//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: base_gcmessages.proto
// Note: requires additional types generated from: steammessages.proto
namespace nora.protos
{
  public partial class CGCStorePurchaseInit_LineItem : global::ProtoBuf.IExtensible
  {
    public CGCStorePurchaseInit_LineItem() {}
    

    private uint _item_def_id = default(uint);
    public uint item_def_id
    {
      get { return _item_def_id; }
      set { _item_def_id = value; }
    }

    private uint _quantity = default(uint);
    public uint quantity
    {
      get { return _quantity; }
      set { _quantity = value; }
    }

    private uint _cost_in_local_currency = default(uint);
    public uint cost_in_local_currency
    {
      get { return _cost_in_local_currency; }
      set { _cost_in_local_currency = value; }
    }

    private uint _purchase_type = default(uint);
    public uint purchase_type
    {
      get { return _purchase_type; }
      set { _purchase_type = value; }
    }

    private ulong _source_reference_id = default(ulong);
    public ulong source_reference_id
    {
      get { return _source_reference_id; }
      set { _source_reference_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCStorePurchaseInit : global::ProtoBuf.IExtensible
  {
    public CMsgGCStorePurchaseInit() {}
    

    private string _country = "";
    public string country
    {
      get { return _country; }
      set { _country = value; }
    }

    private int _language = default(int);
    public int language
    {
      get { return _language; }
      set { _language = value; }
    }

    private int _currency = default(int);
    public int currency
    {
      get { return _currency; }
      set { _currency = value; }
    }
    private readonly global::System.Collections.Generic.List<CGCStorePurchaseInit_LineItem> _line_items = new global::System.Collections.Generic.List<CGCStorePurchaseInit_LineItem>();
    public global::System.Collections.Generic.List<CGCStorePurchaseInit_LineItem> line_items
    {
      get { return _line_items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCStorePurchaseInitResponse : global::ProtoBuf.IExtensible
  {
    public CMsgGCStorePurchaseInitResponse() {}
    

    private int _result = default(int);
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private ulong _txn_id = default(ulong);
    public ulong txn_id
    {
      get { return _txn_id; }
      set { _txn_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOPartyInvite : global::ProtoBuf.IExtensible
  {
    public CSOPartyInvite() {}
    

    private ulong _group_id = default(ulong);
    public ulong group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }

    private ulong _sender_id = default(ulong);
    public ulong sender_id
    {
      get { return _sender_id; }
      set { _sender_id = value; }
    }

    private string _sender_name = "";
    public string sender_name
    {
      get { return _sender_name; }
      set { _sender_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOLobbyInvite : global::ProtoBuf.IExtensible
  {
    public CSOLobbyInvite() {}
    

    private ulong _group_id = default(ulong);
    public ulong group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }

    private ulong _sender_id = default(ulong);
    public ulong sender_id
    {
      get { return _sender_id; }
      set { _sender_id = value; }
    }

    private string _sender_name = "";
    public string sender_name
    {
      get { return _sender_name; }
      set { _sender_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgSystemBroadcast : global::ProtoBuf.IExtensible
  {
    public CMsgSystemBroadcast() {}
    

    private string _message = "";
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgInviteToParty : global::ProtoBuf.IExtensible
  {
    public CMsgInviteToParty() {}
    

    private ulong _steam_id = default(ulong);
    public ulong steam_id
    {
      get { return _steam_id; }
      set { _steam_id = value; }
    }

    private uint _client_version = default(uint);
    public uint client_version
    {
      get { return _client_version; }
      set { _client_version = value; }
    }

    private uint _team_id = default(uint);
    public uint team_id
    {
      get { return _team_id; }
      set { _team_id = value; }
    }

    private bool _as_coach = default(bool);
    public bool as_coach
    {
      get { return _as_coach; }
      set { _as_coach = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgInvitationCreated : global::ProtoBuf.IExtensible
  {
    public CMsgInvitationCreated() {}
    

    private ulong _group_id = default(ulong);
    public ulong group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }

    private ulong _steam_id = default(ulong);
    public ulong steam_id
    {
      get { return _steam_id; }
      set { _steam_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgPartyInviteResponse : global::ProtoBuf.IExtensible
  {
    public CMsgPartyInviteResponse() {}
    

    private ulong _party_id = default(ulong);
    public ulong party_id
    {
      get { return _party_id; }
      set { _party_id = value; }
    }

    private bool _accept = default(bool);
    public bool accept
    {
      get { return _accept; }
      set { _accept = value; }
    }

    private uint _client_version = default(uint);
    public uint client_version
    {
      get { return _client_version; }
      set { _client_version = value; }
    }

    private uint _team_id = default(uint);
    public uint team_id
    {
      get { return _team_id; }
      set { _team_id = value; }
    }

    private bool _as_coach = default(bool);
    public bool as_coach
    {
      get { return _as_coach; }
      set { _as_coach = value; }
    }

    private uint _game_language_enum = default(uint);
    public uint game_language_enum
    {
      get { return _game_language_enum; }
      set { _game_language_enum = value; }
    }

    private string _game_language_name = "";
    public string game_language_name
    {
      get { return _game_language_name; }
      set { _game_language_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgKickFromParty : global::ProtoBuf.IExtensible
  {
    public CMsgKickFromParty() {}
    

    private ulong _steam_id = default(ulong);
    public ulong steam_id
    {
      get { return _steam_id; }
      set { _steam_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgLeaveParty : global::ProtoBuf.IExtensible
  {
    public CMsgLeaveParty() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgServerAvailable : global::ProtoBuf.IExtensible
  {
    public CMsgServerAvailable() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgLANServerAvailable : global::ProtoBuf.IExtensible
  {
    public CMsgLANServerAvailable() {}
    

    private ulong _lobby_id = default(ulong);
    public ulong lobby_id
    {
      get { return _lobby_id; }
      set { _lobby_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOEconGameAccountClient : global::ProtoBuf.IExtensible
  {
    public CSOEconGameAccountClient() {}
    

    private uint _additional_backpack_slots = (uint)0;
    public uint additional_backpack_slots
    {
      get { return _additional_backpack_slots; }
      set { _additional_backpack_slots = value; }
    }

    private bool _trial_account = (bool)false;
    public bool trial_account
    {
      get { return _trial_account; }
      set { _trial_account = value; }
    }

    private bool _eligible_for_online_play = (bool)true;
    public bool eligible_for_online_play
    {
      get { return _eligible_for_online_play; }
      set { _eligible_for_online_play = value; }
    }

    private bool _need_to_choose_most_helpful_friend = default(bool);
    public bool need_to_choose_most_helpful_friend
    {
      get { return _need_to_choose_most_helpful_friend; }
      set { _need_to_choose_most_helpful_friend = value; }
    }

    private bool _in_coaches_list = default(bool);
    public bool in_coaches_list
    {
      get { return _in_coaches_list; }
      set { _in_coaches_list = value; }
    }

    private uint _trade_ban_expiration = default(uint);
    public uint trade_ban_expiration
    {
      get { return _trade_ban_expiration; }
      set { _trade_ban_expiration = value; }
    }

    private uint _duel_ban_expiration = default(uint);
    public uint duel_ban_expiration
    {
      get { return _duel_ban_expiration; }
      set { _duel_ban_expiration = value; }
    }

    private uint _preview_item_def = (uint)0;
    public uint preview_item_def
    {
      get { return _preview_item_def; }
      set { _preview_item_def = value; }
    }

    private bool _made_first_purchase = (bool)false;
    public bool made_first_purchase
    {
      get { return _made_first_purchase; }
      set { _made_first_purchase = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOItemCriteriaCondition : global::ProtoBuf.IExtensible
  {
    public CSOItemCriteriaCondition() {}
    

    private int _op = default(int);
    public int op
    {
      get { return _op; }
      set { _op = value; }
    }

    private string _field = "";
    public string field
    {
      get { return _field; }
      set { _field = value; }
    }

    private bool _required = default(bool);
    public bool required
    {
      get { return _required; }
      set { _required = value; }
    }

    private float _float_value = default(float);
    public float float_value
    {
      get { return _float_value; }
      set { _float_value = value; }
    }

    private string _string_value = "";
    public string string_value
    {
      get { return _string_value; }
      set { _string_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOItemCriteria : global::ProtoBuf.IExtensible
  {
    public CSOItemCriteria() {}
    

    private uint _item_level = default(uint);
    public uint item_level
    {
      get { return _item_level; }
      set { _item_level = value; }
    }

    private int _item_quality = default(int);
    public int item_quality
    {
      get { return _item_quality; }
      set { _item_quality = value; }
    }

    private bool _item_level_set = default(bool);
    public bool item_level_set
    {
      get { return _item_level_set; }
      set { _item_level_set = value; }
    }

    private bool _item_quality_set = default(bool);
    public bool item_quality_set
    {
      get { return _item_quality_set; }
      set { _item_quality_set = value; }
    }

    private uint _initial_inventory = default(uint);
    public uint initial_inventory
    {
      get { return _initial_inventory; }
      set { _initial_inventory = value; }
    }

    private uint _initial_quantity = default(uint);
    public uint initial_quantity
    {
      get { return _initial_quantity; }
      set { _initial_quantity = value; }
    }

    private bool _ignore_enabled_flag = default(bool);
    public bool ignore_enabled_flag
    {
      get { return _ignore_enabled_flag; }
      set { _ignore_enabled_flag = value; }
    }
    private readonly global::System.Collections.Generic.List<CSOItemCriteriaCondition> _conditions = new global::System.Collections.Generic.List<CSOItemCriteriaCondition>();
    public global::System.Collections.Generic.List<CSOItemCriteriaCondition> conditions
    {
      get { return _conditions; }
    }
  

    private bool _recent_only = default(bool);
    public bool recent_only
    {
      get { return _recent_only; }
      set { _recent_only = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOItemRecipe : global::ProtoBuf.IExtensible
  {
    public CSOItemRecipe() {}
    

    private uint _def_index = default(uint);
    public uint def_index
    {
      get { return _def_index; }
      set { _def_index = value; }
    }

    private string _name = "";
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _n_a = "";
    public string n_a
    {
      get { return _n_a; }
      set { _n_a = value; }
    }

    private string _desc_inputs = "";
    public string desc_inputs
    {
      get { return _desc_inputs; }
      set { _desc_inputs = value; }
    }

    private string _desc_outputs = "";
    public string desc_outputs
    {
      get { return _desc_outputs; }
      set { _desc_outputs = value; }
    }

    private string _di_a = "";
    public string di_a
    {
      get { return _di_a; }
      set { _di_a = value; }
    }

    private string _di_b = "";
    public string di_b
    {
      get { return _di_b; }
      set { _di_b = value; }
    }

    private string _di_c = "";
    public string di_c
    {
      get { return _di_c; }
      set { _di_c = value; }
    }

    private string _do_a = "";
    public string do_a
    {
      get { return _do_a; }
      set { _do_a = value; }
    }

    private string _do_b = "";
    public string do_b
    {
      get { return _do_b; }
      set { _do_b = value; }
    }

    private string _do_c = "";
    public string do_c
    {
      get { return _do_c; }
      set { _do_c = value; }
    }

    private bool _requires_all_same_class = default(bool);
    public bool requires_all_same_class
    {
      get { return _requires_all_same_class; }
      set { _requires_all_same_class = value; }
    }

    private bool _requires_all_same_slot = default(bool);
    public bool requires_all_same_slot
    {
      get { return _requires_all_same_slot; }
      set { _requires_all_same_slot = value; }
    }

    private int _class_usage_for_output = default(int);
    public int class_usage_for_output
    {
      get { return _class_usage_for_output; }
      set { _class_usage_for_output = value; }
    }

    private int _slot_usage_for_output = default(int);
    public int slot_usage_for_output
    {
      get { return _slot_usage_for_output; }
      set { _slot_usage_for_output = value; }
    }

    private int _set_for_output = default(int);
    public int set_for_output
    {
      get { return _set_for_output; }
      set { _set_for_output = value; }
    }
    private readonly global::System.Collections.Generic.List<CSOItemCriteria> _input_items_criteria = new global::System.Collections.Generic.List<CSOItemCriteria>();
    public global::System.Collections.Generic.List<CSOItemCriteria> input_items_criteria
    {
      get { return _input_items_criteria; }
    }
  
    private readonly global::System.Collections.Generic.List<CSOItemCriteria> _output_items_criteria = new global::System.Collections.Generic.List<CSOItemCriteria>();
    public global::System.Collections.Generic.List<CSOItemCriteria> output_items_criteria
    {
      get { return _output_items_criteria; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _input_item_dupe_counts = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> input_item_dupe_counts
    {
      get { return _input_item_dupe_counts; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDevNewItemRequest : global::ProtoBuf.IExtensible
  {
    public CMsgDevNewItemRequest() {}
    

    private ulong _receiver = default(ulong);
    public ulong receiver
    {
      get { return _receiver; }
      set { _receiver = value; }
    }

    private CSOItemCriteria _criteria = null;
    public CSOItemCriteria criteria
    {
      get { return _criteria; }
      set { _criteria = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgApplyStrangePart : global::ProtoBuf.IExtensible
  {
    public CMsgApplyStrangePart() {}
    

    private ulong _strange_part_item_id = default(ulong);
    public ulong strange_part_item_id
    {
      get { return _strange_part_item_id; }
      set { _strange_part_item_id = value; }
    }

    private ulong _item_item_id = default(ulong);
    public ulong item_item_id
    {
      get { return _item_item_id; }
      set { _item_item_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgApplyPennantUpgrade : global::ProtoBuf.IExtensible
  {
    public CMsgApplyPennantUpgrade() {}
    

    private ulong _upgrade_item_id = default(ulong);
    public ulong upgrade_item_id
    {
      get { return _upgrade_item_id; }
      set { _upgrade_item_id = value; }
    }

    private ulong _pennant_item_id = default(ulong);
    public ulong pennant_item_id
    {
      get { return _pennant_item_id; }
      set { _pennant_item_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgApplyEggEssence : global::ProtoBuf.IExtensible
  {
    public CMsgApplyEggEssence() {}
    

    private ulong _essence_item_id = default(ulong);
    public ulong essence_item_id
    {
      get { return _essence_item_id; }
      set { _essence_item_id = value; }
    }

    private ulong _egg_item_id = default(ulong);
    public ulong egg_item_id
    {
      get { return _egg_item_id; }
      set { _egg_item_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOEconItemAttribute : global::ProtoBuf.IExtensible
  {
    public CSOEconItemAttribute() {}
    

    private uint _def_index = default(uint);
    public uint def_index
    {
      get { return _def_index; }
      set { _def_index = value; }
    }

    private uint _value = default(uint);
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }

    private byte[] _value_bytes = null;
    public byte[] value_bytes
    {
      get { return _value_bytes; }
      set { _value_bytes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOEconItemEquipped : global::ProtoBuf.IExtensible
  {
    public CSOEconItemEquipped() {}
    

    private uint _new_class = default(uint);
    public uint new_class
    {
      get { return _new_class; }
      set { _new_class = value; }
    }

    private uint _new_slot = default(uint);
    public uint new_slot
    {
      get { return _new_slot; }
      set { _new_slot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOEconItem : global::ProtoBuf.IExtensible
  {
    public CSOEconItem() {}
    

    private ulong _id = default(ulong);
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _inventory = default(uint);
    public uint inventory
    {
      get { return _inventory; }
      set { _inventory = value; }
    }

    private uint _def_index = default(uint);
    public uint def_index
    {
      get { return _def_index; }
      set { _def_index = value; }
    }

    private uint _quantity = (uint)1;
    public uint quantity
    {
      get { return _quantity; }
      set { _quantity = value; }
    }

    private uint _level = (uint)1;
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }

    private uint _quality = (uint)4;
    public uint quality
    {
      get { return _quality; }
      set { _quality = value; }
    }

    private uint _flags = (uint)0;
    public uint flags
    {
      get { return _flags; }
      set { _flags = value; }
    }

    private uint _origin = (uint)0;
    public uint origin
    {
      get { return _origin; }
      set { _origin = value; }
    }
    private readonly global::System.Collections.Generic.List<CSOEconItemAttribute> _attribute = new global::System.Collections.Generic.List<CSOEconItemAttribute>();
    public global::System.Collections.Generic.List<CSOEconItemAttribute> attribute
    {
      get { return _attribute; }
    }
  

    private CSOEconItem _interior_item = null;
    public CSOEconItem interior_item
    {
      get { return _interior_item; }
      set { _interior_item = value; }
    }

    private bool _in_use = (bool)false;
    public bool in_use
    {
      get { return _in_use; }
      set { _in_use = value; }
    }

    private uint _style = (uint)0;
    public uint style
    {
      get { return _style; }
      set { _style = value; }
    }

    private ulong _original_id = (ulong)0;
    public ulong original_id
    {
      get { return _original_id; }
      set { _original_id = value; }
    }
    private readonly global::System.Collections.Generic.List<CSOEconItemEquipped> _equipped_state = new global::System.Collections.Generic.List<CSOEconItemEquipped>();
    public global::System.Collections.Generic.List<CSOEconItemEquipped> equipped_state
    {
      get { return _equipped_state; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgAdjustItemEquippedState : global::ProtoBuf.IExtensible
  {
    public CMsgAdjustItemEquippedState() {}
    

    private ulong _item_id = default(ulong);
    public ulong item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }

    private uint _new_class = default(uint);
    public uint new_class
    {
      get { return _new_class; }
      set { _new_class = value; }
    }

    private uint _new_slot = default(uint);
    public uint new_slot
    {
      get { return _new_slot; }
      set { _new_slot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgSortItems : global::ProtoBuf.IExtensible
  {
    public CMsgSortItems() {}
    

    private uint _sort_type = default(uint);
    public uint sort_type
    {
      get { return _sort_type; }
      set { _sort_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOEconClaimCode : global::ProtoBuf.IExtensible
  {
    public CSOEconClaimCode() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _code_type = default(uint);
    public uint code_type
    {
      get { return _code_type; }
      set { _code_type = value; }
    }

    private uint _time_acquired = default(uint);
    public uint time_acquired
    {
      get { return _time_acquired; }
      set { _time_acquired = value; }
    }

    private string _code = "";
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgStoreGetUserData : global::ProtoBuf.IExtensible
  {
    public CMsgStoreGetUserData() {}
    

    private uint _price_sheet_version = default(uint);
    public uint price_sheet_version
    {
      get { return _price_sheet_version; }
      set { _price_sheet_version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgStoreGetUserDataResponse : global::ProtoBuf.IExtensible
  {
    public CMsgStoreGetUserDataResponse() {}
    

    private int _result = default(int);
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private int _currency = default(int);
    public int currency
    {
      get { return _currency; }
      set { _currency = value; }
    }

    private string _country = "";
    public string country
    {
      get { return _country; }
      set { _country = value; }
    }

    private uint _price_sheet_version = default(uint);
    public uint price_sheet_version
    {
      get { return _price_sheet_version; }
      set { _price_sheet_version = value; }
    }

    private ulong _experiment_data = (ulong)0;
    public ulong experiment_data
    {
      get { return _experiment_data; }
      set { _experiment_data = value; }
    }

    private int _featured_item_idx = default(int);
    public int featured_item_idx
    {
      get { return _featured_item_idx; }
      set { _featured_item_idx = value; }
    }

    private bool _show_hat_descriptions = (bool)true;
    public bool show_hat_descriptions
    {
      get { return _show_hat_descriptions; }
      set { _show_hat_descriptions = value; }
    }

    private byte[] _price_sheet = null;
    public byte[] price_sheet
    {
      get { return _price_sheet; }
      set { _price_sheet = value; }
    }

    private int _default_item_sort = (int)0;
    public int default_item_sort
    {
      get { return _default_item_sort; }
      set { _default_item_sort = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _popular_items = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> popular_items
    {
      get { return _popular_items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgUpdateItemSchema : global::ProtoBuf.IExtensible
  {
    public CMsgUpdateItemSchema() {}
    

    private byte[] _items_game = null;
    public byte[] items_game
    {
      get { return _items_game; }
      set { _items_game = value; }
    }

    private uint _item_schema_version = default(uint);
    public uint item_schema_version
    {
      get { return _item_schema_version; }
      set { _item_schema_version = value; }
    }

    private string _items_game_url = "";
    public string items_game_url
    {
      get { return _items_game_url; }
      set { _items_game_url = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCError : global::ProtoBuf.IExtensible
  {
    public CMsgGCError() {}
    

    private string _error_text = "";
    public string error_text
    {
      get { return _error_text; }
      set { _error_text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgRequestInventoryRefresh : global::ProtoBuf.IExtensible
  {
    public CMsgRequestInventoryRefresh() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgConVarValue : global::ProtoBuf.IExtensible
  {
    public CMsgConVarValue() {}
    

    private string _name = "";
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _value = "";
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgReplicateConVars : global::ProtoBuf.IExtensible
  {
    public CMsgReplicateConVars() {}
    
    private readonly global::System.Collections.Generic.List<CMsgConVarValue> _convars = new global::System.Collections.Generic.List<CMsgConVarValue>();
    public global::System.Collections.Generic.List<CMsgConVarValue> convars
    {
      get { return _convars; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgReplayUploadedToYouTube : global::ProtoBuf.IExtensible
  {
    public CMsgReplayUploadedToYouTube() {}
    

    private string _youtube_url = "";
    public string youtube_url
    {
      get { return _youtube_url; }
      set { _youtube_url = value; }
    }

    private string _youtube_account_name = "";
    public string youtube_account_name
    {
      get { return _youtube_account_name; }
      set { _youtube_account_name = value; }
    }

    private ulong _session_id = default(ulong);
    public ulong session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgConsumableExhausted : global::ProtoBuf.IExtensible
  {
    public CMsgConsumableExhausted() {}
    

    private int _item_def_id = default(int);
    public int item_def_id
    {
      get { return _item_def_id; }
      set { _item_def_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgItemAcknowledged : global::ProtoBuf.IExtensible
  {
    public CMsgItemAcknowledged() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _inventory = default(uint);
    public uint inventory
    {
      get { return _inventory; }
      set { _inventory = value; }
    }

    private uint _def_index = default(uint);
    public uint def_index
    {
      get { return _def_index; }
      set { _def_index = value; }
    }

    private uint _quality = default(uint);
    public uint quality
    {
      get { return _quality; }
      set { _quality = value; }
    }

    private uint _rarity = default(uint);
    public uint rarity
    {
      get { return _rarity; }
      set { _rarity = value; }
    }

    private uint _origin = default(uint);
    public uint origin
    {
      get { return _origin; }
      set { _origin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgSetPresetItemPosition : global::ProtoBuf.IExtensible
  {
    public CMsgSetPresetItemPosition() {}
    

    private uint _class_id = default(uint);
    public uint class_id
    {
      get { return _class_id; }
      set { _class_id = value; }
    }

    private uint _preset_id = default(uint);
    public uint preset_id
    {
      get { return _preset_id; }
      set { _preset_id = value; }
    }

    private uint _slot_id = default(uint);
    public uint slot_id
    {
      get { return _slot_id; }
      set { _slot_id = value; }
    }

    private ulong _item_id = default(ulong);
    public ulong item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgSetItemPositions : global::ProtoBuf.IExtensible
  {
    public CMsgSetItemPositions() {}
    
    private readonly global::System.Collections.Generic.List<CMsgSetItemPositions.ItemPosition> _item_positions = new global::System.Collections.Generic.List<CMsgSetItemPositions.ItemPosition>();
    public global::System.Collections.Generic.List<CMsgSetItemPositions.ItemPosition> item_positions
    {
      get { return _item_positions; }
    }
  
  public partial class ItemPosition : global::ProtoBuf.IExtensible
  {
    public ItemPosition() {}
    

    private ulong _item_id = default(ulong);
    public ulong item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }

    private uint _position = default(uint);
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOEconItemPresetInstance : global::ProtoBuf.IExtensible
  {
    public CSOEconItemPresetInstance() {}
    

    private uint _class_id = default(uint);
    public uint class_id
    {
      get { return _class_id; }
      set { _class_id = value; }
    }

    private uint _preset_id = default(uint);
    public uint preset_id
    {
      get { return _preset_id; }
      set { _preset_id = value; }
    }

    private uint _slot_id = default(uint);
    public uint slot_id
    {
      get { return _slot_id; }
      set { _slot_id = value; }
    }

    private ulong _item_id = default(ulong);
    public ulong item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgSelectItemPresetForClass : global::ProtoBuf.IExtensible
  {
    public CMsgSelectItemPresetForClass() {}
    

    private uint _class_id = default(uint);
    public uint class_id
    {
      get { return _class_id; }
      set { _class_id = value; }
    }

    private uint _preset_id = default(uint);
    public uint preset_id
    {
      get { return _preset_id; }
      set { _preset_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgSelectItemPresetForClassReply : global::ProtoBuf.IExtensible
  {
    public CMsgSelectItemPresetForClassReply() {}
    

    private bool _success = default(bool);
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOSelectedItemPreset : global::ProtoBuf.IExtensible
  {
    public CSOSelectedItemPreset() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _class_id = default(uint);
    public uint class_id
    {
      get { return _class_id; }
      set { _class_id = value; }
    }

    private uint _preset_id = default(uint);
    public uint preset_id
    {
      get { return _preset_id; }
      set { _preset_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCReportAbuse : global::ProtoBuf.IExtensible
  {
    public CMsgGCReportAbuse() {}
    

    private ulong _target_steam_id = default(ulong);
    public ulong target_steam_id
    {
      get { return _target_steam_id; }
      set { _target_steam_id = value; }
    }

    private string _description = "";
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }

    private ulong _gid = default(ulong);
    public ulong gid
    {
      get { return _gid; }
      set { _gid = value; }
    }

    private uint _abuse_type = default(uint);
    public uint abuse_type
    {
      get { return _abuse_type; }
      set { _abuse_type = value; }
    }

    private uint _content_type = default(uint);
    public uint content_type
    {
      get { return _content_type; }
      set { _content_type = value; }
    }

    private uint _target_game_server_ip = default(uint);
    public uint target_game_server_ip
    {
      get { return _target_game_server_ip; }
      set { _target_game_server_ip = value; }
    }

    private uint _target_game_server_port = default(uint);
    public uint target_game_server_port
    {
      get { return _target_game_server_port; }
      set { _target_game_server_port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCReportAbuseResponse : global::ProtoBuf.IExtensible
  {
    public CMsgGCReportAbuseResponse() {}
    

    private ulong _target_steam_id = default(ulong);
    public ulong target_steam_id
    {
      get { return _target_steam_id; }
      set { _target_steam_id = value; }
    }

    private uint _result = default(uint);
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private string _error_message = "";
    public string error_message
    {
      get { return _error_message; }
      set { _error_message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCNameItemNotification : global::ProtoBuf.IExtensible
  {
    public CMsgGCNameItemNotification() {}
    

    private ulong _player_steamid = default(ulong);
    public ulong player_steamid
    {
      get { return _player_steamid; }
      set { _player_steamid = value; }
    }

    private uint _item_def_index = default(uint);
    public uint item_def_index
    {
      get { return _item_def_index; }
      set { _item_def_index = value; }
    }

    private string _item_name_custom = "";
    public string item_name_custom
    {
      get { return _item_name_custom; }
      set { _item_name_custom = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCClientDisplayNotification : global::ProtoBuf.IExtensible
  {
    public CMsgGCClientDisplayNotification() {}
    

    private string _notification_title_localization_key = "";
    public string notification_title_localization_key
    {
      get { return _notification_title_localization_key; }
      set { _notification_title_localization_key = value; }
    }

    private string _notification_body_localization_key = "";
    public string notification_body_localization_key
    {
      get { return _notification_body_localization_key; }
      set { _notification_body_localization_key = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _body_substring_keys = new global::System.Collections.Generic.List<string>();
    public global::System.Collections.Generic.List<string> body_substring_keys
    {
      get { return _body_substring_keys; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _body_substring_values = new global::System.Collections.Generic.List<string>();
    public global::System.Collections.Generic.List<string> body_substring_values
    {
      get { return _body_substring_values; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCShowItemsPickedUp : global::ProtoBuf.IExtensible
  {
    public CMsgGCShowItemsPickedUp() {}
    

    private ulong _player_steamid = default(ulong);
    public ulong player_steamid
    {
      get { return _player_steamid; }
      set { _player_steamid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCIncrementKillCountResponse : global::ProtoBuf.IExtensible
  {
    public CMsgGCIncrementKillCountResponse() {}
    

    private uint _killer_account_id = default(uint);
    public uint killer_account_id
    {
      get { return _killer_account_id; }
      set { _killer_account_id = value; }
    }

    private uint _num_kills = default(uint);
    public uint num_kills
    {
      get { return _num_kills; }
      set { _num_kills = value; }
    }

    private uint _item_def = default(uint);
    public uint item_def
    {
      get { return _item_def; }
      set { _item_def = value; }
    }

    private uint _level_type = default(uint);
    public uint level_type
    {
      get { return _level_type; }
      set { _level_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOEconItemDropRateBonus : global::ProtoBuf.IExtensible
  {
    public CSOEconItemDropRateBonus() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _expiration_date = default(uint);
    public uint expiration_date
    {
      get { return _expiration_date; }
      set { _expiration_date = value; }
    }

    private float _bonus = default(float);
    public float bonus
    {
      get { return _bonus; }
      set { _bonus = value; }
    }

    private uint _bonus_count = default(uint);
    public uint bonus_count
    {
      get { return _bonus_count; }
      set { _bonus_count = value; }
    }

    private ulong _item_id = default(ulong);
    public ulong item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }

    private uint _def_index = default(uint);
    public uint def_index
    {
      get { return _def_index; }
      set { _def_index = value; }
    }

    private uint _seconds_left = default(uint);
    public uint seconds_left
    {
      get { return _seconds_left; }
      set { _seconds_left = value; }
    }

    private uint _booster_type = default(uint);
    public uint booster_type
    {
      get { return _booster_type; }
      set { _booster_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOEconItemLeagueViewPass : global::ProtoBuf.IExtensible
  {
    public CSOEconItemLeagueViewPass() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _league_id = default(uint);
    public uint league_id
    {
      get { return _league_id; }
      set { _league_id = value; }
    }

    private uint _itemindex = default(uint);
    public uint itemindex
    {
      get { return _itemindex; }
      set { _itemindex = value; }
    }

    private uint _grant_reason = default(uint);
    public uint grant_reason
    {
      get { return _grant_reason; }
      set { _grant_reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOEconItemEventTicket : global::ProtoBuf.IExtensible
  {
    public CSOEconItemEventTicket() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _event_id = default(uint);
    public uint event_id
    {
      get { return _event_id; }
      set { _event_id = value; }
    }

    private ulong _item_id = default(ulong);
    public ulong item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSOEconItemTournamentPassport : global::ProtoBuf.IExtensible
  {
    public CSOEconItemTournamentPassport() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _league_id = default(uint);
    public uint league_id
    {
      get { return _league_id; }
      set { _league_id = value; }
    }

    private ulong _item_id = default(ulong);
    public ulong item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }

    private uint _original_purchaser_id = default(uint);
    public uint original_purchaser_id
    {
      get { return _original_purchaser_id; }
      set { _original_purchaser_id = value; }
    }

    private uint _passports_bought = default(uint);
    public uint passports_bought
    {
      get { return _passports_bought; }
      set { _passports_bought = value; }
    }

    private uint _version = default(uint);
    public uint version
    {
      get { return _version; }
      set { _version = value; }
    }

    private uint _def_index = default(uint);
    public uint def_index
    {
      get { return _def_index; }
      set { _def_index = value; }
    }

    private uint _reward_flags = default(uint);
    public uint reward_flags
    {
      get { return _reward_flags; }
      set { _reward_flags = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCItemPreviewItemBoughtNotification : global::ProtoBuf.IExtensible
  {
    public CMsgGCItemPreviewItemBoughtNotification() {}
    

    private uint _item_def_index = default(uint);
    public uint item_def_index
    {
      get { return _item_def_index; }
      set { _item_def_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCStorePurchaseCancel : global::ProtoBuf.IExtensible
  {
    public CMsgGCStorePurchaseCancel() {}
    

    private ulong _txn_id = default(ulong);
    public ulong txn_id
    {
      get { return _txn_id; }
      set { _txn_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCStorePurchaseCancelResponse : global::ProtoBuf.IExtensible
  {
    public CMsgGCStorePurchaseCancelResponse() {}
    

    private uint _result = default(uint);
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCStorePurchaseFinalize : global::ProtoBuf.IExtensible
  {
    public CMsgGCStorePurchaseFinalize() {}
    

    private ulong _txn_id = default(ulong);
    public ulong txn_id
    {
      get { return _txn_id; }
      set { _txn_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCStorePurchaseFinalizeResponse : global::ProtoBuf.IExtensible
  {
    public CMsgGCStorePurchaseFinalizeResponse() {}
    

    private uint _result = default(uint);
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _item_ids = new global::System.Collections.Generic.List<ulong>();
    public global::System.Collections.Generic.List<ulong> item_ids
    {
      get { return _item_ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCBannedWordListRequest : global::ProtoBuf.IExtensible
  {
    public CMsgGCBannedWordListRequest() {}
    

    private uint _ban_list_group_id = default(uint);
    public uint ban_list_group_id
    {
      get { return _ban_list_group_id; }
      set { _ban_list_group_id = value; }
    }

    private uint _word_id = default(uint);
    public uint word_id
    {
      get { return _word_id; }
      set { _word_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCBannedWord : global::ProtoBuf.IExtensible
  {
    public CMsgGCBannedWord() {}
    

    private uint _word_id = default(uint);
    public uint word_id
    {
      get { return _word_id; }
      set { _word_id = value; }
    }

    private GC_BannedWordType _word_type = GC_BannedWordType.GC_BANNED_WORD_DISABLE_WORD;
    public GC_BannedWordType word_type
    {
      get { return _word_type; }
      set { _word_type = value; }
    }

    private string _word = "";
    public string word
    {
      get { return _word; }
      set { _word = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCBannedWordListResponse : global::ProtoBuf.IExtensible
  {
    public CMsgGCBannedWordListResponse() {}
    

    private uint _ban_list_group_id = default(uint);
    public uint ban_list_group_id
    {
      get { return _ban_list_group_id; }
      set { _ban_list_group_id = value; }
    }
    private readonly global::System.Collections.Generic.List<CMsgGCBannedWord> _word_list = new global::System.Collections.Generic.List<CMsgGCBannedWord>();
    public global::System.Collections.Generic.List<CMsgGCBannedWord> word_list
    {
      get { return _word_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCToGCBannedWordListBroadcast : global::ProtoBuf.IExtensible
  {
    public CMsgGCToGCBannedWordListBroadcast() {}
    

    private CMsgGCBannedWordListResponse _broadcast = null;
    public CMsgGCBannedWordListResponse broadcast
    {
      get { return _broadcast; }
      set { _broadcast = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCToGCBannedWordListUpdated : global::ProtoBuf.IExtensible
  {
    public CMsgGCToGCBannedWordListUpdated() {}
    

    private uint _group_id = default(uint);
    public uint group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCToGCDirtySDOCache : global::ProtoBuf.IExtensible
  {
    public CMsgGCToGCDirtySDOCache() {}
    

    private uint _sdo_type = default(uint);
    public uint sdo_type
    {
      get { return _sdo_type; }
      set { _sdo_type = value; }
    }

    private ulong _key_uint64 = default(ulong);
    public ulong key_uint64
    {
      get { return _key_uint64; }
      set { _key_uint64 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCToGCDirtyMultipleSDOCache : global::ProtoBuf.IExtensible
  {
    public CMsgGCToGCDirtyMultipleSDOCache() {}
    

    private uint _sdo_type = default(uint);
    public uint sdo_type
    {
      get { return _sdo_type; }
      set { _sdo_type = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _key_uint64 = new global::System.Collections.Generic.List<ulong>();
    public global::System.Collections.Generic.List<ulong> key_uint64
    {
      get { return _key_uint64; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCToGCApplyLocalizationDiff : global::ProtoBuf.IExtensible
  {
    public CMsgGCToGCApplyLocalizationDiff() {}
    

    private uint _language = default(uint);
    public uint language
    {
      get { return _language; }
      set { _language = value; }
    }

    private string _packed_diff = "";
    public string packed_diff
    {
      get { return _packed_diff; }
      set { _packed_diff = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCToGCApplyLocalizationDiffResponse : global::ProtoBuf.IExtensible
  {
    public CMsgGCToGCApplyLocalizationDiffResponse() {}
    

    private bool _success = default(bool);
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCCollectItem : global::ProtoBuf.IExtensible
  {
    public CMsgGCCollectItem() {}
    

    private ulong _collection_item_id = default(ulong);
    public ulong collection_item_id
    {
      get { return _collection_item_id; }
      set { _collection_item_id = value; }
    }

    private ulong _subject_item_id = default(ulong);
    public ulong subject_item_id
    {
      get { return _subject_item_id; }
      set { _subject_item_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgSDONoMemcached : global::ProtoBuf.IExtensible
  {
    public CMsgSDONoMemcached() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCToGCUpdateSQLKeyValue : global::ProtoBuf.IExtensible
  {
    public CMsgGCToGCUpdateSQLKeyValue() {}
    

    private string _key_name = "";
    public string key_name
    {
      get { return _key_name; }
      set { _key_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCToGCBroadcastConsoleCommand : global::ProtoBuf.IExtensible
  {
    public CMsgGCToGCBroadcastConsoleCommand() {}
    

    private string _con_command = "";
    public string con_command
    {
      get { return _con_command; }
      set { _con_command = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCServerVersionUpdated : global::ProtoBuf.IExtensible
  {
    public CMsgGCServerVersionUpdated() {}
    

    private uint _server_version = default(uint);
    public uint server_version
    {
      get { return _server_version; }
      set { _server_version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCClientVersionUpdated : global::ProtoBuf.IExtensible
  {
    public CMsgGCClientVersionUpdated() {}
    

    private uint _client_version = default(uint);
    public uint client_version
    {
      get { return _client_version; }
      set { _client_version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCToGCWebAPIAccountChanged : global::ProtoBuf.IExtensible
  {
    public CMsgGCToGCWebAPIAccountChanged() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgRecipeComponent : global::ProtoBuf.IExtensible
  {
    public CMsgRecipeComponent() {}
    

    private ulong _subject_item_id = default(ulong);
    public ulong subject_item_id
    {
      get { return _subject_item_id; }
      set { _subject_item_id = value; }
    }

    private ulong _attribute_index = default(ulong);
    public ulong attribute_index
    {
      get { return _attribute_index; }
      set { _attribute_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgFulfillDynamicRecipeComponent : global::ProtoBuf.IExtensible
  {
    public CMsgFulfillDynamicRecipeComponent() {}
    

    private ulong _tool_item_id = default(ulong);
    public ulong tool_item_id
    {
      get { return _tool_item_id; }
      set { _tool_item_id = value; }
    }
    private readonly global::System.Collections.Generic.List<CMsgRecipeComponent> _consumption_components = new global::System.Collections.Generic.List<CMsgRecipeComponent>();
    public global::System.Collections.Generic.List<CMsgRecipeComponent> consumption_components
    {
      get { return _consumption_components; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCClientMarketDataRequest : global::ProtoBuf.IExtensible
  {
    public CMsgGCClientMarketDataRequest() {}
    

    private uint _user_currency = default(uint);
    public uint user_currency
    {
      get { return _user_currency; }
      set { _user_currency = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCClientMarketDataEntry : global::ProtoBuf.IExtensible
  {
    public CMsgGCClientMarketDataEntry() {}
    

    private uint _item_def_index = default(uint);
    public uint item_def_index
    {
      get { return _item_def_index; }
      set { _item_def_index = value; }
    }

    private uint _item_quality = default(uint);
    public uint item_quality
    {
      get { return _item_quality; }
      set { _item_quality = value; }
    }

    private uint _item_sell_listings = default(uint);
    public uint item_sell_listings
    {
      get { return _item_sell_listings; }
      set { _item_sell_listings = value; }
    }

    private uint _price_in_local_currency = default(uint);
    public uint price_in_local_currency
    {
      get { return _price_in_local_currency; }
      set { _price_in_local_currency = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCClientMarketData : global::ProtoBuf.IExtensible
  {
    public CMsgGCClientMarketData() {}
    
    private readonly global::System.Collections.Generic.List<CMsgGCClientMarketDataEntry> _entries = new global::System.Collections.Generic.List<CMsgGCClientMarketDataEntry>();
    public global::System.Collections.Generic.List<CMsgGCClientMarketDataEntry> entries
    {
      get { return _entries; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgExtractGems : global::ProtoBuf.IExtensible
  {
    public CMsgExtractGems() {}
    

    private ulong _tool_item_id = default(ulong);
    public ulong tool_item_id
    {
      get { return _tool_item_id; }
      set { _tool_item_id = value; }
    }

    private ulong _item_item_id = default(ulong);
    public ulong item_item_id
    {
      get { return _item_item_id; }
      set { _item_item_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgAddSocket : global::ProtoBuf.IExtensible
  {
    public CMsgAddSocket() {}
    

    private ulong _tool_item_id = default(ulong);
    public ulong tool_item_id
    {
      get { return _tool_item_id; }
      set { _tool_item_id = value; }
    }

    private ulong _item_item_id = default(ulong);
    public ulong item_item_id
    {
      get { return _item_item_id; }
      set { _item_item_id = value; }
    }

    private bool _unusual = default(bool);
    public bool unusual
    {
      get { return _unusual; }
      set { _unusual = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgAddSocketResponse : global::ProtoBuf.IExtensible
  {
    public CMsgAddSocketResponse() {}
    

    private ulong _item_id = default(ulong);
    public ulong item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _updated_socket_index = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> updated_socket_index
    {
      get { return _updated_socket_index; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgAddItemToSocketData : global::ProtoBuf.IExtensible
  {
    public CMsgAddItemToSocketData() {}
    

    private ulong _gem_item_id = default(ulong);
    public ulong gem_item_id
    {
      get { return _gem_item_id; }
      set { _gem_item_id = value; }
    }

    private uint _socket_index = default(uint);
    public uint socket_index
    {
      get { return _socket_index; }
      set { _socket_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgAddItemToSocket : global::ProtoBuf.IExtensible
  {
    public CMsgAddItemToSocket() {}
    

    private ulong _item_item_id = default(ulong);
    public ulong item_item_id
    {
      get { return _item_item_id; }
      set { _item_item_id = value; }
    }
    private readonly global::System.Collections.Generic.List<CMsgAddItemToSocketData> _gems_to_socket = new global::System.Collections.Generic.List<CMsgAddItemToSocketData>();
    public global::System.Collections.Generic.List<CMsgAddItemToSocketData> gems_to_socket
    {
      get { return _gems_to_socket; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgAddItemToSocketResponse : global::ProtoBuf.IExtensible
  {
    public CMsgAddItemToSocketResponse() {}
    

    private ulong _item_item_id = default(ulong);
    public ulong item_item_id
    {
      get { return _item_item_id; }
      set { _item_item_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _updated_socket_index = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> updated_socket_index
    {
      get { return _updated_socket_index; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgResetStrangeGemCount : global::ProtoBuf.IExtensible
  {
    public CMsgResetStrangeGemCount() {}
    

    private ulong _item_item_id = default(ulong);
    public ulong item_item_id
    {
      get { return _item_item_id; }
      set { _item_item_id = value; }
    }

    private uint _socket_index = default(uint);
    public uint socket_index
    {
      get { return _socket_index; }
      set { _socket_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public enum EGCBaseMsg
    {
            
      k_EMsgGCSystemMessage = 4001,
            
      k_EMsgGCReplicateConVars = 4002,
            
      k_EMsgGCConVarUpdated = 4003,
            
      k_EMsgGCInviteToParty = 4501,
            
      k_EMsgGCInvitationCreated = 4502,
            
      k_EMsgGCPartyInviteResponse = 4503,
            
      k_EMsgGCKickFromParty = 4504,
            
      k_EMsgGCLeaveParty = 4505,
            
      k_EMsgGCServerAvailable = 4506,
            
      k_EMsgGCClientConnectToServer = 4507,
            
      k_EMsgGCGameServerInfo = 4508,
            
      k_EMsgGCError = 4509,
            
      k_EMsgGCReplay_UploadedToYouTube = 4510,
            
      k_EMsgGCLANServerAvailable = 4511
    }
  
    public enum EGCBaseProtoObjectTypes
    {
            
      k_EProtoObjectPartyInvite = 1001,
            
      k_EProtoObjectLobbyInvite = 1002
    }
  
    public enum GC_BannedWordType
    {
            
      GC_BANNED_WORD_DISABLE_WORD = 0,
            
      GC_BANNED_WORD_ENABLE_WORD = 1
    }
  
}
#pragma warning restore 1591
