//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: demo.proto
// Note: requires additional types generated from: google/protobuf/descriptor.proto
namespace nora.protos
{
  public partial class CDemoFileHeader : global::ProtoBuf.IExtensible
  {
    public CDemoFileHeader() {}
    
    private string _demo_file_stamp;
    public string demo_file_stamp
    {
      get { return _demo_file_stamp; }
      set { _demo_file_stamp = value; }
    }

    private int _network_protocol = default(int);
    public int network_protocol
    {
      get { return _network_protocol; }
      set { _network_protocol = value; }
    }

    private string _server_name = "";
    public string server_name
    {
      get { return _server_name; }
      set { _server_name = value; }
    }

    private string _client_name = "";
    public string client_name
    {
      get { return _client_name; }
      set { _client_name = value; }
    }

    private string _map_name = "";
    public string map_name
    {
      get { return _map_name; }
      set { _map_name = value; }
    }

    private string _game_directory = "";
    public string game_directory
    {
      get { return _game_directory; }
      set { _game_directory = value; }
    }

    private int _fullpackets_version = default(int);
    public int fullpackets_version
    {
      get { return _fullpackets_version; }
      set { _fullpackets_version = value; }
    }

    private bool _allow_clientside_entities = default(bool);
    public bool allow_clientside_entities
    {
      get { return _allow_clientside_entities; }
      set { _allow_clientside_entities = value; }
    }

    private bool _allow_clientside_particles = default(bool);
    public bool allow_clientside_particles
    {
      get { return _allow_clientside_particles; }
      set { _allow_clientside_particles = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CGameInfo : global::ProtoBuf.IExtensible
  {
    public CGameInfo() {}
    

    private CGameInfo.CDotaGameInfo _dota = null;
    public CGameInfo.CDotaGameInfo dota
    {
      get { return _dota; }
      set { _dota = value; }
    }
  public partial class CDotaGameInfo : global::ProtoBuf.IExtensible
  {
    public CDotaGameInfo() {}
    

    private uint _match_id = default(uint);
    public uint match_id
    {
      get { return _match_id; }
      set { _match_id = value; }
    }

    private int _game_mode = default(int);
    public int game_mode
    {
      get { return _game_mode; }
      set { _game_mode = value; }
    }

    private int _game_winner = default(int);
    public int game_winner
    {
      get { return _game_winner; }
      set { _game_winner = value; }
    }
    private readonly global::System.Collections.Generic.List<CGameInfo.CDotaGameInfo.CPlayerInfo> _player_info = new global::System.Collections.Generic.List<CGameInfo.CDotaGameInfo.CPlayerInfo>();
    public global::System.Collections.Generic.List<CGameInfo.CDotaGameInfo.CPlayerInfo> player_info
    {
      get { return _player_info; }
    }
  

    private uint _leagueid = default(uint);
    public uint leagueid
    {
      get { return _leagueid; }
      set { _leagueid = value; }
    }
    private readonly global::System.Collections.Generic.List<CGameInfo.CDotaGameInfo.CHeroSelectEvent> _picks_bans = new global::System.Collections.Generic.List<CGameInfo.CDotaGameInfo.CHeroSelectEvent>();
    public global::System.Collections.Generic.List<CGameInfo.CDotaGameInfo.CHeroSelectEvent> picks_bans
    {
      get { return _picks_bans; }
    }
  

    private uint _radiant_team_id = default(uint);
    public uint radiant_team_id
    {
      get { return _radiant_team_id; }
      set { _radiant_team_id = value; }
    }

    private uint _dire_team_id = default(uint);
    public uint dire_team_id
    {
      get { return _dire_team_id; }
      set { _dire_team_id = value; }
    }

    private string _radiant_team_tag = "";
    public string radiant_team_tag
    {
      get { return _radiant_team_tag; }
      set { _radiant_team_tag = value; }
    }

    private string _dire_team_tag = "";
    public string dire_team_tag
    {
      get { return _dire_team_tag; }
      set { _dire_team_tag = value; }
    }

    private uint _end_time = default(uint);
    public uint end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
  public partial class CPlayerInfo : global::ProtoBuf.IExtensible
  {
    public CPlayerInfo() {}
    

    private string _hero_name = "";
    public string hero_name
    {
      get { return _hero_name; }
      set { _hero_name = value; }
    }

    private string _player_name = "";
    public string player_name
    {
      get { return _player_name; }
      set { _player_name = value; }
    }

    private bool _is_fake_client = default(bool);
    public bool is_fake_client
    {
      get { return _is_fake_client; }
      set { _is_fake_client = value; }
    }

    private ulong _steamid = default(ulong);
    public ulong steamid
    {
      get { return _steamid; }
      set { _steamid = value; }
    }

    private int _game_team = default(int);
    public int game_team
    {
      get { return _game_team; }
      set { _game_team = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CHeroSelectEvent : global::ProtoBuf.IExtensible
  {
    public CHeroSelectEvent() {}
    

    private bool _is_pick = default(bool);
    public bool is_pick
    {
      get { return _is_pick; }
      set { _is_pick = value; }
    }

    private uint _team = default(uint);
    public uint team
    {
      get { return _team; }
      set { _team = value; }
    }

    private uint _hero_id = default(uint);
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDemoFileInfo : global::ProtoBuf.IExtensible
  {
    public CDemoFileInfo() {}
    

    private float _playback_time = default(float);
    public float playback_time
    {
      get { return _playback_time; }
      set { _playback_time = value; }
    }

    private int _playback_ticks = default(int);
    public int playback_ticks
    {
      get { return _playback_ticks; }
      set { _playback_ticks = value; }
    }

    private int _playback_frames = default(int);
    public int playback_frames
    {
      get { return _playback_frames; }
      set { _playback_frames = value; }
    }

    private CGameInfo _game_info = null;
    public CGameInfo game_info
    {
      get { return _game_info; }
      set { _game_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDemoPacket : global::ProtoBuf.IExtensible
  {
    public CDemoPacket() {}
    

    private int _sequence_in = default(int);
    public int sequence_in
    {
      get { return _sequence_in; }
      set { _sequence_in = value; }
    }

    private int _sequence_out_ack = default(int);
    public int sequence_out_ack
    {
      get { return _sequence_out_ack; }
      set { _sequence_out_ack = value; }
    }

    private byte[] _data = null;
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDemoFullPacket : global::ProtoBuf.IExtensible
  {
    public CDemoFullPacket() {}
    

    private CDemoStringTables _string_table = null;
    public CDemoStringTables string_table
    {
      get { return _string_table; }
      set { _string_table = value; }
    }

    private CDemoPacket _packet = null;
    public CDemoPacket packet
    {
      get { return _packet; }
      set { _packet = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDemoSaveGame : global::ProtoBuf.IExtensible
  {
    public CDemoSaveGame() {}
    

    private byte[] _data = null;
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }

    private ulong _steam_id = default(ulong);
    public ulong steam_id
    {
      get { return _steam_id; }
      set { _steam_id = value; }
    }

    private ulong _signature = default(ulong);
    public ulong signature
    {
      get { return _signature; }
      set { _signature = value; }
    }

    private int _version = default(int);
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDemoSyncTick : global::ProtoBuf.IExtensible
  {
    public CDemoSyncTick() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDemoConsoleCmd : global::ProtoBuf.IExtensible
  {
    public CDemoConsoleCmd() {}
    

    private string _cmdstring = "";
    public string cmdstring
    {
      get { return _cmdstring; }
      set { _cmdstring = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDemoSendTables : global::ProtoBuf.IExtensible
  {
    public CDemoSendTables() {}
    

    private byte[] _data = null;
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDemoClassInfo : global::ProtoBuf.IExtensible
  {
    public CDemoClassInfo() {}
    
    private readonly global::System.Collections.Generic.List<CDemoClassInfo.class_t> _classes = new global::System.Collections.Generic.List<CDemoClassInfo.class_t>();
    public global::System.Collections.Generic.List<CDemoClassInfo.class_t> classes
    {
      get { return _classes; }
    }
  
  public partial class class_t : global::ProtoBuf.IExtensible
  {
    public class_t() {}
    

    private int _class_id = default(int);
    public int class_id
    {
      get { return _class_id; }
      set { _class_id = value; }
    }

    private string _network_name = "";
    public string network_name
    {
      get { return _network_name; }
      set { _network_name = value; }
    }

    private string _table_name = "";
    public string table_name
    {
      get { return _table_name; }
      set { _table_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDemoCustomData : global::ProtoBuf.IExtensible
  {
    public CDemoCustomData() {}
    

    private int _callback_index = default(int);
    public int callback_index
    {
      get { return _callback_index; }
      set { _callback_index = value; }
    }

    private byte[] _data = null;
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDemoCustomDataCallbacks : global::ProtoBuf.IExtensible
  {
    public CDemoCustomDataCallbacks() {}
    
    private readonly global::System.Collections.Generic.List<string> _save_id = new global::System.Collections.Generic.List<string>();
    public global::System.Collections.Generic.List<string> save_id
    {
      get { return _save_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDemoStringTables : global::ProtoBuf.IExtensible
  {
    public CDemoStringTables() {}
    
    private readonly global::System.Collections.Generic.List<CDemoStringTables.table_t> _tables = new global::System.Collections.Generic.List<CDemoStringTables.table_t>();
    public global::System.Collections.Generic.List<CDemoStringTables.table_t> tables
    {
      get { return _tables; }
    }
  
  public partial class items_t : global::ProtoBuf.IExtensible
  {
    public items_t() {}
    

    private string _str = "";
    public string str
    {
      get { return _str; }
      set { _str = value; }
    }

    private byte[] _data = null;
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class table_t : global::ProtoBuf.IExtensible
  {
    public table_t() {}
    

    private string _table_name = "";
    public string table_name
    {
      get { return _table_name; }
      set { _table_name = value; }
    }
    private readonly global::System.Collections.Generic.List<CDemoStringTables.items_t> _items = new global::System.Collections.Generic.List<CDemoStringTables.items_t>();
    public global::System.Collections.Generic.List<CDemoStringTables.items_t> items
    {
      get { return _items; }
    }
  
    private readonly global::System.Collections.Generic.List<CDemoStringTables.items_t> _items_clientside = new global::System.Collections.Generic.List<CDemoStringTables.items_t>();
    public global::System.Collections.Generic.List<CDemoStringTables.items_t> items_clientside
    {
      get { return _items_clientside; }
    }
  

    private int _table_flags = default(int);
    public int table_flags
    {
      get { return _table_flags; }
      set { _table_flags = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDemoStop : global::ProtoBuf.IExtensible
  {
    public CDemoStop() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDemoUserCmd : global::ProtoBuf.IExtensible
  {
    public CDemoUserCmd() {}
    

    private int _cmd_number = default(int);
    public int cmd_number
    {
      get { return _cmd_number; }
      set { _cmd_number = value; }
    }

    private byte[] _data = null;
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public enum EDemoCommands
    {
            
      DEM_Error = -1,
            
      DEM_Stop = 0,
            
      DEM_FileHeader = 1,
            
      DEM_FileInfo = 2,
            
      DEM_SyncTick = 3,
            
      DEM_SendTables = 4,
            
      DEM_ClassInfo = 5,
            
      DEM_StringTables = 6,
            
      DEM_Packet = 7,
            
      DEM_SignonPacket = 8,
            
      DEM_ConsoleCmd = 9,
            
      DEM_CustomData = 10,
            
      DEM_CustomDataCallbacks = 11,
            
      DEM_UserCmd = 12,
            
      DEM_FullPacket = 13,
            
      DEM_SaveGame = 14,
            
      DEM_Max = 15,
            
      DEM_IsCompressed = 112
    }
  
}
#pragma warning restore 1591
