//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: dota_modifiers.proto
// Note: requires additional types generated from: google/protobuf/descriptor.proto
// Note: requires additional types generated from: networkbasetypes.proto
namespace nora.protos
{
  public partial class CDOTAModifierBuffTableEntry : global::ProtoBuf.IExtensible
  {
    public CDOTAModifierBuffTableEntry() {}
    
    private DOTA_MODIFIER_ENTRY_TYPE _entry_type;
    public DOTA_MODIFIER_ENTRY_TYPE entry_type
    {
      get { return _entry_type; }
      set { _entry_type = value; }
    }
    private int _parent;
    public int parent
    {
      get { return _parent; }
      set { _parent = value; }
    }
    private int _index;
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _serial_num;
    public int serial_num
    {
      get { return _serial_num; }
      set { _serial_num = value; }
    }

    private int _modifier_class = default(int);
    public int modifier_class
    {
      get { return _modifier_class; }
      set { _modifier_class = value; }
    }

    private int _ability_level = default(int);
    public int ability_level
    {
      get { return _ability_level; }
      set { _ability_level = value; }
    }

    private int _stack_count = default(int);
    public int stack_count
    {
      get { return _stack_count; }
      set { _stack_count = value; }
    }

    private float _creation_time = default(float);
    public float creation_time
    {
      get { return _creation_time; }
      set { _creation_time = value; }
    }

    private float _duration = (float)-1;
    public float duration
    {
      get { return _duration; }
      set { _duration = value; }
    }

    private int _caster = default(int);
    public int caster
    {
      get { return _caster; }
      set { _caster = value; }
    }

    private int _ability = default(int);
    public int ability
    {
      get { return _ability; }
      set { _ability = value; }
    }

    private int _armor = default(int);
    public int armor
    {
      get { return _armor; }
      set { _armor = value; }
    }

    private float _fade_time = default(float);
    public float fade_time
    {
      get { return _fade_time; }
      set { _fade_time = value; }
    }

    private bool _subtle = default(bool);
    public bool subtle
    {
      get { return _subtle; }
      set { _subtle = value; }
    }

    private float _channel_time = default(float);
    public float channel_time
    {
      get { return _channel_time; }
      set { _channel_time = value; }
    }

    private CMsgVector _v_start = null;
    public CMsgVector v_start
    {
      get { return _v_start; }
      set { _v_start = value; }
    }

    private CMsgVector _v_end = null;
    public CMsgVector v_end
    {
      get { return _v_end; }
      set { _v_end = value; }
    }

    private string _portal_loop_appear = "";
    public string portal_loop_appear
    {
      get { return _portal_loop_appear; }
      set { _portal_loop_appear = value; }
    }

    private string _portal_loop_disappear = "";
    public string portal_loop_disappear
    {
      get { return _portal_loop_disappear; }
      set { _portal_loop_disappear = value; }
    }

    private string _hero_loop_appear = "";
    public string hero_loop_appear
    {
      get { return _hero_loop_appear; }
      set { _hero_loop_appear = value; }
    }

    private string _hero_loop_disappear = "";
    public string hero_loop_disappear
    {
      get { return _hero_loop_disappear; }
      set { _hero_loop_disappear = value; }
    }

    private int _movement_speed = default(int);
    public int movement_speed
    {
      get { return _movement_speed; }
      set { _movement_speed = value; }
    }

    private bool _aura = default(bool);
    public bool aura
    {
      get { return _aura; }
      set { _aura = value; }
    }

    private int _activity = default(int);
    public int activity
    {
      get { return _activity; }
      set { _activity = value; }
    }

    private int _damage = default(int);
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }

    private int _range = default(int);
    public int range
    {
      get { return _range; }
      set { _range = value; }
    }

    private int _dd_modifier_index = default(int);
    public int dd_modifier_index
    {
      get { return _dd_modifier_index; }
      set { _dd_modifier_index = value; }
    }

    private int _dd_ability_index = default(int);
    public int dd_ability_index
    {
      get { return _dd_ability_index; }
      set { _dd_ability_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public enum DOTA_MODIFIER_ENTRY_TYPE
    {
            
      DOTA_MODIFIER_ENTRY_TYPE_ACTIVE = 1,
            
      DOTA_MODIFIER_ENTRY_TYPE_REMOVED = 2
    }
  
}
#pragma warning restore 1591
