//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: dota_commonmessages.proto
// Note: requires additional types generated from: google/protobuf/descriptor.proto
// Note: requires additional types generated from: networkbasetypes.proto
namespace nora.protos
{
  public partial class CDOTAMsg_LocationPing : global::ProtoBuf.IExtensible
  {
    public CDOTAMsg_LocationPing() {}
    

    private int _x = default(int);
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }

    private int _y = default(int);
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }

    private int _target = default(int);
    public int target
    {
      get { return _target; }
      set { _target = value; }
    }

    private bool _direct_ping = default(bool);
    public bool direct_ping
    {
      get { return _direct_ping; }
      set { _direct_ping = value; }
    }

    private int _type = default(int);
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAMsg_ItemAlert : global::ProtoBuf.IExtensible
  {
    public CDOTAMsg_ItemAlert() {}
    

    private int _x = default(int);
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }

    private int _y = default(int);
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }

    private int _itemid = default(int);
    public int itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAMsg_MapLine : global::ProtoBuf.IExtensible
  {
    public CDOTAMsg_MapLine() {}
    

    private int _x = default(int);
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }

    private int _y = default(int);
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }

    private bool _initial = default(bool);
    public bool initial
    {
      get { return _initial; }
      set { _initial = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAMsg_WorldLine : global::ProtoBuf.IExtensible
  {
    public CDOTAMsg_WorldLine() {}
    

    private int _x = default(int);
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }

    private int _y = default(int);
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }

    private int _z = default(int);
    public int z
    {
      get { return _z; }
      set { _z = value; }
    }

    private bool _initial = default(bool);
    public bool initial
    {
      get { return _initial; }
      set { _initial = value; }
    }

    private bool _end = default(bool);
    public bool end
    {
      get { return _end; }
      set { _end = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAMsg_SendStatPopup : global::ProtoBuf.IExtensible
  {
    public CDOTAMsg_SendStatPopup() {}
    

    private EDOTAStatPopupTypes _style = EDOTAStatPopupTypes.k_EDOTA_SPT_Textline;
    public EDOTAStatPopupTypes style
    {
      get { return _style; }
      set { _style = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _stat_strings = new global::System.Collections.Generic.List<string>();
    public global::System.Collections.Generic.List<string> stat_strings
    {
      get { return _stat_strings; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _stat_images = new global::System.Collections.Generic.List<int>();
    public global::System.Collections.Generic.List<int> stat_images
    {
      get { return _stat_images; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAMsg_CoachHUDPing : global::ProtoBuf.IExtensible
  {
    public CDOTAMsg_CoachHUDPing() {}
    

    private uint _x = default(uint);
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }

    private uint _y = default(uint);
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }

    private string _tgtpath = "";
    public string tgtpath
    {
      get { return _tgtpath; }
      set { _tgtpath = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public enum EDOTAChatWheelMessage
    {
            
      k_EDOTA_CW_Ok = 0,
            
      k_EDOTA_CW_Care = 1,
            
      k_EDOTA_CW_GetBack = 2,
            
      k_EDOTA_CW_NeedWards = 3,
            
      k_EDOTA_CW_Stun = 4,
            
      k_EDOTA_CW_Help = 5,
            
      k_EDOTA_CW_Push = 6,
            
      k_EDOTA_CW_GoodJob = 7,
            
      k_EDOTA_CW_Missing = 8,
            
      k_EDOTA_CW_Missing_Top = 9,
            
      k_EDOTA_CW_Missing_Mid = 10,
            
      k_EDOTA_CW_Missing_Bottom = 11,
            
      k_EDOTA_CW_Go = 12,
            
      k_EDOTA_CW_Initiate = 13,
            
      k_EDOTA_CW_Follow = 14,
            
      k_EDOTA_CW_Group_Up = 15,
            
      k_EDOTA_CW_Spread_Out = 16,
            
      k_EDOTA_CW_Split_Farm = 17,
            
      k_EDOTA_CW_Attack = 18,
            
      k_EDOTA_CW_BRB = 19,
            
      k_EDOTA_CW_Dive = 20,
            
      k_EDOTA_CW_OMW = 21,
            
      k_EDOTA_CW_Get_Ready = 22,
            
      k_EDOTA_CW_Bait = 23,
            
      k_EDOTA_CW_Heal = 24,
            
      k_EDOTA_CW_Mana = 25,
            
      k_EDOTA_CW_OOM = 26,
            
      k_EDOTA_CW_Skill_Cooldown = 27,
            
      k_EDOTA_CW_Ulti_Ready = 28,
            
      k_EDOTA_CW_Enemy_Returned = 29,
            
      k_EDOTA_CW_All_Missing = 30,
            
      k_EDOTA_CW_Enemy_Incoming = 31,
            
      k_EDOTA_CW_Invis_Enemy = 32,
            
      k_EDOTA_CW_Enemy_Had_Rune = 33,
            
      k_EDOTA_CW_Split_Push = 34,
            
      k_EDOTA_CW_Coming_To_Gank = 35,
            
      k_EDOTA_CW_Request_Gank = 36,
            
      k_EDOTA_CW_Fight_Under_Tower = 37,
            
      k_EDOTA_CW_Deny_Tower = 38,
            
      k_EDOTA_CW_Buy_Courier = 39,
            
      k_EDOTA_CW_Upgrade_Courier = 40,
            
      k_EDOTA_CW_Need_Detection = 41,
            
      k_EDOTA_CW_They_Have_Detection = 42,
            
      k_EDOTA_CW_Buy_TP = 43,
            
      k_EDOTA_CW_Reuse_Courier = 44,
            
      k_EDOTA_CW_Deward = 45,
            
      k_EDOTA_CW_Building_Mek = 46,
            
      k_EDOTA_CW_Building_Pipe = 47,
            
      k_EDOTA_CW_Stack_And_Pull = 48,
            
      k_EDOTA_CW_Pull = 49,
            
      k_EDOTA_CW_Pulling = 50,
            
      k_EDOTA_CW_Stack = 51,
            
      k_EDOTA_CW_Jungling = 52,
            
      k_EDOTA_CW_Roshan = 53,
            
      k_EDOTA_CW_Affirmative = 54,
            
      k_EDOTA_CW_Wait = 55,
            
      k_EDOTA_CW_Pause = 56,
            
      k_EDOTA_CW_Current_Time = 57,
            
      k_EDOTA_CW_Check_Runes = 58,
            
      k_EDOTA_CW_Smoke_Gank = 59,
            
      k_EDOTA_CW_GLHF = 60,
            
      k_EDOTA_CW_Nice = 61,
            
      k_EDOTA_CW_Thanks = 62,
            
      k_EDOTA_CW_Sorry = 63,
            
      k_EDOTA_CW_No_Give_Up = 64,
            
      k_EDOTA_CW_Just_Happened = 65,
            
      k_EDOTA_CW_Game_Is_Hard = 66,
            
      k_EDOTA_CW_New_Meta = 67,
            
      k_EDOTA_CW_My_Bad = 68,
            
      k_EDOTA_CW_Regret = 69,
            
      k_EDOTA_CW_Relax = 70,
            
      k_EDOTA_CW_MissingHero = 71,
            
      k_EDOTA_CW_ReturnedHero = 72
    }
  
    public enum EDOTAStatPopupTypes
    {
            
      k_EDOTA_SPT_Textline = 0,
            
      k_EDOTA_SPT_Basic = 1,
            
      k_EDOTA_SPT_Poll = 2
    }
  
}
#pragma warning restore 1591
