//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: dota_gcmessages_server.proto
// Note: requires additional types generated from: steammessages.proto
// Note: requires additional types generated from: matchmaker_common.proto
// Note: requires additional types generated from: dota_gcmessages_common.proto
// Note: requires additional types generated from: econ_gcmessages.proto
// Note: requires additional types generated from: network_connection.proto
namespace nora.protos
{
  public partial class CMsgSpawnLootGreevil : global::ProtoBuf.IExtensible
  {
    public CMsgSpawnLootGreevil() {}
    

    private bool _rare = default(bool);
    public bool rare
    {
      get { return _rare; }
      set { _rare = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDismissLootGreevil : global::ProtoBuf.IExtensible
  {
    public CMsgDismissLootGreevil() {}
    

    private bool _killed = default(bool);
    public bool killed
    {
      get { return _killed; }
      set { _killed = value; }
    }

    private bool _rare = default(bool);
    public bool rare
    {
      get { return _rare; }
      set { _rare = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDismissLootGreevilResponse : global::ProtoBuf.IExtensible
  {
    public CMsgDismissLootGreevilResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgConnectedPlayers : global::ProtoBuf.IExtensible
  {
    public CMsgConnectedPlayers() {}
    
    private readonly global::System.Collections.Generic.List<CMsgConnectedPlayers.Player> _connected_players = new global::System.Collections.Generic.List<CMsgConnectedPlayers.Player>();
    public global::System.Collections.Generic.List<CMsgConnectedPlayers.Player> connected_players
    {
      get { return _connected_players; }
    }
  
    private readonly global::System.Collections.Generic.List<CMsgConnectedPlayers.Player> _disconnected_players = new global::System.Collections.Generic.List<CMsgConnectedPlayers.Player>();
    public global::System.Collections.Generic.List<CMsgConnectedPlayers.Player> disconnected_players
    {
      get { return _disconnected_players; }
    }
  

    private DOTA_GameState _game_state = DOTA_GameState.DOTA_GAMERULES_STATE_INIT;
    public DOTA_GameState game_state
    {
      get { return _game_state; }
      set { _game_state = value; }
    }

    private uint _tower_state = default(uint);
    public uint tower_state
    {
      get { return _tower_state; }
      set { _tower_state = value; }
    }

    private bool _first_blood_happened = default(bool);
    public bool first_blood_happened
    {
      get { return _first_blood_happened; }
      set { _first_blood_happened = value; }
    }

    private CMsgConnectedPlayers.SendReason _send_reason = CMsgConnectedPlayers.SendReason.INVALID;
    public CMsgConnectedPlayers.SendReason send_reason
    {
      get { return _send_reason; }
      set { _send_reason = value; }
    }
  public partial class Player : global::ProtoBuf.IExtensible
  {
    public Player() {}
    

    private ulong _steam_id = default(ulong);
    public ulong steam_id
    {
      get { return _steam_id; }
      set { _steam_id = value; }
    }

    private uint _hero_id = default(uint);
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }

    private CMsgLeaverState _leaver_state = null;
    public CMsgLeaverState leaver_state
    {
      get { return _leaver_state; }
      set { _leaver_state = value; }
    }

    private ENetworkDisconnectionReason _disconnect_reason = ENetworkDisconnectionReason.NETWORK_DISCONNECT_INVALID;
    public ENetworkDisconnectionReason disconnect_reason
    {
      get { return _disconnect_reason; }
      set { _disconnect_reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public enum SendReason
    {
            
      INVALID = 0,
            
      HEARTBEAT = 1,
            
      GAME_STATE = 2,
            
      FIRST_BLOOD = 3,
            
      PLAYER_CONNECTED = 4,
            
      PLAYER_HERO = 5,
            
      PLAYER_DISCONNECTED_CONSEQUENCES = 6,
            
      PLAYER_DISCONNECTED_NOCONSEQUENCES = 7,
            
      TOWER_STATE = 9,
            
      GAMESTATE_TIMEOUT = 10,
            
      MASS_DISCONNECT = 11
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGameServerInfo : global::ProtoBuf.IExtensible
  {
    public CMsgGameServerInfo() {}
    

    private uint _server_public_ip_addr = default(uint);
    public uint server_public_ip_addr
    {
      get { return _server_public_ip_addr; }
      set { _server_public_ip_addr = value; }
    }

    private uint _server_private_ip_addr = default(uint);
    public uint server_private_ip_addr
    {
      get { return _server_private_ip_addr; }
      set { _server_private_ip_addr = value; }
    }

    private uint _server_port = default(uint);
    public uint server_port
    {
      get { return _server_port; }
      set { _server_port = value; }
    }

    private uint _server_tv_port = default(uint);
    public uint server_tv_port
    {
      get { return _server_tv_port; }
      set { _server_tv_port = value; }
    }

    private string _server_key = "";
    public string server_key
    {
      get { return _server_key; }
      set { _server_key = value; }
    }

    private bool _server_hibernation = default(bool);
    public bool server_hibernation
    {
      get { return _server_hibernation; }
      set { _server_hibernation = value; }
    }

    private CMsgGameServerInfo.ServerType _server_type = CMsgGameServerInfo.ServerType.UNSPECIFIED;
    public CMsgGameServerInfo.ServerType server_type
    {
      get { return _server_type; }
      set { _server_type = value; }
    }

    private uint _server_region = default(uint);
    public uint server_region
    {
      get { return _server_region; }
      set { _server_region = value; }
    }

    private float _server_loadavg = default(float);
    public float server_loadavg
    {
      get { return _server_loadavg; }
      set { _server_loadavg = value; }
    }

    private float _server_tv_broadcast_time = default(float);
    public float server_tv_broadcast_time
    {
      get { return _server_tv_broadcast_time; }
      set { _server_tv_broadcast_time = value; }
    }

    private float _server_game_time = default(float);
    public float server_game_time
    {
      get { return _server_game_time; }
      set { _server_game_time = value; }
    }

    private ulong _server_relay_connected_steam_id = default(ulong);
    public ulong server_relay_connected_steam_id
    {
      get { return _server_relay_connected_steam_id; }
      set { _server_relay_connected_steam_id = value; }
    }

    private uint _relay_slots_max = default(uint);
    public uint relay_slots_max
    {
      get { return _relay_slots_max; }
      set { _relay_slots_max = value; }
    }

    private int _relays_connected = default(int);
    public int relays_connected
    {
      get { return _relays_connected; }
      set { _relays_connected = value; }
    }

    private int _relay_clients_connected = default(int);
    public int relay_clients_connected
    {
      get { return _relay_clients_connected; }
      set { _relay_clients_connected = value; }
    }

    private ulong _relayed_game_server_steam_id = default(ulong);
    public ulong relayed_game_server_steam_id
    {
      get { return _relayed_game_server_steam_id; }
      set { _relayed_game_server_steam_id = value; }
    }

    private uint _parent_relay_count = default(uint);
    public uint parent_relay_count
    {
      get { return _parent_relay_count; }
      set { _parent_relay_count = value; }
    }

    private ulong _tv_secret_code = default(ulong);
    public ulong tv_secret_code
    {
      get { return _tv_secret_code; }
      set { _tv_secret_code = value; }
    }

    private uint _server_version = default(uint);
    public uint server_version
    {
      get { return _server_version; }
      set { _server_version = value; }
    }

    private uint _server_cluster = default(uint);
    public uint server_cluster
    {
      get { return _server_cluster; }
      set { _server_cluster = value; }
    }
    public enum ServerType
    {
            
      UNSPECIFIED = 0,
            
      GAME = 1,
            
      PROXY = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgLeaverDetected : global::ProtoBuf.IExtensible
  {
    public CMsgLeaverDetected() {}
    

    private ulong _steam_id = default(ulong);
    public ulong steam_id
    {
      get { return _steam_id; }
      set { _steam_id = value; }
    }

    private DOTALeaverStatus_t _leaver_status = DOTALeaverStatus_t.DOTA_LEAVER_NONE;
    public DOTALeaverStatus_t leaver_status
    {
      get { return _leaver_status; }
      set { _leaver_status = value; }
    }

    private bool _obsolete_mass_disconnect = default(bool);
    public bool obsolete_mass_disconnect
    {
      get { return _obsolete_mass_disconnect; }
      set { _obsolete_mass_disconnect = value; }
    }

    private CMsgLeaverState _leaver_state = null;
    public CMsgLeaverState leaver_state
    {
      get { return _leaver_state; }
      set { _leaver_state = value; }
    }

    private uint _server_cluster = default(uint);
    public uint server_cluster
    {
      get { return _server_cluster; }
      set { _server_cluster = value; }
    }

    private ENetworkDisconnectionReason _disconnect_reason = ENetworkDisconnectionReason.NETWORK_DISCONNECT_INVALID;
    public ENetworkDisconnectionReason disconnect_reason
    {
      get { return _disconnect_reason; }
      set { _disconnect_reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgLeaverDetectedResponse : global::ProtoBuf.IExtensible
  {
    public CMsgLeaverDetectedResponse() {}
    

    private uint _result = default(uint);
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDOTAFantasyPlayerStats : global::ProtoBuf.IExtensible
  {
    public CMsgDOTAFantasyPlayerStats() {}
    

    private uint _player_account_id = default(uint);
    public uint player_account_id
    {
      get { return _player_account_id; }
      set { _player_account_id = value; }
    }

    private uint _match_id = default(uint);
    public uint match_id
    {
      get { return _match_id; }
      set { _match_id = value; }
    }

    private bool _match_completed = default(bool);
    public bool match_completed
    {
      get { return _match_completed; }
      set { _match_completed = value; }
    }

    private uint _level = default(uint);
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }

    private uint _kills = default(uint);
    public uint kills
    {
      get { return _kills; }
      set { _kills = value; }
    }

    private uint _deaths = default(uint);
    public uint deaths
    {
      get { return _deaths; }
      set { _deaths = value; }
    }

    private uint _assists = default(uint);
    public uint assists
    {
      get { return _assists; }
      set { _assists = value; }
    }

    private uint _last_hits = default(uint);
    public uint last_hits
    {
      get { return _last_hits; }
      set { _last_hits = value; }
    }

    private uint _denies = default(uint);
    public uint denies
    {
      get { return _denies; }
      set { _denies = value; }
    }

    private float _gpm = default(float);
    public float gpm
    {
      get { return _gpm; }
      set { _gpm = value; }
    }

    private float _xppm = default(float);
    public float xppm
    {
      get { return _xppm; }
      set { _xppm = value; }
    }

    private float _stuns = default(float);
    public float stuns
    {
      get { return _stuns; }
      set { _stuns = value; }
    }

    private float _healing = default(float);
    public float healing
    {
      get { return _healing; }
      set { _healing = value; }
    }

    private uint _tower_kills = default(uint);
    public uint tower_kills
    {
      get { return _tower_kills; }
      set { _tower_kills = value; }
    }

    private uint _roshan_kills = default(uint);
    public uint roshan_kills
    {
      get { return _roshan_kills; }
      set { _roshan_kills = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGameMatchSignOut : global::ProtoBuf.IExtensible
  {
    public CMsgGameMatchSignOut() {}
    

    private uint _match_id = default(uint);
    public uint match_id
    {
      get { return _match_id; }
      set { _match_id = value; }
    }

    private uint _duration = default(uint);
    public uint duration
    {
      get { return _duration; }
      set { _duration = value; }
    }

    private bool _good_guys_win = default(bool);
    public bool good_guys_win
    {
      get { return _good_guys_win; }
      set { _good_guys_win = value; }
    }

    private uint _date = default(uint);
    public uint date
    {
      get { return _date; }
      set { _date = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _num_players = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> num_players
    {
      get { return _num_players; }
    }
  
    private readonly global::System.Collections.Generic.List<CMsgGameMatchSignOut.CTeam> _teams = new global::System.Collections.Generic.List<CMsgGameMatchSignOut.CTeam>();
    public global::System.Collections.Generic.List<CMsgGameMatchSignOut.CTeam> teams
    {
      get { return _teams; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _tower_status = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> tower_status
    {
      get { return _tower_status; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _barracks_status = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> barracks_status
    {
      get { return _barracks_status; }
    }
  

    private uint _cluster = default(uint);
    public uint cluster
    {
      get { return _cluster; }
      set { _cluster = value; }
    }

    private string _server_addr = "";
    public string server_addr
    {
      get { return _server_addr; }
      set { _server_addr = value; }
    }

    private uint _first_blood_time = default(uint);
    public uint first_blood_time
    {
      get { return _first_blood_time; }
      set { _first_blood_time = value; }
    }

    private float _game_balance = default(float);
    public float game_balance
    {
      get { return _game_balance; }
      set { _game_balance = value; }
    }

    private uint _event_score = default(uint);
    public uint event_score
    {
      get { return _event_score; }
      set { _event_score = value; }
    }
    private readonly global::System.Collections.Generic.List<CMatchHeroSelectEvent> _picks_bans = new global::System.Collections.Generic.List<CMatchHeroSelectEvent>();
    public global::System.Collections.Generic.List<CMatchHeroSelectEvent> picks_bans
    {
      get { return _picks_bans; }
    }
  
    private readonly global::System.Collections.Generic.List<CMsgDOTAFantasyPlayerStats> _fantasy_stats = new global::System.Collections.Generic.List<CMsgDOTAFantasyPlayerStats>();
    public global::System.Collections.Generic.List<CMsgDOTAFantasyPlayerStats> fantasy_stats
    {
      get { return _fantasy_stats; }
    }
  
    private readonly global::System.Collections.Generic.List<CMsgEconPlayerStrangeCountAdjustment> _player_strange_count_adjustments = new global::System.Collections.Generic.List<CMsgEconPlayerStrangeCountAdjustment>();
    public global::System.Collections.Generic.List<CMsgEconPlayerStrangeCountAdjustment> player_strange_count_adjustments
    {
      get { return _player_strange_count_adjustments; }
    }
  

    private bool _automatic_surrender = default(bool);
    public bool automatic_surrender
    {
      get { return _automatic_surrender; }
      set { _automatic_surrender = value; }
    }

    private uint _server_version = default(uint);
    public uint server_version
    {
      get { return _server_version; }
      set { _server_version = value; }
    }

    private bool _mass_disconnect = default(bool);
    public bool mass_disconnect
    {
      get { return _mass_disconnect; }
      set { _mass_disconnect = value; }
    }
    private readonly global::System.Collections.Generic.List<CMsgGameMatchSignOut.CAdditionalSignoutMsg> _additional_msgs = new global::System.Collections.Generic.List<CMsgGameMatchSignOut.CAdditionalSignoutMsg>();
    public global::System.Collections.Generic.List<CMsgGameMatchSignOut.CAdditionalSignoutMsg> additional_msgs
    {
      get { return _additional_msgs; }
    }
  
  public partial class CTeam : global::ProtoBuf.IExtensible
  {
    public CTeam() {}
    
    private readonly global::System.Collections.Generic.List<CMsgGameMatchSignOut.CTeam.CPlayer> _players = new global::System.Collections.Generic.List<CMsgGameMatchSignOut.CTeam.CPlayer>();
    public global::System.Collections.Generic.List<CMsgGameMatchSignOut.CTeam.CPlayer> players
    {
      get { return _players; }
    }
  
  public partial class CPlayer : global::ProtoBuf.IExtensible
  {
    public CPlayer() {}
    

    private ulong _account_id = default(ulong);
    public ulong account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _hero_id = default(uint);
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _items = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> items
    {
      get { return _items; }
    }
  

    private uint _gold = default(uint);
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }

    private uint _kills = default(uint);
    public uint kills
    {
      get { return _kills; }
      set { _kills = value; }
    }

    private uint _deaths = default(uint);
    public uint deaths
    {
      get { return _deaths; }
      set { _deaths = value; }
    }

    private uint _assists = default(uint);
    public uint assists
    {
      get { return _assists; }
      set { _assists = value; }
    }

    private uint _leaver_status = default(uint);
    public uint leaver_status
    {
      get { return _leaver_status; }
      set { _leaver_status = value; }
    }

    private uint _last_hits = default(uint);
    public uint last_hits
    {
      get { return _last_hits; }
      set { _last_hits = value; }
    }

    private uint _denies = default(uint);
    public uint denies
    {
      get { return _denies; }
      set { _denies = value; }
    }

    private uint _gold_per_min = default(uint);
    public uint gold_per_min
    {
      get { return _gold_per_min; }
      set { _gold_per_min = value; }
    }

    private uint _xp_per_minute = default(uint);
    public uint xp_per_minute
    {
      get { return _xp_per_minute; }
      set { _xp_per_minute = value; }
    }

    private uint _gold_spent = default(uint);
    public uint gold_spent
    {
      get { return _gold_spent; }
      set { _gold_spent = value; }
    }

    private uint _level = default(uint);
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }

    private uint _hero_damage = default(uint);
    public uint hero_damage
    {
      get { return _hero_damage; }
      set { _hero_damage = value; }
    }

    private uint _tower_damage = default(uint);
    public uint tower_damage
    {
      get { return _tower_damage; }
      set { _tower_damage = value; }
    }

    private uint _hero_healing = default(uint);
    public uint hero_healing
    {
      get { return _hero_healing; }
      set { _hero_healing = value; }
    }

    private uint _time_last_seen = default(uint);
    public uint time_last_seen
    {
      get { return _time_last_seen; }
      set { _time_last_seen = value; }
    }

    private uint _support_ability_value = default(uint);
    public uint support_ability_value
    {
      get { return _support_ability_value; }
      set { _support_ability_value = value; }
    }

    private ulong _party_id = default(ulong);
    public ulong party_id
    {
      get { return _party_id; }
      set { _party_id = value; }
    }

    private float _scaled_kills = default(float);
    public float scaled_kills
    {
      get { return _scaled_kills; }
      set { _scaled_kills = value; }
    }

    private float _scaled_deaths = default(float);
    public float scaled_deaths
    {
      get { return _scaled_deaths; }
      set { _scaled_deaths = value; }
    }

    private float _scaled_assists = default(float);
    public float scaled_assists
    {
      get { return _scaled_assists; }
      set { _scaled_assists = value; }
    }

    private uint _claimed_farm_gold = default(uint);
    public uint claimed_farm_gold
    {
      get { return _claimed_farm_gold; }
      set { _claimed_farm_gold = value; }
    }

    private uint _support_gold = default(uint);
    public uint support_gold
    {
      get { return _support_gold; }
      set { _support_gold = value; }
    }

    private uint _claimed_denies = default(uint);
    public uint claimed_denies
    {
      get { return _claimed_denies; }
      set { _claimed_denies = value; }
    }

    private uint _claimed_misses = default(uint);
    public uint claimed_misses
    {
      get { return _claimed_misses; }
      set { _claimed_misses = value; }
    }

    private uint _misses = default(uint);
    public uint misses
    {
      get { return _misses; }
      set { _misses = value; }
    }
    private readonly global::System.Collections.Generic.List<CMatchPlayerAbilityUpgrade> _ability_upgrades = new global::System.Collections.Generic.List<CMatchPlayerAbilityUpgrade>();
    public global::System.Collections.Generic.List<CMatchPlayerAbilityUpgrade> ability_upgrades
    {
      get { return _ability_upgrades; }
    }
  
    private readonly global::System.Collections.Generic.List<CMatchAdditionalUnitInventory> _additional_units_inventory = new global::System.Collections.Generic.List<CMatchAdditionalUnitInventory>();
    public global::System.Collections.Generic.List<CMatchAdditionalUnitInventory> additional_units_inventory
    {
      get { return _additional_units_inventory; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CAdditionalSignoutMsg : global::ProtoBuf.IExtensible
  {
    public CAdditionalSignoutMsg() {}
    

    private uint _id = default(uint);
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private byte[] _contents = null;
    public byte[] contents
    {
      get { return _contents; }
      set { _contents = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgSignOutDraftInfo : global::ProtoBuf.IExtensible
  {
    public CMsgSignOutDraftInfo() {}
    

    private uint _radiant_captain_account_id = default(uint);
    public uint radiant_captain_account_id
    {
      get { return _radiant_captain_account_id; }
      set { _radiant_captain_account_id = value; }
    }

    private uint _dire_captain_account_id = default(uint);
    public uint dire_captain_account_id
    {
      get { return _dire_captain_account_id; }
      set { _dire_captain_account_id = value; }
    }
    private readonly global::System.Collections.Generic.List<CMatchHeroSelectEvent> _picks_bans = new global::System.Collections.Generic.List<CMatchHeroSelectEvent>();
    public global::System.Collections.Generic.List<CMatchHeroSelectEvent> picks_bans
    {
      get { return _picks_bans; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGameMatchSignoutResponse : global::ProtoBuf.IExtensible
  {
    public CMsgGameMatchSignoutResponse() {}
    

    private uint _match_id = default(uint);
    public uint match_id
    {
      get { return _match_id; }
      set { _match_id = value; }
    }

    private uint _replay_salt = default(uint);
    public uint replay_salt
    {
      get { return _replay_salt; }
      set { _replay_salt = value; }
    }
    private readonly global::System.Collections.Generic.List<CLobbyTimedRewardDetails> _timed_reward_details = new global::System.Collections.Generic.List<CLobbyTimedRewardDetails>();
    public global::System.Collections.Generic.List<CLobbyTimedRewardDetails> timed_reward_details
    {
      get { return _timed_reward_details; }
    }
  
    private readonly global::System.Collections.Generic.List<CDOTALobbyMember> _xp_reward_details = new global::System.Collections.Generic.List<CDOTALobbyMember>();
    public global::System.Collections.Generic.List<CDOTALobbyMember> xp_reward_details
    {
      get { return _xp_reward_details; }
    }
  

    private uint _leagueid = default(uint);
    public uint leagueid
    {
      get { return _leagueid; }
      set { _leagueid = value; }
    }
    private readonly global::System.Collections.Generic.List<CMsgGameMatchSignoutResponse.CAdditionalSignoutMsg> _additional_msgs = new global::System.Collections.Generic.List<CMsgGameMatchSignoutResponse.CAdditionalSignoutMsg>();
    public global::System.Collections.Generic.List<CMsgGameMatchSignoutResponse.CAdditionalSignoutMsg> additional_msgs
    {
      get { return _additional_msgs; }
    }
  
  public partial class CAdditionalSignoutMsg : global::ProtoBuf.IExtensible
  {
    public CAdditionalSignoutMsg() {}
    

    private uint _id = default(uint);
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private byte[] _contents = null;
    public byte[] contents
    {
      get { return _contents; }
      set { _contents = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGameMatchSignOutPermissionRequest : global::ProtoBuf.IExtensible
  {
    public CMsgGameMatchSignOutPermissionRequest() {}
    

    private uint _server_version = default(uint);
    public uint server_version
    {
      get { return _server_version; }
      set { _server_version = value; }
    }

    private uint _local_attempt = default(uint);
    public uint local_attempt
    {
      get { return _local_attempt; }
      set { _local_attempt = value; }
    }

    private uint _total_attempt = default(uint);
    public uint total_attempt
    {
      get { return _total_attempt; }
      set { _total_attempt = value; }
    }

    private uint _seconds_waited = default(uint);
    public uint seconds_waited
    {
      get { return _seconds_waited; }
      set { _seconds_waited = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGameMatchSignOutPermissionResponse : global::ProtoBuf.IExtensible
  {
    public CMsgGameMatchSignOutPermissionResponse() {}
    

    private bool _permission_granted = (bool)false;
    public bool permission_granted
    {
      get { return _permission_granted; }
      set { _permission_granted = value; }
    }

    private bool _abandon_signout = (bool)false;
    public bool abandon_signout
    {
      get { return _abandon_signout; }
      set { _abandon_signout = value; }
    }

    private uint _retry_delay_seconds = (uint)0;
    public uint retry_delay_seconds
    {
      get { return _retry_delay_seconds; }
      set { _retry_delay_seconds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGameChatLog : global::ProtoBuf.IExtensible
  {
    public CMsgGameChatLog() {}
    

    private uint _match_id = default(uint);
    public uint match_id
    {
      get { return _match_id; }
      set { _match_id = value; }
    }
    private readonly global::System.Collections.Generic.List<CMsgGameChatLog.CChatLine> _lines = new global::System.Collections.Generic.List<CMsgGameChatLog.CChatLine>();
    public global::System.Collections.Generic.List<CMsgGameChatLog.CChatLine> lines
    {
      get { return _lines; }
    }
  
  public partial class CChatLine : global::ProtoBuf.IExtensible
  {
    public CChatLine() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _team_only = default(uint);
    public uint team_only
    {
      get { return _team_only; }
      set { _team_only = value; }
    }

    private string _text = "";
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }

    private uint _game_time = default(uint);
    public uint game_time
    {
      get { return _game_time; }
      set { _game_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDOTALiveScoreboardUpdate : global::ProtoBuf.IExtensible
  {
    public CMsgDOTALiveScoreboardUpdate() {}
    

    private uint _tournament_id = default(uint);
    public uint tournament_id
    {
      get { return _tournament_id; }
      set { _tournament_id = value; }
    }

    private uint _tournament_game_id = default(uint);
    public uint tournament_game_id
    {
      get { return _tournament_game_id; }
      set { _tournament_game_id = value; }
    }

    private float _duration = default(float);
    public float duration
    {
      get { return _duration; }
      set { _duration = value; }
    }

    private int _hltv_delay = default(int);
    public int hltv_delay
    {
      get { return _hltv_delay; }
      set { _hltv_delay = value; }
    }

    private CMsgDOTALiveScoreboardUpdate.Team _team_good = null;
    public CMsgDOTALiveScoreboardUpdate.Team team_good
    {
      get { return _team_good; }
      set { _team_good = value; }
    }

    private CMsgDOTALiveScoreboardUpdate.Team _team_bad = null;
    public CMsgDOTALiveScoreboardUpdate.Team team_bad
    {
      get { return _team_bad; }
      set { _team_bad = value; }
    }

    private uint _roshan_respawn_timer = default(uint);
    public uint roshan_respawn_timer
    {
      get { return _roshan_respawn_timer; }
      set { _roshan_respawn_timer = value; }
    }

    private uint _league_id = default(uint);
    public uint league_id
    {
      get { return _league_id; }
      set { _league_id = value; }
    }

    private ulong _match_id = default(ulong);
    public ulong match_id
    {
      get { return _match_id; }
      set { _match_id = value; }
    }
  public partial class Team : global::ProtoBuf.IExtensible
  {
    public Team() {}
    
    private readonly global::System.Collections.Generic.List<CMsgDOTALiveScoreboardUpdate.Team.Player> _players = new global::System.Collections.Generic.List<CMsgDOTALiveScoreboardUpdate.Team.Player>();
    public global::System.Collections.Generic.List<CMsgDOTALiveScoreboardUpdate.Team.Player> players
    {
      get { return _players; }
    }
  

    private uint _score = default(uint);
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
  public partial class Player : global::ProtoBuf.IExtensible
  {
    public Player() {}
    

    private uint _player_slot = default(uint);
    public uint player_slot
    {
      get { return _player_slot; }
      set { _player_slot = value; }
    }

    private string _player_name = "";
    public string player_name
    {
      get { return _player_name; }
      set { _player_name = value; }
    }

    private string _hero_name = "";
    public string hero_name
    {
      get { return _hero_name; }
      set { _hero_name = value; }
    }

    private uint _hero_id = default(uint);
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }

    private uint _kills = default(uint);
    public uint kills
    {
      get { return _kills; }
      set { _kills = value; }
    }

    private uint _deaths = default(uint);
    public uint deaths
    {
      get { return _deaths; }
      set { _deaths = value; }
    }

    private uint _assists = default(uint);
    public uint assists
    {
      get { return _assists; }
      set { _assists = value; }
    }

    private uint _last_hits = default(uint);
    public uint last_hits
    {
      get { return _last_hits; }
      set { _last_hits = value; }
    }

    private uint _denies = default(uint);
    public uint denies
    {
      get { return _denies; }
      set { _denies = value; }
    }

    private uint _gold = default(uint);
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }

    private uint _level = default(uint);
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }

    private float _gold_per_min = default(float);
    public float gold_per_min
    {
      get { return _gold_per_min; }
      set { _gold_per_min = value; }
    }

    private float _xp_per_min = default(float);
    public float xp_per_min
    {
      get { return _xp_per_min; }
      set { _xp_per_min = value; }
    }

    private CMsgDOTALiveScoreboardUpdate.Team.Player.DOTAUltimateState _ultimate_state = CMsgDOTALiveScoreboardUpdate.Team.Player.DOTAUltimateState.k_EDOTAUltimateStateNotLearned;
    public CMsgDOTALiveScoreboardUpdate.Team.Player.DOTAUltimateState ultimate_state
    {
      get { return _ultimate_state; }
      set { _ultimate_state = value; }
    }

    private float _ultimate_cooldown = default(float);
    public float ultimate_cooldown
    {
      get { return _ultimate_cooldown; }
      set { _ultimate_cooldown = value; }
    }

    private uint _item0 = default(uint);
    public uint item0
    {
      get { return _item0; }
      set { _item0 = value; }
    }

    private uint _item1 = default(uint);
    public uint item1
    {
      get { return _item1; }
      set { _item1 = value; }
    }

    private uint _item2 = default(uint);
    public uint item2
    {
      get { return _item2; }
      set { _item2 = value; }
    }

    private uint _item3 = default(uint);
    public uint item3
    {
      get { return _item3; }
      set { _item3 = value; }
    }

    private uint _item4 = default(uint);
    public uint item4
    {
      get { return _item4; }
      set { _item4 = value; }
    }

    private uint _item5 = default(uint);
    public uint item5
    {
      get { return _item5; }
      set { _item5 = value; }
    }

    private uint _respawn_timer = default(uint);
    public uint respawn_timer
    {
      get { return _respawn_timer; }
      set { _respawn_timer = value; }
    }

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private float _position_x = default(float);
    public float position_x
    {
      get { return _position_x; }
      set { _position_x = value; }
    }

    private float _position_y = default(float);
    public float position_y
    {
      get { return _position_y; }
      set { _position_y = value; }
    }
    public enum DOTAUltimateState
    {
            
      k_EDOTAUltimateStateNotLearned = 0,
            
      k_EDOTAUltimateStateCooldown = 1,
            
      k_EDOTAUltimateStateNeedsMana = 2,
            
      k_EDOTAUltimateStateReady = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDOTARequestPlayerResources : global::ProtoBuf.IExtensible
  {
    public CMsgDOTARequestPlayerResources() {}
    

    private ulong _steam_id = default(ulong);
    public ulong steam_id
    {
      get { return _steam_id; }
      set { _steam_id = value; }
    }

    private uint _player_id = default(uint);
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDOTARequestPlayerResourcesResponse : global::ProtoBuf.IExtensible
  {
    public CMsgDOTARequestPlayerResourcesResponse() {}
    

    private ulong _steam_id = default(ulong);
    public ulong steam_id
    {
      get { return _steam_id; }
      set { _steam_id = value; }
    }

    private uint _rank = default(uint);
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }

    private uint _player_id = default(uint);
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private bool _prevent_text_chat = default(bool);
    public bool prevent_text_chat
    {
      get { return _prevent_text_chat; }
      set { _prevent_text_chat = value; }
    }

    private bool _prevent_voice_chat = default(bool);
    public bool prevent_voice_chat
    {
      get { return _prevent_voice_chat; }
      set { _prevent_voice_chat = value; }
    }

    private bool _low_priority = default(bool);
    public bool low_priority
    {
      get { return _low_priority; }
      set { _low_priority = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDOTARequestBatchPlayerResources : global::ProtoBuf.IExtensible
  {
    public CMsgDOTARequestBatchPlayerResources() {}
    
    private readonly global::System.Collections.Generic.List<uint> _account_ids = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> account_ids
    {
      get { return _account_ids; }
    }
  

    private bool _legacy_rank_use_competitive = default(bool);
    public bool legacy_rank_use_competitive
    {
      get { return _legacy_rank_use_competitive; }
      set { _legacy_rank_use_competitive = value; }
    }
    private readonly global::System.Collections.Generic.List<bool> _legacy_rank_use_solo = new global::System.Collections.Generic.List<bool>();
    public global::System.Collections.Generic.List<bool> legacy_rank_use_solo
    {
      get { return _legacy_rank_use_solo; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _rank_types = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> rank_types
    {
      get { return _rank_types; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDOTARequestBatchPlayerResourcesResponse : global::ProtoBuf.IExtensible
  {
    public CMsgDOTARequestBatchPlayerResourcesResponse() {}
    
    private readonly global::System.Collections.Generic.List<CMsgDOTARequestBatchPlayerResourcesResponse.Result> _results = new global::System.Collections.Generic.List<CMsgDOTARequestBatchPlayerResourcesResponse.Result>();
    public global::System.Collections.Generic.List<CMsgDOTARequestBatchPlayerResourcesResponse.Result> results
    {
      get { return _results; }
    }
  
  public partial class Result : global::ProtoBuf.IExtensible
  {
    public Result() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private bool _prevent_text_chat = default(bool);
    public bool prevent_text_chat
    {
      get { return _prevent_text_chat; }
      set { _prevent_text_chat = value; }
    }

    private bool _prevent_voice_chat = default(bool);
    public bool prevent_voice_chat
    {
      get { return _prevent_voice_chat; }
      set { _prevent_voice_chat = value; }
    }

    private uint _rank = default(uint);
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }

    private bool _rank_calibrated = default(bool);
    public bool rank_calibrated
    {
      get { return _rank_calibrated; }
      set { _rank_calibrated = value; }
    }

    private bool _low_priority = default(bool);
    public bool low_priority
    {
      get { return _low_priority; }
      set { _low_priority = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDOTAPlayerFailedToConnect : global::ProtoBuf.IExtensible
  {
    public CMsgDOTAPlayerFailedToConnect() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _failed_loaders = new global::System.Collections.Generic.List<ulong>();
    public global::System.Collections.Generic.List<ulong> failed_loaders
    {
      get { return _failed_loaders; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _abandoned_loaders = new global::System.Collections.Generic.List<ulong>();
    public global::System.Collections.Generic.List<ulong> abandoned_loaders
    {
      get { return _abandoned_loaders; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCToRelayConnect : global::ProtoBuf.IExtensible
  {
    public CMsgGCToRelayConnect() {}
    

    private uint _source_tv_public_addr = default(uint);
    public uint source_tv_public_addr
    {
      get { return _source_tv_public_addr; }
      set { _source_tv_public_addr = value; }
    }

    private uint _source_tv_private_addr = default(uint);
    public uint source_tv_private_addr
    {
      get { return _source_tv_private_addr; }
      set { _source_tv_private_addr = value; }
    }

    private uint _source_tv_port = default(uint);
    public uint source_tv_port
    {
      get { return _source_tv_port; }
      set { _source_tv_port = value; }
    }

    private ulong _game_server_steam_id = default(ulong);
    public ulong game_server_steam_id
    {
      get { return _game_server_steam_id; }
      set { _game_server_steam_id = value; }
    }

    private uint _parent_count = default(uint);
    public uint parent_count
    {
      get { return _parent_count; }
      set { _parent_count = value; }
    }

    private ulong _tv_unique_secret_code = default(ulong);
    public ulong tv_unique_secret_code
    {
      get { return _tv_unique_secret_code; }
      set { _tv_unique_secret_code = value; }
    }

    private uint _source_tv_steamid = default(uint);
    public uint source_tv_steamid
    {
      get { return _source_tv_steamid; }
      set { _source_tv_steamid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCToRelayConnectResponse : global::ProtoBuf.IExtensible
  {
    public CMsgGCToRelayConnectResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCBanStatusRequest : global::ProtoBuf.IExtensible
  {
    public CMsgGCBanStatusRequest() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCBanStatusResponse : global::ProtoBuf.IExtensible
  {
    public CMsgGCBanStatusResponse() {}
    

    private uint _result = default(uint);
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private bool _low_priority = default(bool);
    public bool low_priority
    {
      get { return _low_priority; }
      set { _low_priority = value; }
    }

    private bool _text_chat_banned = default(bool);
    public bool text_chat_banned
    {
      get { return _text_chat_banned; }
      set { _text_chat_banned = value; }
    }

    private bool _voice_chat_banned = default(bool);
    public bool voice_chat_banned
    {
      get { return _voice_chat_banned; }
      set { _voice_chat_banned = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgTournamentItemEvent : global::ProtoBuf.IExtensible
  {
    public CMsgTournamentItemEvent() {}
    

    private uint _killer_account_id = default(uint);
    public uint killer_account_id
    {
      get { return _killer_account_id; }
      set { _killer_account_id = value; }
    }

    private uint _victim_account_id = default(uint);
    public uint victim_account_id
    {
      get { return _victim_account_id; }
      set { _victim_account_id = value; }
    }

    private DOTA_TournamentEvents _event_type = DOTA_TournamentEvents.TE_FIRST_BLOOD;
    public DOTA_TournamentEvents event_type
    {
      get { return _event_type; }
      set { _event_type = value; }
    }

    private int _tv_delay = default(int);
    public int tv_delay
    {
      get { return _tv_delay; }
      set { _tv_delay = value; }
    }

    private int _dota_time = default(int);
    public int dota_time
    {
      get { return _dota_time; }
      set { _dota_time = value; }
    }

    private float _replay_time = default(float);
    public float replay_time
    {
      get { return _replay_time; }
      set { _replay_time = value; }
    }

    private string _loot_list = "";
    public string loot_list
    {
      get { return _loot_list; }
      set { _loot_list = value; }
    }

    private uint _event_team = default(uint);
    public uint event_team
    {
      get { return _event_team; }
      set { _event_team = value; }
    }

    private uint _multi_kill_count = default(uint);
    public uint multi_kill_count
    {
      get { return _multi_kill_count; }
      set { _multi_kill_count = value; }
    }

    private uint _winner_score = default(uint);
    public uint winner_score
    {
      get { return _winner_score; }
      set { _winner_score = value; }
    }

    private uint _loser_score = default(uint);
    public uint loser_score
    {
      get { return _loser_score; }
      set { _loser_score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgTournamentItemEventResponse : global::ProtoBuf.IExtensible
  {
    public CMsgTournamentItemEventResponse() {}
    

    private DOTA_TournamentEvents _event_type = DOTA_TournamentEvents.TE_FIRST_BLOOD;
    public DOTA_TournamentEvents event_type
    {
      get { return _event_type; }
      set { _event_type = value; }
    }

    private uint _viewers_granted = default(uint);
    public uint viewers_granted
    {
      get { return _viewers_granted; }
      set { _viewers_granted = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgTeamFanfare : global::ProtoBuf.IExtensible
  {
    public CMsgTeamFanfare() {}
    

    private uint _match_id = default(uint);
    public uint match_id
    {
      get { return _match_id; }
      set { _match_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgResponseTeamFanfare : global::ProtoBuf.IExtensible
  {
    public CMsgResponseTeamFanfare() {}
    

    private uint _fanfare_goodguys = default(uint);
    public uint fanfare_goodguys
    {
      get { return _fanfare_goodguys; }
      set { _fanfare_goodguys = value; }
    }

    private uint _fanfare_badguys = default(uint);
    public uint fanfare_badguys
    {
      get { return _fanfare_badguys; }
      set { _fanfare_badguys = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGameServerUploadSaveGame : global::ProtoBuf.IExtensible
  {
    public CMsgGameServerUploadSaveGame() {}
    

    private uint _game_time = default(uint);
    public uint game_time
    {
      get { return _game_time; }
      set { _game_time = value; }
    }

    private byte[] _save_game_data = null;
    public byte[] save_game_data
    {
      get { return _save_game_data; }
      set { _save_game_data = value; }
    }

    private ulong _lobby_id = default(ulong);
    public ulong lobby_id
    {
      get { return _lobby_id; }
      set { _lobby_id = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _player_steam_ids = new global::System.Collections.Generic.List<ulong>();
    public global::System.Collections.Generic.List<ulong> player_steam_ids
    {
      get { return _player_steam_ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGameServerSaveGameResult : global::ProtoBuf.IExtensible
  {
    public CMsgGameServerSaveGameResult() {}
    

    private CMsgGameServerSaveGameResult.Result _result = CMsgGameServerSaveGameResult.Result.SaveSuccessful;
    public CMsgGameServerSaveGameResult.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    public enum Result
    {
            
      SaveSuccessful = 0,
            
      SessionNotFound = 1,
            
      DatabaseError = 2,
            
      TooBig = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGameServerGetLoadGame : global::ProtoBuf.IExtensible
  {
    public CMsgGameServerGetLoadGame() {}
    

    private uint _save_id = default(uint);
    public uint save_id
    {
      get { return _save_id; }
      set { _save_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGameServerGetLoadGameResult : global::ProtoBuf.IExtensible
  {
    public CMsgGameServerGetLoadGameResult() {}
    

    private byte[] _save_game_data = null;
    public byte[] save_game_data
    {
      get { return _save_game_data; }
      set { _save_game_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDOTAGenerateDiretidePrizeList : global::ProtoBuf.IExtensible
  {
    public CMsgDOTAGenerateDiretidePrizeList() {}
    

    private uint _prize_list = default(uint);
    public uint prize_list
    {
      get { return _prize_list; }
      set { _prize_list = value; }
    }

    private uint _highest_roshan_level = default(uint);
    public uint highest_roshan_level
    {
      get { return _highest_roshan_level; }
      set { _highest_roshan_level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDOTAGenerateDiretidePrizeListResponse : global::ProtoBuf.IExtensible
  {
    public CMsgDOTAGenerateDiretidePrizeListResponse() {}
    
    private readonly global::System.Collections.Generic.List<uint> _item_defs = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> item_defs
    {
      get { return _item_defs; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _steam_ids = new global::System.Collections.Generic.List<ulong>();
    public global::System.Collections.Generic.List<ulong> steam_ids
    {
      get { return _steam_ids; }
    }
  

    private uint _prize_list = default(uint);
    public uint prize_list
    {
      get { return _prize_list; }
      set { _prize_list = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDOTARewardDiretidePrizes : global::ProtoBuf.IExtensible
  {
    public CMsgDOTARewardDiretidePrizes() {}
    

    private uint _team = default(uint);
    public uint team
    {
      get { return _team; }
      set { _team = value; }
    }

    private uint _prize_list = default(uint);
    public uint prize_list
    {
      get { return _prize_list; }
      set { _prize_list = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDOTADiretidePrizesRewardedResponse : global::ProtoBuf.IExtensible
  {
    public CMsgDOTADiretidePrizesRewardedResponse() {}
    

    private uint _prize_list = default(uint);
    public uint prize_list
    {
      get { return _prize_list; }
      set { _prize_list = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDOTAAwardEventPoints : global::ProtoBuf.IExtensible
  {
    public CMsgDOTAAwardEventPoints() {}
    
    private readonly global::System.Collections.Generic.List<CMsgDOTAAwardEventPoints.AwardPoints> _award_points = new global::System.Collections.Generic.List<CMsgDOTAAwardEventPoints.AwardPoints>();
    public global::System.Collections.Generic.List<CMsgDOTAAwardEventPoints.AwardPoints> award_points
    {
      get { return _award_points; }
    }
  

    private ulong _match_id = default(ulong);
    public ulong match_id
    {
      get { return _match_id; }
      set { _match_id = value; }
    }

    private uint _event_id = default(uint);
    public uint event_id
    {
      get { return _event_id; }
      set { _event_id = value; }
    }
  public partial class AwardPoints : global::ProtoBuf.IExtensible
  {
    public AwardPoints() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private int _points = default(int);
    public int points
    {
      get { return _points; }
      set { _points = value; }
    }

    private int _premium_points = default(int);
    public int premium_points
    {
      get { return _premium_points; }
      set { _premium_points = value; }
    }

    private uint _trade_ban_time = default(uint);
    public uint trade_ban_time
    {
      get { return _trade_ban_time; }
      set { _trade_ban_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDOTAUpdateTI4HeroQuest : global::ProtoBuf.IExtensible
  {
    public CMsgDOTAUpdateTI4HeroQuest() {}
    
    private readonly global::System.Collections.Generic.List<CMsgDOTAUpdateTI4HeroQuest.Player> _players = new global::System.Collections.Generic.List<CMsgDOTAUpdateTI4HeroQuest.Player>();
    public global::System.Collections.Generic.List<CMsgDOTAUpdateTI4HeroQuest.Player> players
    {
      get { return _players; }
    }
  

    private uint _match_start_time = default(uint);
    public uint match_start_time
    {
      get { return _match_start_time; }
      set { _match_start_time = value; }
    }

    private ulong _match_id = default(ulong);
    public ulong match_id
    {
      get { return _match_id; }
      set { _match_id = value; }
    }
  public partial class Player : global::ProtoBuf.IExtensible
  {
    public Player() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _hero_id = default(uint);
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgDOTAFrostivusTimeElapsed : global::ProtoBuf.IExtensible
  {
    public CMsgDOTAFrostivusTimeElapsed() {}
    

    private uint _seconds = default(uint);
    public uint seconds
    {
      get { return _seconds; }
      set { _seconds = value; }
    }
    private readonly global::System.Collections.Generic.List<CMsgDOTAFrostivusTimeElapsed.User> _users = new global::System.Collections.Generic.List<CMsgDOTAFrostivusTimeElapsed.User>();
    public global::System.Collections.Generic.List<CMsgDOTAFrostivusTimeElapsed.User> users
    {
      get { return _users; }
    }
  

    private ulong _match_id = default(ulong);
    public ulong match_id
    {
      get { return _match_id; }
      set { _match_id = value; }
    }
  public partial class User : global::ProtoBuf.IExtensible
  {
    public User() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _time_elapsed_s = default(uint);
    public uint time_elapsed_s
    {
      get { return _time_elapsed_s; }
      set { _time_elapsed_s = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCToServerPingRequest : global::ProtoBuf.IExtensible
  {
    public CMsgGCToServerPingRequest() {}
    

    private ulong _request_id = default(ulong);
    public ulong request_id
    {
      get { return _request_id; }
      set { _request_id = value; }
    }

    private ulong _request_time = default(ulong);
    public ulong request_time
    {
      get { return _request_time; }
      set { _request_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCToServerPingResponse : global::ProtoBuf.IExtensible
  {
    public CMsgGCToServerPingResponse() {}
    

    private ulong _request_id = default(ulong);
    public ulong request_id
    {
      get { return _request_id; }
      set { _request_id = value; }
    }

    private ulong _request_time = default(ulong);
    public ulong request_time
    {
      get { return _request_time; }
      set { _request_time = value; }
    }

    private uint _cluster = default(uint);
    public uint cluster
    {
      get { return _cluster; }
      set { _cluster = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgGCToServerConsoleCommand : global::ProtoBuf.IExtensible
  {
    public CMsgGCToServerConsoleCommand() {}
    

    private string _console_command = "";
    public string console_command
    {
      get { return _console_command; }
      set { _console_command = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgServerGetEventPoints : global::ProtoBuf.IExtensible
  {
    public CMsgServerGetEventPoints() {}
    

    private uint _event_id = default(uint);
    public uint event_id
    {
      get { return _event_id; }
      set { _event_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _account_id = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> account_id
    {
      get { return _account_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgServerGetEventPointsResponse : global::ProtoBuf.IExtensible
  {
    public CMsgServerGetEventPointsResponse() {}
    

    private uint _event_id = default(uint);
    public uint event_id
    {
      get { return _event_id; }
      set { _event_id = value; }
    }
    private readonly global::System.Collections.Generic.List<CMsgServerGetEventPointsResponse.Points> _points = new global::System.Collections.Generic.List<CMsgServerGetEventPointsResponse.Points>();
    public global::System.Collections.Generic.List<CMsgServerGetEventPointsResponse.Points> points
    {
      get { return _points; }
    }
  
  public partial class Points : global::ProtoBuf.IExtensible
  {
    public Points() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _points_total = default(uint);
    public uint points_total
    {
      get { return _points_total; }
      set { _points_total = value; }
    }

    private uint _premium_total = default(uint);
    public uint premium_total
    {
      get { return _premium_total; }
      set { _premium_total = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgServerGrantSurveyPermission : global::ProtoBuf.IExtensible
  {
    public CMsgServerGrantSurveyPermission() {}
    
    private readonly global::System.Collections.Generic.List<CMsgServerGrantSurveyPermission.Survey> _surveys = new global::System.Collections.Generic.List<CMsgServerGrantSurveyPermission.Survey>();
    public global::System.Collections.Generic.List<CMsgServerGrantSurveyPermission.Survey> surveys
    {
      get { return _surveys; }
    }
  
  public partial class Survey : global::ProtoBuf.IExtensible
  {
    public Survey() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _question_id = default(uint);
    public uint question_id
    {
      get { return _question_id; }
      set { _question_id = value; }
    }

    private uint _expire_time = default(uint);
    public uint expire_time
    {
      get { return _expire_time; }
      set { _expire_time = value; }
    }

    private ulong _survey_key = default(ulong);
    public ulong survey_key
    {
      get { return _survey_key; }
      set { _survey_key = value; }
    }

    private ulong _extra_data = default(ulong);
    public ulong extra_data
    {
      get { return _extra_data; }
      set { _extra_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgServerGrantSurveyPermissionResponse : global::ProtoBuf.IExtensible
  {
    public CMsgServerGrantSurveyPermissionResponse() {}
    

    private uint _result = default(uint);
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgServerToGCMatchConnectionStats : global::ProtoBuf.IExtensible
  {
    public CMsgServerToGCMatchConnectionStats() {}
    

    private ulong _match_id = default(ulong);
    public ulong match_id
    {
      get { return _match_id; }
      set { _match_id = value; }
    }

    private uint _region_id = default(uint);
    public uint region_id
    {
      get { return _region_id; }
      set { _region_id = value; }
    }

    private uint _league_id = default(uint);
    public uint league_id
    {
      get { return _league_id; }
      set { _league_id = value; }
    }
    private readonly global::System.Collections.Generic.List<CMsgServerToGCMatchConnectionStats.Player> _players = new global::System.Collections.Generic.List<CMsgServerToGCMatchConnectionStats.Player>();
    public global::System.Collections.Generic.List<CMsgServerToGCMatchConnectionStats.Player> players
    {
      get { return _players; }
    }
  
  public partial class Player : global::ProtoBuf.IExtensible
  {
    public Player() {}
    

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _ip = default(uint);
    public uint ip
    {
      get { return _ip; }
      set { _ip = value; }
    }

    private uint _avg_ping_ms = default(uint);
    public uint avg_ping_ms
    {
      get { return _avg_ping_ms; }
      set { _avg_ping_ms = value; }
    }

    private uint _peak_ping_ms = default(uint);
    public uint peak_ping_ms
    {
      get { return _peak_ping_ms; }
      set { _peak_ping_ms = value; }
    }

    private float _packet_loss = default(float);
    public float packet_loss
    {
      get { return _packet_loss; }
      set { _packet_loss = value; }
    }

    private float _ping_deviation = default(float);
    public float ping_deviation
    {
      get { return _ping_deviation; }
      set { _ping_deviation = value; }
    }

    private uint _full_resends = default(uint);
    public uint full_resends
    {
      get { return _full_resends; }
      set { _full_resends = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CMsgServerGCUpdateSpectatorCount : global::ProtoBuf.IExtensible
  {
    public CMsgServerGCUpdateSpectatorCount() {}
    

    private uint _spectator_count = default(uint);
    public uint spectator_count
    {
      get { return _spectator_count; }
      set { _spectator_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
#pragma warning restore 1591
