//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: dota_usermessages.proto
// Note: requires additional types generated from: google/protobuf/descriptor.proto
// Note: requires additional types generated from: networkbasetypes.proto
// Note: requires additional types generated from: ai_activity.proto
// Note: requires additional types generated from: dota_commonmessages.proto
namespace nora.protos
{
  public partial class CDOTAUserMsg_AIDebugLine : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_AIDebugLine() {}
    

    private string _message = "";
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_Ping : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_Ping() {}
    

    private string _message = "";
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_SwapVerify : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_SwapVerify() {}
    

    private uint _player_id = default(uint);
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_ChatEvent : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_ChatEvent() {}
    
    private DOTA_CHAT_MESSAGE _type;
    public DOTA_CHAT_MESSAGE type
    {
      get { return _type; }
      set { _type = value; }
    }

    private uint _value = default(uint);
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }

    private int _playerid_1 = (int)-1;
    public int playerid_1
    {
      get { return _playerid_1; }
      set { _playerid_1 = value; }
    }

    private int _playerid_2 = (int)-1;
    public int playerid_2
    {
      get { return _playerid_2; }
      set { _playerid_2 = value; }
    }

    private int _playerid_3 = (int)-1;
    public int playerid_3
    {
      get { return _playerid_3; }
      set { _playerid_3 = value; }
    }

    private int _playerid_4 = (int)-1;
    public int playerid_4
    {
      get { return _playerid_4; }
      set { _playerid_4 = value; }
    }

    private int _playerid_5 = (int)-1;
    public int playerid_5
    {
      get { return _playerid_5; }
      set { _playerid_5 = value; }
    }

    private int _playerid_6 = (int)-1;
    public int playerid_6
    {
      get { return _playerid_6; }
      set { _playerid_6 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_CombatLogData : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_CombatLogData() {}
    

    private DOTA_COMBATLOG_TYPES _type = DOTA_COMBATLOG_TYPES.DOTA_COMBATLOG_DAMAGE;
    public DOTA_COMBATLOG_TYPES type
    {
      get { return _type; }
      set { _type = value; }
    }

    private uint _target_name = default(uint);
    public uint target_name
    {
      get { return _target_name; }
      set { _target_name = value; }
    }

    private uint _attacker_name = default(uint);
    public uint attacker_name
    {
      get { return _attacker_name; }
      set { _attacker_name = value; }
    }

    private bool _attacker_illusion = default(bool);
    public bool attacker_illusion
    {
      get { return _attacker_illusion; }
      set { _attacker_illusion = value; }
    }

    private bool _target_illusion = default(bool);
    public bool target_illusion
    {
      get { return _target_illusion; }
      set { _target_illusion = value; }
    }

    private uint _inflictor_name = default(uint);
    public uint inflictor_name
    {
      get { return _inflictor_name; }
      set { _inflictor_name = value; }
    }

    private int _value = default(int);
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }

    private int _health = default(int);
    public int health
    {
      get { return _health; }
      set { _health = value; }
    }

    private float _time = default(float);
    public float time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_CombatLogShowDeath : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_CombatLogShowDeath() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_BotChat : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_BotChat() {}
    

    private uint _player_id = default(uint);
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private string _format = "";
    public string format
    {
      get { return _format; }
      set { _format = value; }
    }

    private string _message = "";
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }

    private string _target = "";
    public string target
    {
      get { return _target; }
      set { _target = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_CombatHeroPositions : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_CombatHeroPositions() {}
    

    private uint _index = default(uint);
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }

    private int _time = default(int);
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }

    private CMsgVector2D _world_pos = null;
    public CMsgVector2D world_pos
    {
      get { return _world_pos; }
      set { _world_pos = value; }
    }

    private int _health = default(int);
    public int health
    {
      get { return _health; }
      set { _health = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_MiniKillCamInfo : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_MiniKillCamInfo() {}
    
    private readonly global::System.Collections.Generic.List<CDOTAUserMsg_MiniKillCamInfo.Attacker> _attackers = new global::System.Collections.Generic.List<CDOTAUserMsg_MiniKillCamInfo.Attacker>();
    public global::System.Collections.Generic.List<CDOTAUserMsg_MiniKillCamInfo.Attacker> attackers
    {
      get { return _attackers; }
    }
  
  public partial class Attacker : global::ProtoBuf.IExtensible
  {
    public Attacker() {}
    

    private uint _attacker = default(uint);
    public uint attacker
    {
      get { return _attacker; }
      set { _attacker = value; }
    }

    private int _total_damage = default(int);
    public int total_damage
    {
      get { return _total_damage; }
      set { _total_damage = value; }
    }
    private readonly global::System.Collections.Generic.List<CDOTAUserMsg_MiniKillCamInfo.Attacker.Ability> _abilities = new global::System.Collections.Generic.List<CDOTAUserMsg_MiniKillCamInfo.Attacker.Ability>();
    public global::System.Collections.Generic.List<CDOTAUserMsg_MiniKillCamInfo.Attacker.Ability> abilities
    {
      get { return _abilities; }
    }
  
  public partial class Ability : global::ProtoBuf.IExtensible
  {
    public Ability() {}
    

    private uint _ability = default(uint);
    public uint ability
    {
      get { return _ability; }
      set { _ability = value; }
    }

    private int _damage = default(int);
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_GlobalLightColor : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_GlobalLightColor() {}
    

    private uint _color = default(uint);
    public uint color
    {
      get { return _color; }
      set { _color = value; }
    }

    private float _duration = default(float);
    public float duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_GlobalLightDirection : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_GlobalLightDirection() {}
    

    private CMsgVector _direction = null;
    public CMsgVector direction
    {
      get { return _direction; }
      set { _direction = value; }
    }

    private float _duration = default(float);
    public float duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_LocationPing : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_LocationPing() {}
    

    private uint _player_id = default(uint);
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private CDOTAMsg_LocationPing _location_ping = null;
    public CDOTAMsg_LocationPing location_ping
    {
      get { return _location_ping; }
      set { _location_ping = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_ItemAlert : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_ItemAlert() {}
    

    private uint _player_id = default(uint);
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private CDOTAMsg_ItemAlert _item_alert = null;
    public CDOTAMsg_ItemAlert item_alert
    {
      get { return _item_alert; }
      set { _item_alert = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_WillPurchaseAlert : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_WillPurchaseAlert() {}
    

    private int _itemid = default(int);
    public int itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }

    private int _player_id = default(int);
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_CourierKilledAlert : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_CourierKilledAlert() {}
    

    private uint _team = default(uint);
    public uint team
    {
      get { return _team; }
      set { _team = value; }
    }

    private uint _gold_value = default(uint);
    public uint gold_value
    {
      get { return _gold_value; }
      set { _gold_value = value; }
    }

    private int _entity_handle = default(int);
    public int entity_handle
    {
      get { return _entity_handle; }
      set { _entity_handle = value; }
    }

    private int _timestamp = default(int);
    public int timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_MinimapEvent : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_MinimapEvent() {}
    

    private int _event_type = default(int);
    public int event_type
    {
      get { return _event_type; }
      set { _event_type = value; }
    }

    private int _entity_handle = default(int);
    public int entity_handle
    {
      get { return _entity_handle; }
      set { _entity_handle = value; }
    }

    private int _x = default(int);
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }

    private int _y = default(int);
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }

    private int _duration = default(int);
    public int duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_MapLine : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_MapLine() {}
    

    private int _player_id = default(int);
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private CDOTAMsg_MapLine _mapline = null;
    public CDOTAMsg_MapLine mapline
    {
      get { return _mapline; }
      set { _mapline = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_MinimapDebugPoint : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_MinimapDebugPoint() {}
    

    private CMsgVector _location = null;
    public CMsgVector location
    {
      get { return _location; }
      set { _location = value; }
    }

    private uint _color = default(uint);
    public uint color
    {
      get { return _color; }
      set { _color = value; }
    }

    private int _size = default(int);
    public int size
    {
      get { return _size; }
      set { _size = value; }
    }

    private float _duration = default(float);
    public float duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_CreateLinearProjectile : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_CreateLinearProjectile() {}
    

    private CMsgVector _origin = null;
    public CMsgVector origin
    {
      get { return _origin; }
      set { _origin = value; }
    }

    private CMsgVector2D _velocity = null;
    public CMsgVector2D velocity
    {
      get { return _velocity; }
      set { _velocity = value; }
    }

    private int _latency = default(int);
    public int latency
    {
      get { return _latency; }
      set { _latency = value; }
    }

    private int _entindex = default(int);
    public int entindex
    {
      get { return _entindex; }
      set { _entindex = value; }
    }

    private int _particle_index = default(int);
    public int particle_index
    {
      get { return _particle_index; }
      set { _particle_index = value; }
    }

    private int _handle = default(int);
    public int handle
    {
      get { return _handle; }
      set { _handle = value; }
    }

    private CMsgVector2D _acceleration = null;
    public CMsgVector2D acceleration
    {
      get { return _acceleration; }
      set { _acceleration = value; }
    }

    private float _max_speed = default(float);
    public float max_speed
    {
      get { return _max_speed; }
      set { _max_speed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_DestroyLinearProjectile : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_DestroyLinearProjectile() {}
    

    private int _handle = default(int);
    public int handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_DodgeTrackingProjectiles : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_DodgeTrackingProjectiles() {}
    
    private int _entindex;
    public int entindex
    {
      get { return _entindex; }
      set { _entindex = value; }
    }

    private bool _attacks_only = default(bool);
    public bool attacks_only
    {
      get { return _attacks_only; }
      set { _attacks_only = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_SpectatorPlayerClick : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_SpectatorPlayerClick() {}
    
    private int _entindex;
    public int entindex
    {
      get { return _entindex; }
      set { _entindex = value; }
    }

    private int _order_type = default(int);
    public int order_type
    {
      get { return _order_type; }
      set { _order_type = value; }
    }

    private int _target_index = default(int);
    public int target_index
    {
      get { return _target_index; }
      set { _target_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_NevermoreRequiem : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_NevermoreRequiem() {}
    

    private int _entity_handle = default(int);
    public int entity_handle
    {
      get { return _entity_handle; }
      set { _entity_handle = value; }
    }

    private int _lines = default(int);
    public int lines
    {
      get { return _lines; }
      set { _lines = value; }
    }

    private CMsgVector _origin = null;
    public CMsgVector origin
    {
      get { return _origin; }
      set { _origin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_InvalidCommand : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_InvalidCommand() {}
    

    private string _message = "";
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_HudError : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_HudError() {}
    

    private int _order_id = default(int);
    public int order_id
    {
      get { return _order_id; }
      set { _order_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_SharedCooldown : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_SharedCooldown() {}
    

    private int _entindex = default(int);
    public int entindex
    {
      get { return _entindex; }
      set { _entindex = value; }
    }

    private string _name = "";
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private float _cooldown = default(float);
    public float cooldown
    {
      get { return _cooldown; }
      set { _cooldown = value; }
    }

    private int _name_index = default(int);
    public int name_index
    {
      get { return _name_index; }
      set { _name_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_SetNextAutobuyItem : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_SetNextAutobuyItem() {}
    

    private string _name = "";
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_HalloweenDrops : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_HalloweenDrops() {}
    
    private readonly global::System.Collections.Generic.List<uint> _item_defs = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> item_defs
    {
      get { return _item_defs; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _player_ids = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> player_ids
    {
      get { return _player_ids; }
    }
  

    private uint _prize_list = default(uint);
    public uint prize_list
    {
      get { return _prize_list; }
      set { _prize_list = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAResponseQuerySerialized : global::ProtoBuf.IExtensible
  {
    public CDOTAResponseQuerySerialized() {}
    
    private readonly global::System.Collections.Generic.List<CDOTAResponseQuerySerialized.Fact> _facts = new global::System.Collections.Generic.List<CDOTAResponseQuerySerialized.Fact>();
    public global::System.Collections.Generic.List<CDOTAResponseQuerySerialized.Fact> facts
    {
      get { return _facts; }
    }
  
  public partial class Fact : global::ProtoBuf.IExtensible
  {
    public Fact() {}
    
    private int _key;
    public int key
    {
      get { return _key; }
      set { _key = value; }
    }
    private CDOTAResponseQuerySerialized.Fact.ValueType _valtype;
    public CDOTAResponseQuerySerialized.Fact.ValueType valtype
    {
      get { return _valtype; }
      set { _valtype = value; }
    }

    private float _val_numeric = default(float);
    public float val_numeric
    {
      get { return _val_numeric; }
      set { _val_numeric = value; }
    }

    private string _val_string = "";
    public string val_string
    {
      get { return _val_string; }
      set { _val_string = value; }
    }
    public enum ValueType
    {
            
      NUMERIC = 1,
            
      STRING = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTASpeechMatchOnClient : global::ProtoBuf.IExtensible
  {
    public CDOTASpeechMatchOnClient() {}
    

    private int _concept = default(int);
    public int concept
    {
      get { return _concept; }
      set { _concept = value; }
    }

    private int _recipient_type = default(int);
    public int recipient_type
    {
      get { return _recipient_type; }
      set { _recipient_type = value; }
    }

    private CDOTAResponseQuerySerialized _responsequery = null;
    public CDOTAResponseQuerySerialized responsequery
    {
      get { return _responsequery; }
      set { _responsequery = value; }
    }

    private int _randomseed = (int)0;
    public int randomseed
    {
      get { return _randomseed; }
      set { _randomseed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_UnitEvent : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_UnitEvent() {}
    
    private EDotaEntityMessages _msg_type;
    public EDotaEntityMessages msg_type
    {
      get { return _msg_type; }
      set { _msg_type = value; }
    }
    private int _entity_index;
    public int entity_index
    {
      get { return _entity_index; }
      set { _entity_index = value; }
    }

    private CDOTAUserMsg_UnitEvent.Speech _speech = null;
    public CDOTAUserMsg_UnitEvent.Speech speech
    {
      get { return _speech; }
      set { _speech = value; }
    }

    private CDOTAUserMsg_UnitEvent.SpeechMute _speech_mute = null;
    public CDOTAUserMsg_UnitEvent.SpeechMute speech_mute
    {
      get { return _speech_mute; }
      set { _speech_mute = value; }
    }

    private CDOTAUserMsg_UnitEvent.AddGesture _add_gesture = null;
    public CDOTAUserMsg_UnitEvent.AddGesture add_gesture
    {
      get { return _add_gesture; }
      set { _add_gesture = value; }
    }

    private CDOTAUserMsg_UnitEvent.RemoveGesture _remove_gesture = null;
    public CDOTAUserMsg_UnitEvent.RemoveGesture remove_gesture
    {
      get { return _remove_gesture; }
      set { _remove_gesture = value; }
    }

    private CDOTAUserMsg_UnitEvent.BloodImpact _blood_impact = null;
    public CDOTAUserMsg_UnitEvent.BloodImpact blood_impact
    {
      get { return _blood_impact; }
      set { _blood_impact = value; }
    }

    private CDOTAUserMsg_UnitEvent.FadeGesture _fade_gesture = null;
    public CDOTAUserMsg_UnitEvent.FadeGesture fade_gesture
    {
      get { return _fade_gesture; }
      set { _fade_gesture = value; }
    }

    private CDOTASpeechMatchOnClient _speech_match_on_client = null;
    public CDOTASpeechMatchOnClient speech_match_on_client
    {
      get { return _speech_match_on_client; }
      set { _speech_match_on_client = value; }
    }
  public partial class Speech : global::ProtoBuf.IExtensible
  {
    public Speech() {}
    

    private int _concept = default(int);
    public int concept
    {
      get { return _concept; }
      set { _concept = value; }
    }

    private string _response = "";
    public string response
    {
      get { return _response; }
      set { _response = value; }
    }

    private int _recipient_type = default(int);
    public int recipient_type
    {
      get { return _recipient_type; }
      set { _recipient_type = value; }
    }

    private int _level = default(int);
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }

    private bool _muteable = (bool)false;
    public bool muteable
    {
      get { return _muteable; }
      set { _muteable = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class SpeechMute : global::ProtoBuf.IExtensible
  {
    public SpeechMute() {}
    

    private float _delay = (float)0.5;
    public float delay
    {
      get { return _delay; }
      set { _delay = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class AddGesture : global::ProtoBuf.IExtensible
  {
    public AddGesture() {}
    

    private Activity _activity = Activity.ACT_INVALID;
    public Activity activity
    {
      get { return _activity; }
      set { _activity = value; }
    }

    private int _slot = default(int);
    public int slot
    {
      get { return _slot; }
      set { _slot = value; }
    }

    private float _fade_in = (float)0;
    public float fade_in
    {
      get { return _fade_in; }
      set { _fade_in = value; }
    }

    private float _fade_out = (float)0.1;
    public float fade_out
    {
      get { return _fade_out; }
      set { _fade_out = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class RemoveGesture : global::ProtoBuf.IExtensible
  {
    public RemoveGesture() {}
    

    private Activity _activity = Activity.ACT_INVALID;
    public Activity activity
    {
      get { return _activity; }
      set { _activity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class BloodImpact : global::ProtoBuf.IExtensible
  {
    public BloodImpact() {}
    

    private int _scale = default(int);
    public int scale
    {
      get { return _scale; }
      set { _scale = value; }
    }

    private int _x_normal = default(int);
    public int x_normal
    {
      get { return _x_normal; }
      set { _x_normal = value; }
    }

    private int _y_normal = default(int);
    public int y_normal
    {
      get { return _y_normal; }
      set { _y_normal = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class FadeGesture : global::ProtoBuf.IExtensible
  {
    public FadeGesture() {}
    

    private Activity _activity = Activity.ACT_INVALID;
    public Activity activity
    {
      get { return _activity; }
      set { _activity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_ItemPurchased : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_ItemPurchased() {}
    

    private int _item_index = default(int);
    public int item_index
    {
      get { return _item_index; }
      set { _item_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_ItemFound : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_ItemFound() {}
    

    private int _player = default(int);
    public int player
    {
      get { return _player; }
      set { _player = value; }
    }

    private int _quality = default(int);
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }

    private int _rarity = default(int);
    public int rarity
    {
      get { return _rarity; }
      set { _rarity = value; }
    }

    private int _method = default(int);
    public int method
    {
      get { return _method; }
      set { _method = value; }
    }

    private int _itemdef = default(int);
    public int itemdef
    {
      get { return _itemdef; }
      set { _itemdef = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_ParticleManager : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_ParticleManager() {}
    
    private DOTA_PARTICLE_MESSAGE _type;
    public DOTA_PARTICLE_MESSAGE type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _index;
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }

    private CDOTAUserMsg_ParticleManager.ReleaseParticleIndex _release_particle_index = null;
    public CDOTAUserMsg_ParticleManager.ReleaseParticleIndex release_particle_index
    {
      get { return _release_particle_index; }
      set { _release_particle_index = value; }
    }

    private CDOTAUserMsg_ParticleManager.CreateParticle _create_particle = null;
    public CDOTAUserMsg_ParticleManager.CreateParticle create_particle
    {
      get { return _create_particle; }
      set { _create_particle = value; }
    }

    private CDOTAUserMsg_ParticleManager.DestroyParticle _destroy_particle = null;
    public CDOTAUserMsg_ParticleManager.DestroyParticle destroy_particle
    {
      get { return _destroy_particle; }
      set { _destroy_particle = value; }
    }

    private CDOTAUserMsg_ParticleManager.DestroyParticleInvolving _destroy_particle_involving = null;
    public CDOTAUserMsg_ParticleManager.DestroyParticleInvolving destroy_particle_involving
    {
      get { return _destroy_particle_involving; }
      set { _destroy_particle_involving = value; }
    }

    private CDOTAUserMsg_ParticleManager.UpdateParticle _update_particle = null;
    public CDOTAUserMsg_ParticleManager.UpdateParticle update_particle
    {
      get { return _update_particle; }
      set { _update_particle = value; }
    }

    private CDOTAUserMsg_ParticleManager.UpdateParticleFwd _update_particle_fwd = null;
    public CDOTAUserMsg_ParticleManager.UpdateParticleFwd update_particle_fwd
    {
      get { return _update_particle_fwd; }
      set { _update_particle_fwd = value; }
    }

    private CDOTAUserMsg_ParticleManager.UpdateParticleOrient _update_particle_orient = null;
    public CDOTAUserMsg_ParticleManager.UpdateParticleOrient update_particle_orient
    {
      get { return _update_particle_orient; }
      set { _update_particle_orient = value; }
    }

    private CDOTAUserMsg_ParticleManager.UpdateParticleFallback _update_particle_fallback = null;
    public CDOTAUserMsg_ParticleManager.UpdateParticleFallback update_particle_fallback
    {
      get { return _update_particle_fallback; }
      set { _update_particle_fallback = value; }
    }

    private CDOTAUserMsg_ParticleManager.UpdateParticleOffset _update_particle_offset = null;
    public CDOTAUserMsg_ParticleManager.UpdateParticleOffset update_particle_offset
    {
      get { return _update_particle_offset; }
      set { _update_particle_offset = value; }
    }

    private CDOTAUserMsg_ParticleManager.UpdateParticleEnt _update_particle_ent = null;
    public CDOTAUserMsg_ParticleManager.UpdateParticleEnt update_particle_ent
    {
      get { return _update_particle_ent; }
      set { _update_particle_ent = value; }
    }

    private CDOTAUserMsg_ParticleManager.UpdateParticleShouldDraw _update_particle_should_draw = null;
    public CDOTAUserMsg_ParticleManager.UpdateParticleShouldDraw update_particle_should_draw
    {
      get { return _update_particle_should_draw; }
      set { _update_particle_should_draw = value; }
    }

    private CDOTAUserMsg_ParticleManager.UpdateParticleSetFrozen _update_particle_set_frozen = null;
    public CDOTAUserMsg_ParticleManager.UpdateParticleSetFrozen update_particle_set_frozen
    {
      get { return _update_particle_set_frozen; }
      set { _update_particle_set_frozen = value; }
    }
  public partial class ReleaseParticleIndex : global::ProtoBuf.IExtensible
  {
    public ReleaseParticleIndex() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CreateParticle : global::ProtoBuf.IExtensible
  {
    public CreateParticle() {}
    

    private int _particle_name_index = default(int);
    public int particle_name_index
    {
      get { return _particle_name_index; }
      set { _particle_name_index = value; }
    }

    private int _attach_type = default(int);
    public int attach_type
    {
      get { return _attach_type; }
      set { _attach_type = value; }
    }

    private int _entity_handle = default(int);
    public int entity_handle
    {
      get { return _entity_handle; }
      set { _entity_handle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class DestroyParticle : global::ProtoBuf.IExtensible
  {
    public DestroyParticle() {}
    

    private bool _destroy_immediately = default(bool);
    public bool destroy_immediately
    {
      get { return _destroy_immediately; }
      set { _destroy_immediately = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class DestroyParticleInvolving : global::ProtoBuf.IExtensible
  {
    public DestroyParticleInvolving() {}
    

    private bool _destroy_immediately = default(bool);
    public bool destroy_immediately
    {
      get { return _destroy_immediately; }
      set { _destroy_immediately = value; }
    }

    private int _entity_handle = default(int);
    public int entity_handle
    {
      get { return _entity_handle; }
      set { _entity_handle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class UpdateParticle : global::ProtoBuf.IExtensible
  {
    public UpdateParticle() {}
    

    private int _control_point = default(int);
    public int control_point
    {
      get { return _control_point; }
      set { _control_point = value; }
    }

    private CMsgVector _position = null;
    public CMsgVector position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class UpdateParticleFwd : global::ProtoBuf.IExtensible
  {
    public UpdateParticleFwd() {}
    

    private int _control_point = default(int);
    public int control_point
    {
      get { return _control_point; }
      set { _control_point = value; }
    }

    private CMsgVector _forward = null;
    public CMsgVector forward
    {
      get { return _forward; }
      set { _forward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class UpdateParticleOrient : global::ProtoBuf.IExtensible
  {
    public UpdateParticleOrient() {}
    

    private int _control_point = default(int);
    public int control_point
    {
      get { return _control_point; }
      set { _control_point = value; }
    }

    private CMsgVector _forward = null;
    public CMsgVector forward
    {
      get { return _forward; }
      set { _forward = value; }
    }

    private CMsgVector _right = null;
    public CMsgVector right
    {
      get { return _right; }
      set { _right = value; }
    }

    private CMsgVector _up = null;
    public CMsgVector up
    {
      get { return _up; }
      set { _up = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class UpdateParticleFallback : global::ProtoBuf.IExtensible
  {
    public UpdateParticleFallback() {}
    

    private int _control_point = default(int);
    public int control_point
    {
      get { return _control_point; }
      set { _control_point = value; }
    }

    private CMsgVector _position = null;
    public CMsgVector position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class UpdateParticleOffset : global::ProtoBuf.IExtensible
  {
    public UpdateParticleOffset() {}
    

    private int _control_point = default(int);
    public int control_point
    {
      get { return _control_point; }
      set { _control_point = value; }
    }

    private CMsgVector _origin_offset = null;
    public CMsgVector origin_offset
    {
      get { return _origin_offset; }
      set { _origin_offset = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class UpdateParticleEnt : global::ProtoBuf.IExtensible
  {
    public UpdateParticleEnt() {}
    

    private int _control_point = default(int);
    public int control_point
    {
      get { return _control_point; }
      set { _control_point = value; }
    }

    private int _entity_handle = default(int);
    public int entity_handle
    {
      get { return _entity_handle; }
      set { _entity_handle = value; }
    }

    private int _attach_type = default(int);
    public int attach_type
    {
      get { return _attach_type; }
      set { _attach_type = value; }
    }

    private int _attachment = default(int);
    public int attachment
    {
      get { return _attachment; }
      set { _attachment = value; }
    }

    private CMsgVector _fallback_position = null;
    public CMsgVector fallback_position
    {
      get { return _fallback_position; }
      set { _fallback_position = value; }
    }

    private bool _include_wearables = default(bool);
    public bool include_wearables
    {
      get { return _include_wearables; }
      set { _include_wearables = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class UpdateParticleSetFrozen : global::ProtoBuf.IExtensible
  {
    public UpdateParticleSetFrozen() {}
    

    private bool _set_frozen = default(bool);
    public bool set_frozen
    {
      get { return _set_frozen; }
      set { _set_frozen = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class UpdateParticleShouldDraw : global::ProtoBuf.IExtensible
  {
    public UpdateParticleShouldDraw() {}
    

    private bool _should_draw = default(bool);
    public bool should_draw
    {
      get { return _should_draw; }
      set { _should_draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_OverheadEvent : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_OverheadEvent() {}
    
    private DOTA_OVERHEAD_ALERT _message_type;
    public DOTA_OVERHEAD_ALERT message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private int _value = default(int);
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }

    private int _target_player_entindex = default(int);
    public int target_player_entindex
    {
      get { return _target_player_entindex; }
      set { _target_player_entindex = value; }
    }

    private int _target_entindex = default(int);
    public int target_entindex
    {
      get { return _target_entindex; }
      set { _target_entindex = value; }
    }

    private int _source_player_entindex = default(int);
    public int source_player_entindex
    {
      get { return _source_player_entindex; }
      set { _source_player_entindex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_TutorialTipInfo : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_TutorialTipInfo() {}
    

    private string _name = "";
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private int _progress = default(int);
    public int progress
    {
      get { return _progress; }
      set { _progress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_TutorialFinish : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_TutorialFinish() {}
    

    private string _heading = "";
    public string heading
    {
      get { return _heading; }
      set { _heading = value; }
    }

    private string _emblem = "";
    public string emblem
    {
      get { return _emblem; }
      set { _emblem = value; }
    }

    private string _body = "";
    public string body
    {
      get { return _body; }
      set { _body = value; }
    }

    private bool _success = default(bool);
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_TutorialMinimapPosition : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_TutorialMinimapPosition() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_SendGenericToolTip : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_SendGenericToolTip() {}
    

    private string _title = "";
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }

    private string _text = "";
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }

    private int _entindex = default(int);
    public int entindex
    {
      get { return _entindex; }
      set { _entindex = value; }
    }

    private bool _close = default(bool);
    public bool close
    {
      get { return _close; }
      set { _close = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_WorldLine : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_WorldLine() {}
    

    private int _player_id = default(int);
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private CDOTAMsg_WorldLine _worldline = null;
    public CDOTAMsg_WorldLine worldline
    {
      get { return _worldline; }
      set { _worldline = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_ChatWheel : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_ChatWheel() {}
    

    private EDOTAChatWheelMessage _chat_message = EDOTAChatWheelMessage.k_EDOTA_CW_Ok;
    public EDOTAChatWheelMessage chat_message
    {
      get { return _chat_message; }
      set { _chat_message = value; }
    }

    private uint _player_id = default(uint);
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private uint _account_id = default(uint);
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _param_hero_id = default(uint);
    public uint param_hero_id
    {
      get { return _param_hero_id; }
      set { _param_hero_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_ReceivedXmasGift : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_ReceivedXmasGift() {}
    

    private int _player_id = default(int);
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private string _item_name = "";
    public string item_name
    {
      get { return _item_name; }
      set { _item_name = value; }
    }

    private int _inventory_slot = default(int);
    public int inventory_slot
    {
      get { return _inventory_slot; }
      set { _inventory_slot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_ShowSurvey : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_ShowSurvey() {}
    

    private int _survey_id = default(int);
    public int survey_id
    {
      get { return _survey_id; }
      set { _survey_id = value; }
    }

    private uint _match_id = default(uint);
    public uint match_id
    {
      get { return _match_id; }
      set { _match_id = value; }
    }

    private string _response_style = "";
    public string response_style
    {
      get { return _response_style; }
      set { _response_style = value; }
    }

    private uint _teammate_hero_id = default(uint);
    public uint teammate_hero_id
    {
      get { return _teammate_hero_id; }
      set { _teammate_hero_id = value; }
    }

    private string _teammate_name = "";
    public string teammate_name
    {
      get { return _teammate_name; }
      set { _teammate_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_UpdateSharedContent : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_UpdateSharedContent() {}
    

    private int _slot_type = default(int);
    public int slot_type
    {
      get { return _slot_type; }
      set { _slot_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_TutorialRequestExp : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_TutorialRequestExp() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_TutorialFade : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_TutorialFade() {}
    

    private int _tgt_alpha = default(int);
    public int tgt_alpha
    {
      get { return _tgt_alpha; }
      set { _tgt_alpha = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_TutorialPingMinimap : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_TutorialPingMinimap() {}
    

    private uint _player_id = default(uint);
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private float _pos_x = default(float);
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }

    private float _pos_y = default(float);
    public float pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }

    private float _pos_z = default(float);
    public float pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }

    private int _entity_index = default(int);
    public int entity_index
    {
      get { return _entity_index; }
      set { _entity_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTA_UM_GamerulesStateChanged : global::ProtoBuf.IExtensible
  {
    public CDOTA_UM_GamerulesStateChanged() {}
    

    private uint _state = default(uint);
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_AddQuestLogEntry : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_AddQuestLogEntry() {}
    

    private string _npc_name = "";
    public string npc_name
    {
      get { return _npc_name; }
      set { _npc_name = value; }
    }

    private string _npc_dialog = "";
    public string npc_dialog
    {
      get { return _npc_dialog; }
      set { _npc_dialog = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_SendStatPopup : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_SendStatPopup() {}
    

    private int _player_id = default(int);
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private CDOTAMsg_SendStatPopup _statpopup = null;
    public CDOTAMsg_SendStatPopup statpopup
    {
      get { return _statpopup; }
      set { _statpopup = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_SendRoshanPopup : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_SendRoshanPopup() {}
    

    private bool _reclaimed = default(bool);
    public bool reclaimed
    {
      get { return _reclaimed; }
      set { _reclaimed = value; }
    }

    private int _gametime = default(int);
    public int gametime
    {
      get { return _gametime; }
      set { _gametime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_SendFinalGold : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_SendFinalGold() {}
    
    private readonly global::System.Collections.Generic.List<uint> _reliable_gold = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> reliable_gold
    {
      get { return _reliable_gold; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _unreliable_gold = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> unreliable_gold
    {
      get { return _unreliable_gold; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_CustomMsg : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_CustomMsg() {}
    

    private string _message = "";
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }

    private int _player_id = default(int);
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private int _value = default(int);
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_CoachHUDPing : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_CoachHUDPing() {}
    

    private uint _player_id = default(uint);
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private CDOTAMsg_CoachHUDPing _hud_ping = null;
    public CDOTAMsg_CoachHUDPing hud_ping
    {
      get { return _hud_ping; }
      set { _hud_ping = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_ClientLoadGridNav : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_ClientLoadGridNav() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_AbilityPing : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_AbilityPing() {}
    

    private uint _player_id = default(uint);
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private uint _ability_id = default(uint);
    public uint ability_id
    {
      get { return _ability_id; }
      set { _ability_id = value; }
    }

    private DOTA_ABILITY_PING_TYPE _type = DOTA_ABILITY_PING_TYPE.ABILITY_PING_READY;
    public DOTA_ABILITY_PING_TYPE type
    {
      get { return _type; }
      set { _type = value; }
    }

    private uint _cooldown_seconds = default(uint);
    public uint cooldown_seconds
    {
      get { return _cooldown_seconds; }
      set { _cooldown_seconds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_ShowGenericPopup : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_ShowGenericPopup() {}
    
    private string _header;
    public string header
    {
      get { return _header; }
      set { _header = value; }
    }
    private string _body;
    public string body
    {
      get { return _body; }
      set { _body = value; }
    }

    private string _param1 = "";
    public string param1
    {
      get { return _param1; }
      set { _param1 = value; }
    }

    private string _param2 = "";
    public string param2
    {
      get { return _param2; }
      set { _param2 = value; }
    }

    private bool _tint_screen = default(bool);
    public bool tint_screen
    {
      get { return _tint_screen; }
      set { _tint_screen = value; }
    }

    private bool _show_no_other_dialogs = default(bool);
    public bool show_no_other_dialogs
    {
      get { return _show_no_other_dialogs; }
      set { _show_no_other_dialogs = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_VoteStart : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_VoteStart() {}
    

    private string _title = "";
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }

    private float _duration = default(float);
    public float duration
    {
      get { return _duration; }
      set { _duration = value; }
    }

    private int _choice_count = default(int);
    public int choice_count
    {
      get { return _choice_count; }
      set { _choice_count = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _choices = new global::System.Collections.Generic.List<string>();
    public global::System.Collections.Generic.List<string> choices
    {
      get { return _choices; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_VoteUpdate : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_VoteUpdate() {}
    
    private readonly global::System.Collections.Generic.List<int> _choice_counts = new global::System.Collections.Generic.List<int>();
    public global::System.Collections.Generic.List<int> choice_counts
    {
      get { return _choice_counts; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_VoteEnd : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_VoteEnd() {}
    

    private int _selected_choice = default(int);
    public int selected_choice
    {
      get { return _selected_choice; }
      set { _selected_choice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_BoosterStatePlayer : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_BoosterStatePlayer() {}
    

    private uint _player_id = default(uint);
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private float _bonus = default(float);
    public float bonus
    {
      get { return _bonus; }
      set { _bonus = value; }
    }

    private float _event_bonus = default(float);
    public float event_bonus
    {
      get { return _event_bonus; }
      set { _event_bonus = value; }
    }

    private uint _bonus_item_id = default(uint);
    public uint bonus_item_id
    {
      get { return _bonus_item_id; }
      set { _bonus_item_id = value; }
    }

    private uint _event_bonus_item_id = default(uint);
    public uint event_bonus_item_id
    {
      get { return _event_bonus_item_id; }
      set { _event_bonus_item_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_BoosterState : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_BoosterState() {}
    
    private readonly global::System.Collections.Generic.List<CDOTAUserMsg_BoosterStatePlayer> _boosted_players = new global::System.Collections.Generic.List<CDOTAUserMsg_BoosterStatePlayer>();
    public global::System.Collections.Generic.List<CDOTAUserMsg_BoosterStatePlayer> boosted_players
    {
      get { return _boosted_players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_PlayerMMR : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_PlayerMMR() {}
    
    private readonly global::System.Collections.Generic.List<int> _mmr = new global::System.Collections.Generic.List<int>();
    public global::System.Collections.Generic.List<int> mmr
    {
      get { return _mmr; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CDOTAUserMsg_AbilitySteal : global::ProtoBuf.IExtensible
  {
    public CDOTAUserMsg_AbilitySteal() {}
    

    private uint _player_id = default(uint);
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private uint _ability_id = default(uint);
    public uint ability_id
    {
      get { return _ability_id; }
      set { _ability_id = value; }
    }

    private uint _ability_level = default(uint);
    public uint ability_level
    {
      get { return _ability_level; }
      set { _ability_level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public enum EDotaUserMessages
    {
            
      DOTA_UM_AddUnitToSelection = 64,
            
      DOTA_UM_AIDebugLine = 65,
            
      DOTA_UM_ChatEvent = 66,
            
      DOTA_UM_CombatHeroPositions = 67,
            
      DOTA_UM_CombatLogData = 68,
            
      DOTA_UM_CombatLogShowDeath = 70,
            
      DOTA_UM_CreateLinearProjectile = 71,
            
      DOTA_UM_DestroyLinearProjectile = 72,
            
      DOTA_UM_DodgeTrackingProjectiles = 73,
            
      DOTA_UM_GlobalLightColor = 74,
            
      DOTA_UM_GlobalLightDirection = 75,
            
      DOTA_UM_InvalidCommand = 76,
            
      DOTA_UM_LocationPing = 77,
            
      DOTA_UM_MapLine = 78,
            
      DOTA_UM_MiniKillCamInfo = 79,
            
      DOTA_UM_MinimapDebugPoint = 80,
            
      DOTA_UM_MinimapEvent = 81,
            
      DOTA_UM_NevermoreRequiem = 82,
            
      DOTA_UM_OverheadEvent = 83,
            
      DOTA_UM_SetNextAutobuyItem = 84,
            
      DOTA_UM_SharedCooldown = 85,
            
      DOTA_UM_SpectatorPlayerClick = 86,
            
      DOTA_UM_TutorialTipInfo = 87,
            
      DOTA_UM_UnitEvent = 88,
            
      DOTA_UM_ParticleManager = 89,
            
      DOTA_UM_BotChat = 90,
            
      DOTA_UM_HudError = 91,
            
      DOTA_UM_ItemPurchased = 92,
            
      DOTA_UM_Ping = 93,
            
      DOTA_UM_ItemFound = 94,
            
      DOTA_UM_CharacterSpeakConcept = 95,
            
      DOTA_UM_SwapVerify = 96,
            
      DOTA_UM_WorldLine = 97,
            
      DOTA_UM_TournamentDrop = 98,
            
      DOTA_UM_ItemAlert = 99,
            
      DOTA_UM_HalloweenDrops = 100,
            
      DOTA_UM_ChatWheel = 101,
            
      DOTA_UM_ReceivedXmasGift = 102,
            
      DOTA_UM_UpdateSharedContent = 103,
            
      DOTA_UM_TutorialRequestExp = 104,
            
      DOTA_UM_TutorialPingMinimap = 105,
            
      DOTA_UM_GamerulesStateChanged = 106,
            
      DOTA_UM_ShowSurvey = 107,
            
      DOTA_UM_TutorialFade = 108,
            
      DOTA_UM_AddQuestLogEntry = 109,
            
      DOTA_UM_SendStatPopup = 110,
            
      DOTA_UM_TutorialFinish = 111,
            
      DOTA_UM_SendRoshanPopup = 112,
            
      DOTA_UM_SendGenericToolTip = 113,
            
      DOTA_UM_SendFinalGold = 114,
            
      DOTA_UM_CustomMsg = 115,
            
      DOTA_UM_CoachHUDPing = 116,
            
      DOTA_UM_ClientLoadGridNav = 117,
            
      DOTA_UM_AbilityPing = 118,
            
      DOTA_UM_ShowGenericPopup = 119,
            
      DOTA_UM_VoteStart = 120,
            
      DOTA_UM_VoteUpdate = 121,
            
      DOTA_UM_VoteEnd = 122,
            
      DOTA_UM_BoosterState = 123,
            
      DOTA_UM_WillPurchaseAlert = 124,
            
      DOTA_UM_TutorialMinimapPosition = 125,
            
      DOTA_UM_PlayerMMR = 126,
            
      DOTA_UM_AbilitySteal = 127,
            
      DOTA_UM_CourierKilledAlert = 128
    }
  
    public enum DOTA_CHAT_MESSAGE
    {
            
      CHAT_MESSAGE_INVALID = -1,
            
      CHAT_MESSAGE_HERO_KILL = 0,
            
      CHAT_MESSAGE_HERO_DENY = 1,
            
      CHAT_MESSAGE_BARRACKS_KILL = 2,
            
      CHAT_MESSAGE_TOWER_KILL = 3,
            
      CHAT_MESSAGE_TOWER_DENY = 4,
            
      CHAT_MESSAGE_FIRSTBLOOD = 5,
            
      CHAT_MESSAGE_STREAK_KILL = 6,
            
      CHAT_MESSAGE_BUYBACK = 7,
            
      CHAT_MESSAGE_AEGIS = 8,
            
      CHAT_MESSAGE_ROSHAN_KILL = 9,
            
      CHAT_MESSAGE_COURIER_LOST = 10,
            
      CHAT_MESSAGE_COURIER_RESPAWNED = 11,
            
      CHAT_MESSAGE_GLYPH_USED = 12,
            
      CHAT_MESSAGE_ITEM_PURCHASE = 13,
            
      CHAT_MESSAGE_CONNECT = 14,
            
      CHAT_MESSAGE_DISCONNECT = 15,
            
      CHAT_MESSAGE_DISCONNECT_WAIT_FOR_RECONNECT = 16,
            
      CHAT_MESSAGE_DISCONNECT_TIME_REMAINING = 17,
            
      CHAT_MESSAGE_DISCONNECT_TIME_REMAINING_PLURAL = 18,
            
      CHAT_MESSAGE_RECONNECT = 19,
            
      CHAT_MESSAGE_PLAYER_LEFT = 20,
            
      CHAT_MESSAGE_SAFE_TO_LEAVE = 21,
            
      CHAT_MESSAGE_RUNE_PICKUP = 22,
            
      CHAT_MESSAGE_RUNE_BOTTLE = 23,
            
      CHAT_MESSAGE_INTHEBAG = 24,
            
      CHAT_MESSAGE_SECRETSHOP = 25,
            
      CHAT_MESSAGE_ITEM_AUTOPURCHASED = 26,
            
      CHAT_MESSAGE_ITEMS_COMBINED = 27,
            
      CHAT_MESSAGE_SUPER_CREEPS = 28,
            
      CHAT_MESSAGE_CANT_USE_ACTION_ITEM = 29,
            
      CHAT_MESSAGE_CHARGES_EXHAUSTED = 30,
            
      CHAT_MESSAGE_CANTPAUSE = 31,
            
      CHAT_MESSAGE_NOPAUSESLEFT = 32,
            
      CHAT_MESSAGE_CANTPAUSEYET = 33,
            
      CHAT_MESSAGE_PAUSED = 34,
            
      CHAT_MESSAGE_UNPAUSE_COUNTDOWN = 35,
            
      CHAT_MESSAGE_UNPAUSED = 36,
            
      CHAT_MESSAGE_AUTO_UNPAUSED = 37,
            
      CHAT_MESSAGE_YOUPAUSED = 38,
            
      CHAT_MESSAGE_CANTUNPAUSETEAM = 39,
            
      CHAT_MESSAGE_VOICE_TEXT_BANNED = 41,
            
      CHAT_MESSAGE_SPECTATORS_WATCHING_THIS_GAME = 42,
            
      CHAT_MESSAGE_REPORT_REMINDER = 43,
            
      CHAT_MESSAGE_ECON_ITEM = 44,
            
      CHAT_MESSAGE_TAUNT = 45,
            
      CHAT_MESSAGE_RANDOM = 46,
            
      CHAT_MESSAGE_RD_TURN = 47,
            
      CHAT_MESSAGE_DROP_RATE_BONUS = 49,
            
      CHAT_MESSAGE_NO_BATTLE_POINTS = 50,
            
      CHAT_MESSAGE_DENIED_AEGIS = 51,
            
      CHAT_MESSAGE_INFORMATIONAL = 52,
            
      CHAT_MESSAGE_AEGIS_STOLEN = 53,
            
      CHAT_MESSAGE_ROSHAN_CANDY = 54,
            
      CHAT_MESSAGE_ITEM_GIFTED = 55,
            
      CHAT_MESSAGE_HERO_KILL_WITH_GREEVIL = 56,
            
      CHAT_MESSAGE_HOLDOUT_TOWER_DESTROYED = 57,
            
      CHAT_MESSAGE_HOLDOUT_WALL_DESTROYED = 58,
            
      CHAT_MESSAGE_HOLDOUT_WALL_FINISHED = 59,
            
      CHAT_MESSAGE_PLAYER_LEFT_LIMITED_HERO = 62,
            
      CHAT_MESSAGE_ABANDON_LIMITED_HERO_EXPLANATION = 63,
            
      CHAT_MESSAGE_DISCONNECT_LIMITED_HERO = 64,
            
      CHAT_MESSAGE_LOW_PRIORITY_COMPLETED_EXPLANATION = 65,
            
      CHAT_MESSAGE_RECRUITMENT_DROP_RATE_BONUS = 66,
            
      CHAT_MESSAGE_FROSTIVUS_SHINING_BOOSTER_ACTIVE = 67,
            
      CHAT_MESSAGE_PLAYER_LEFT_AFK = 73,
            
      CHAT_MESSAGE_PLAYER_LEFT_DISCONNECTED_TOO_LONG = 74,
            
      CHAT_MESSAGE_PLAYER_ABANDONED = 75,
            
      CHAT_MESSAGE_PLAYER_ABANDONED_AFK = 76,
            
      CHAT_MESSAGE_PLAYER_ABANDONED_DISCONNECTED_TOO_LONG = 77,
            
      CHAT_MESSAGE_WILL_NOT_BE_SCORED = 78,
            
      CHAT_MESSAGE_WILL_NOT_BE_SCORED_RANKED = 79,
            
      CHAT_MESSAGE_WILL_NOT_BE_SCORED_NETWORK = 80,
            
      CHAT_MESSAGE_WILL_NOT_BE_SCORED_NETWORK_RANKED = 81,
            
      CHAT_MESSAGE_CAN_QUIT_WITHOUT_ABANDON = 82,
            
      CHAT_MESSAGE_RANKED_GAME_STILL_SCORED_LEAVERS_GET_LOSS = 83,
            
      CHAT_MESSAGE_ABANDON_RANKED_BEFORE_FIRST_BLOOD_PARTY = 84,
            
      CHAT_MESSAGE_COMPENDIUM_LEVEL = 85
    }
  
    public enum DOTA_NO_BATTLE_POINTS_REASONS
    {
            
      NO_BATTLE_POINTS_WRONG_LOBBY_TYPE = 1,
            
      NO_BATTLE_POINTS_PRACTICE_BOTS = 2,
            
      NO_BATTLE_POINTS_CHEATS_ENABLED = 3,
            
      NO_BATTLE_POINTS_LOW_PRIORITY = 4
    }
  
    public enum DOTA_CHAT_INFORMATIONAL
    {
            
      INFO_COOP_BATTLE_POINTS_RULES = 1,
            
      INFO_FROSTIVUS_ABANDON_REMINDER = 2,
            
      INFO_RANKED_REMINDER = 3,
            
      INFO_COOP_LOW_PRIORITY_PASSIVE_REMINDER = 4
    }
  
    public enum DOTA_ABILITY_PING_TYPE
    {
            
      ABILITY_PING_READY = 1,
            
      ABILITY_PING_MANA = 2,
            
      ABILITY_PING_COOLDOWN = 3
    }
  
    public enum DOTA_COMBATLOG_TYPES
    {
            
      DOTA_COMBATLOG_DAMAGE = 0,
            
      DOTA_COMBATLOG_HEAL = 1,
            
      DOTA_COMBATLOG_MODIFIER_ADD = 2,
            
      DOTA_COMBATLOG_MODIFIER_REMOVE = 3,
            
      DOTA_COMBATLOG_DEATH = 4,
            
      DOTA_COMBATLOG_ABILITY = 5,
            
      DOTA_COMBATLOG_ITEM = 6
    }
  
    public enum EDotaEntityMessages
    {
            
      DOTA_UNIT_SPEECH = 0,
            
      DOTA_UNIT_SPEECH_MUTE = 1,
            
      DOTA_UNIT_ADD_GESTURE = 2,
            
      DOTA_UNIT_REMOVE_GESTURE = 3,
            
      DOTA_UNIT_REMOVE_ALL_GESTURES = 4,
            
      DOTA_UNIT_FADE_GESTURE = 6,
            
      DOTA_UNIT_SPEECH_CLIENTSIDE_RULES = 7
    }
  
    public enum DOTA_PARTICLE_MESSAGE
    {
            
      DOTA_PARTICLE_MANAGER_EVENT_CREATE = 0,
            
      DOTA_PARTICLE_MANAGER_EVENT_UPDATE = 1,
            
      DOTA_PARTICLE_MANAGER_EVENT_UPDATE_FORWARD = 2,
            
      DOTA_PARTICLE_MANAGER_EVENT_UPDATE_ORIENTATION = 3,
            
      DOTA_PARTICLE_MANAGER_EVENT_UPDATE_FALLBACK = 4,
            
      DOTA_PARTICLE_MANAGER_EVENT_UPDATE_ENT = 5,
            
      DOTA_PARTICLE_MANAGER_EVENT_UPDATE_OFFSET = 6,
            
      DOTA_PARTICLE_MANAGER_EVENT_DESTROY = 7,
            
      DOTA_PARTICLE_MANAGER_EVENT_DESTROY_INVOLVING = 8,
            
      DOTA_PARTICLE_MANAGER_EVENT_RELEASE = 9,
            
      DOTA_PARTICLE_MANAGER_EVENT_LATENCY = 10,
            
      DOTA_PARTICLE_MANAGER_EVENT_SHOULD_DRAW = 11,
            
      DOTA_PARTICLE_MANAGER_EVENT_FROZEN = 12
    }
  
    public enum DOTA_OVERHEAD_ALERT
    {
            
      OVERHEAD_ALERT_GOLD = 0,
            
      OVERHEAD_ALERT_DENY = 1,
            
      OVERHEAD_ALERT_CRITICAL = 2,
            
      OVERHEAD_ALERT_XP = 3,
            
      OVERHEAD_ALERT_BONUS_SPELL_DAMAGE = 4,
            
      OVERHEAD_ALERT_MISS = 5,
            
      OVERHEAD_ALERT_DAMAGE = 6,
            
      OVERHEAD_ALERT_EVADE = 7,
            
      OVERHEAD_ALERT_BLOCK = 8,
            
      OVERHEAD_ALERT_BONUS_POISON_DAMAGE = 9,
            
      OVERHEAD_ALERT_HEAL = 10,
            
      OVERHEAD_ALERT_MANA_ADD = 11,
            
      OVERHEAD_ALERT_MANA_LOSS = 12,
            
      OVERHEAD_ALERT_LAST_HIT_EARLY = 13,
            
      OVERHEAD_ALERT_LAST_HIT_CLOSE = 14,
            
      OVERHEAD_ALERT_LAST_HIT_MISS = 15
    }
  
}
#pragma warning restore 1591
