//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: netmessages.proto
// Note: requires additional types generated from: google/protobuf/descriptor.proto
// Note: requires additional types generated from: networkbasetypes.proto
// Note: requires additional types generated from: network_connection.proto
namespace nora.protos
{
  public partial class CMsg_CVars : global::ProtoBuf.IExtensible
  {
    public CMsg_CVars() {}
    
    private readonly global::System.Collections.Generic.List<CMsg_CVars.CVar> _cvars = new global::System.Collections.Generic.List<CMsg_CVars.CVar>();
    public global::System.Collections.Generic.List<CMsg_CVars.CVar> cvars
    {
      get { return _cvars; }
    }
  
  public partial class CVar : global::ProtoBuf.IExtensible
  {
    public CVar() {}
    

    private string _name = "";
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _value = "";
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CNETMsg_NOP : global::ProtoBuf.IExtensible
  {
    public CNETMsg_NOP() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CNETMsg_Disconnect : global::ProtoBuf.IExtensible
  {
    public CNETMsg_Disconnect() {}
    

    private ENetworkDisconnectionReason _reason = ENetworkDisconnectionReason.NETWORK_DISCONNECT_INVALID;
    public ENetworkDisconnectionReason reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CNETMsg_File : global::ProtoBuf.IExtensible
  {
    public CNETMsg_File() {}
    

    private int _transfer_id = default(int);
    public int transfer_id
    {
      get { return _transfer_id; }
      set { _transfer_id = value; }
    }

    private string _file_name = "";
    public string file_name
    {
      get { return _file_name; }
      set { _file_name = value; }
    }

    private bool _is_replay_demo_file = default(bool);
    public bool is_replay_demo_file
    {
      get { return _is_replay_demo_file; }
      set { _is_replay_demo_file = value; }
    }

    private bool _deny = default(bool);
    public bool deny
    {
      get { return _deny; }
      set { _deny = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CNETMsg_SplitScreenUser : global::ProtoBuf.IExtensible
  {
    public CNETMsg_SplitScreenUser() {}
    

    private int _slot = default(int);
    public int slot
    {
      get { return _slot; }
      set { _slot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CNETMsg_Tick : global::ProtoBuf.IExtensible
  {
    public CNETMsg_Tick() {}
    

    private uint _tick = default(uint);
    public uint tick
    {
      get { return _tick; }
      set { _tick = value; }
    }

    private uint _host_computationtime = default(uint);
    public uint host_computationtime
    {
      get { return _host_computationtime; }
      set { _host_computationtime = value; }
    }

    private uint _host_computationtime_std_deviation = default(uint);
    public uint host_computationtime_std_deviation
    {
      get { return _host_computationtime_std_deviation; }
      set { _host_computationtime_std_deviation = value; }
    }

    private uint _host_framestarttime_std_deviation = default(uint);
    public uint host_framestarttime_std_deviation
    {
      get { return _host_framestarttime_std_deviation; }
      set { _host_framestarttime_std_deviation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CNETMsg_StringCmd : global::ProtoBuf.IExtensible
  {
    public CNETMsg_StringCmd() {}
    

    private string _command = "";
    public string command
    {
      get { return _command; }
      set { _command = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CNETMsg_SetConVar : global::ProtoBuf.IExtensible
  {
    public CNETMsg_SetConVar() {}
    

    private CMsg_CVars _convars = null;
    public CMsg_CVars convars
    {
      get { return _convars; }
      set { _convars = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CNETMsg_SignonState : global::ProtoBuf.IExtensible
  {
    public CNETMsg_SignonState() {}
    

    private uint _signon_state = default(uint);
    public uint signon_state
    {
      get { return _signon_state; }
      set { _signon_state = value; }
    }

    private uint _spawn_count = default(uint);
    public uint spawn_count
    {
      get { return _spawn_count; }
      set { _spawn_count = value; }
    }

    private uint _num_server_players = default(uint);
    public uint num_server_players
    {
      get { return _num_server_players; }
      set { _num_server_players = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _players_networkids = new global::System.Collections.Generic.List<string>();
    public global::System.Collections.Generic.List<string> players_networkids
    {
      get { return _players_networkids; }
    }
  

    private string _map_name = "";
    public string map_name
    {
      get { return _map_name; }
      set { _map_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CCLCMsg_ClientInfo : global::ProtoBuf.IExtensible
  {
    public CCLCMsg_ClientInfo() {}
    

    private uint _send_table_crc = default(uint);
    public uint send_table_crc
    {
      get { return _send_table_crc; }
      set { _send_table_crc = value; }
    }

    private uint _server_count = default(uint);
    public uint server_count
    {
      get { return _server_count; }
      set { _server_count = value; }
    }

    private bool _is_hltv = default(bool);
    public bool is_hltv
    {
      get { return _is_hltv; }
      set { _is_hltv = value; }
    }

    private bool _is_replay = default(bool);
    public bool is_replay
    {
      get { return _is_replay; }
      set { _is_replay = value; }
    }

    private uint _friends_id = default(uint);
    public uint friends_id
    {
      get { return _friends_id; }
      set { _friends_id = value; }
    }

    private string _friends_name = "";
    public string friends_name
    {
      get { return _friends_name; }
      set { _friends_name = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _custom_files = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> custom_files
    {
      get { return _custom_files; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CCLCMsg_Move : global::ProtoBuf.IExtensible
  {
    public CCLCMsg_Move() {}
    

    private uint _num_backup_commands = default(uint);
    public uint num_backup_commands
    {
      get { return _num_backup_commands; }
      set { _num_backup_commands = value; }
    }

    private uint _num_new_commands = default(uint);
    public uint num_new_commands
    {
      get { return _num_new_commands; }
      set { _num_new_commands = value; }
    }

    private byte[] _data = null;
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CCLCMsg_VoiceData : global::ProtoBuf.IExtensible
  {
    public CCLCMsg_VoiceData() {}
    

    private byte[] _data = null;
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }

    private ulong _xuid = default(ulong);
    public ulong xuid
    {
      get { return _xuid; }
      set { _xuid = value; }
    }

    private VoiceDataFormat_t _format = VoiceDataFormat_t.VOICEDATA_FORMAT_STEAM;
    public VoiceDataFormat_t format
    {
      get { return _format; }
      set { _format = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CCLCMsg_BaselineAck : global::ProtoBuf.IExtensible
  {
    public CCLCMsg_BaselineAck() {}
    

    private int _baseline_tick = default(int);
    public int baseline_tick
    {
      get { return _baseline_tick; }
      set { _baseline_tick = value; }
    }

    private int _baseline_nr = default(int);
    public int baseline_nr
    {
      get { return _baseline_nr; }
      set { _baseline_nr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CCLCMsg_ListenEvents : global::ProtoBuf.IExtensible
  {
    public CCLCMsg_ListenEvents() {}
    
    private readonly global::System.Collections.Generic.List<uint> _event_mask = new global::System.Collections.Generic.List<uint>();
    public global::System.Collections.Generic.List<uint> event_mask
    {
      get { return _event_mask; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CCLCMsg_RespondCvarValue : global::ProtoBuf.IExtensible
  {
    public CCLCMsg_RespondCvarValue() {}
    

    private int _cookie = default(int);
    public int cookie
    {
      get { return _cookie; }
      set { _cookie = value; }
    }

    private int _status_code = default(int);
    public int status_code
    {
      get { return _status_code; }
      set { _status_code = value; }
    }

    private string _name = "";
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _value = "";
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CCLCMsg_FileCRCCheck : global::ProtoBuf.IExtensible
  {
    public CCLCMsg_FileCRCCheck() {}
    

    private int _code_path = default(int);
    public int code_path
    {
      get { return _code_path; }
      set { _code_path = value; }
    }

    private string _path = "";
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }

    private int _code_filename = default(int);
    public int code_filename
    {
      get { return _code_filename; }
      set { _code_filename = value; }
    }

    private string _filename = "";
    public string filename
    {
      get { return _filename; }
      set { _filename = value; }
    }

    private uint _crc = default(uint);
    public uint crc
    {
      get { return _crc; }
      set { _crc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CCLCMsg_LoadingProgress : global::ProtoBuf.IExtensible
  {
    public CCLCMsg_LoadingProgress() {}
    

    private int _progress = default(int);
    public int progress
    {
      get { return _progress; }
      set { _progress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CCLCMsg_SplitPlayerConnect : global::ProtoBuf.IExtensible
  {
    public CCLCMsg_SplitPlayerConnect() {}
    

    private CMsg_CVars _convars = null;
    public CMsg_CVars convars
    {
      get { return _convars; }
      set { _convars = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CCLCMsg_ClientMessage : global::ProtoBuf.IExtensible
  {
    public CCLCMsg_ClientMessage() {}
    

    private int _msg_type = default(int);
    public int msg_type
    {
      get { return _msg_type; }
      set { _msg_type = value; }
    }

    private byte[] _data = null;
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_ServerInfo : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_ServerInfo() {}
    

    private int _protocol = default(int);
    public int protocol
    {
      get { return _protocol; }
      set { _protocol = value; }
    }

    private int _server_count = default(int);
    public int server_count
    {
      get { return _server_count; }
      set { _server_count = value; }
    }

    private bool _is_dedicated = default(bool);
    public bool is_dedicated
    {
      get { return _is_dedicated; }
      set { _is_dedicated = value; }
    }

    private bool _is_hltv = default(bool);
    public bool is_hltv
    {
      get { return _is_hltv; }
      set { _is_hltv = value; }
    }

    private bool _is_replay = default(bool);
    public bool is_replay
    {
      get { return _is_replay; }
      set { _is_replay = value; }
    }

    private int _c_os = default(int);
    public int c_os
    {
      get { return _c_os; }
      set { _c_os = value; }
    }

    private uint _map_crc = default(uint);
    public uint map_crc
    {
      get { return _map_crc; }
      set { _map_crc = value; }
    }

    private uint _client_crc = default(uint);
    public uint client_crc
    {
      get { return _client_crc; }
      set { _client_crc = value; }
    }

    private uint _string_table_crc = default(uint);
    public uint string_table_crc
    {
      get { return _string_table_crc; }
      set { _string_table_crc = value; }
    }

    private int _max_clients = default(int);
    public int max_clients
    {
      get { return _max_clients; }
      set { _max_clients = value; }
    }

    private int _max_classes = default(int);
    public int max_classes
    {
      get { return _max_classes; }
      set { _max_classes = value; }
    }

    private int _player_slot = default(int);
    public int player_slot
    {
      get { return _player_slot; }
      set { _player_slot = value; }
    }

    private float _tick_interval = default(float);
    public float tick_interval
    {
      get { return _tick_interval; }
      set { _tick_interval = value; }
    }

    private string _game_dir = "";
    public string game_dir
    {
      get { return _game_dir; }
      set { _game_dir = value; }
    }

    private string _map_name = "";
    public string map_name
    {
      get { return _map_name; }
      set { _map_name = value; }
    }

    private string _sky_name = "";
    public string sky_name
    {
      get { return _sky_name; }
      set { _sky_name = value; }
    }

    private string _host_name = "";
    public string host_name
    {
      get { return _host_name; }
      set { _host_name = value; }
    }

    private string _addon_name = "";
    public string addon_name
    {
      get { return _addon_name; }
      set { _addon_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_ClassInfo : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_ClassInfo() {}
    

    private bool _create_on_client = default(bool);
    public bool create_on_client
    {
      get { return _create_on_client; }
      set { _create_on_client = value; }
    }
    private readonly global::System.Collections.Generic.List<CSVCMsg_ClassInfo.class_t> _classes = new global::System.Collections.Generic.List<CSVCMsg_ClassInfo.class_t>();
    public global::System.Collections.Generic.List<CSVCMsg_ClassInfo.class_t> classes
    {
      get { return _classes; }
    }
  
  public partial class class_t : global::ProtoBuf.IExtensible
  {
    public class_t() {}
    

    private int _class_id = default(int);
    public int class_id
    {
      get { return _class_id; }
      set { _class_id = value; }
    }

    private string _data_table_name = "";
    public string data_table_name
    {
      get { return _data_table_name; }
      set { _data_table_name = value; }
    }

    private string _class_name = "";
    public string class_name
    {
      get { return _class_name; }
      set { _class_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_SetPause : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_SetPause() {}
    

    private bool _paused = default(bool);
    public bool paused
    {
      get { return _paused; }
      set { _paused = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_VoiceInit : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_VoiceInit() {}
    

    private int _quality = default(int);
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }

    private string _codec = "";
    public string codec
    {
      get { return _codec; }
      set { _codec = value; }
    }

    private int _version = (int)0;
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_Print : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_Print() {}
    

    private string _text = "";
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_Sounds : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_Sounds() {}
    

    private bool _reliable_sound = default(bool);
    public bool reliable_sound
    {
      get { return _reliable_sound; }
      set { _reliable_sound = value; }
    }
    private readonly global::System.Collections.Generic.List<CSVCMsg_Sounds.sounddata_t> _sounds = new global::System.Collections.Generic.List<CSVCMsg_Sounds.sounddata_t>();
    public global::System.Collections.Generic.List<CSVCMsg_Sounds.sounddata_t> sounds
    {
      get { return _sounds; }
    }
  
  public partial class sounddata_t : global::ProtoBuf.IExtensible
  {
    public sounddata_t() {}
    

    private int _origin_x = default(int);
    public int origin_x
    {
      get { return _origin_x; }
      set { _origin_x = value; }
    }

    private int _origin_y = default(int);
    public int origin_y
    {
      get { return _origin_y; }
      set { _origin_y = value; }
    }

    private int _origin_z = default(int);
    public int origin_z
    {
      get { return _origin_z; }
      set { _origin_z = value; }
    }

    private uint _volume = default(uint);
    public uint volume
    {
      get { return _volume; }
      set { _volume = value; }
    }

    private float _delay_value = default(float);
    public float delay_value
    {
      get { return _delay_value; }
      set { _delay_value = value; }
    }

    private int _sequence_number = default(int);
    public int sequence_number
    {
      get { return _sequence_number; }
      set { _sequence_number = value; }
    }

    private int _entity_index = default(int);
    public int entity_index
    {
      get { return _entity_index; }
      set { _entity_index = value; }
    }

    private int _channel = default(int);
    public int channel
    {
      get { return _channel; }
      set { _channel = value; }
    }

    private int _pitch = default(int);
    public int pitch
    {
      get { return _pitch; }
      set { _pitch = value; }
    }

    private int _flags = default(int);
    public int flags
    {
      get { return _flags; }
      set { _flags = value; }
    }

    private uint _sound_num = default(uint);
    public uint sound_num
    {
      get { return _sound_num; }
      set { _sound_num = value; }
    }

    private uint _sound_num_handle = default(uint);
    public uint sound_num_handle
    {
      get { return _sound_num_handle; }
      set { _sound_num_handle = value; }
    }

    private int _speaker_entity = default(int);
    public int speaker_entity
    {
      get { return _speaker_entity; }
      set { _speaker_entity = value; }
    }

    private int _random_seed = default(int);
    public int random_seed
    {
      get { return _random_seed; }
      set { _random_seed = value; }
    }

    private int _sound_level = default(int);
    public int sound_level
    {
      get { return _sound_level; }
      set { _sound_level = value; }
    }

    private bool _is_sentence = default(bool);
    public bool is_sentence
    {
      get { return _is_sentence; }
      set { _is_sentence = value; }
    }

    private bool _is_ambient = default(bool);
    public bool is_ambient
    {
      get { return _is_ambient; }
      set { _is_ambient = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_Prefetch : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_Prefetch() {}
    

    private int _sound_index = default(int);
    public int sound_index
    {
      get { return _sound_index; }
      set { _sound_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_SetView : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_SetView() {}
    

    private int _entity_index = default(int);
    public int entity_index
    {
      get { return _entity_index; }
      set { _entity_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_FixAngle : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_FixAngle() {}
    

    private bool _relative = default(bool);
    public bool relative
    {
      get { return _relative; }
      set { _relative = value; }
    }

    private CMsgQAngle _angle = null;
    public CMsgQAngle angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_CrosshairAngle : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_CrosshairAngle() {}
    

    private CMsgQAngle _angle = null;
    public CMsgQAngle angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_BSPDecal : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_BSPDecal() {}
    

    private CMsgVector _pos = null;
    public CMsgVector pos
    {
      get { return _pos; }
      set { _pos = value; }
    }

    private int _decal_texture_index = default(int);
    public int decal_texture_index
    {
      get { return _decal_texture_index; }
      set { _decal_texture_index = value; }
    }

    private int _entity_index = default(int);
    public int entity_index
    {
      get { return _entity_index; }
      set { _entity_index = value; }
    }

    private int _model_index = default(int);
    public int model_index
    {
      get { return _model_index; }
      set { _model_index = value; }
    }

    private bool _low_priority = default(bool);
    public bool low_priority
    {
      get { return _low_priority; }
      set { _low_priority = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_SplitScreen : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_SplitScreen() {}
    

    private ESplitScreenMessageType _type = ESplitScreenMessageType.MSG_SPLITSCREEN_ADDUSER;
    public ESplitScreenMessageType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private int _slot = default(int);
    public int slot
    {
      get { return _slot; }
      set { _slot = value; }
    }

    private int _player_index = default(int);
    public int player_index
    {
      get { return _player_index; }
      set { _player_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_GetCvarValue : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_GetCvarValue() {}
    

    private int _cookie = default(int);
    public int cookie
    {
      get { return _cookie; }
      set { _cookie = value; }
    }

    private string _cvar_name = "";
    public string cvar_name
    {
      get { return _cvar_name; }
      set { _cvar_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_Menu : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_Menu() {}
    

    private int _dialog_type = default(int);
    public int dialog_type
    {
      get { return _dialog_type; }
      set { _dialog_type = value; }
    }

    private byte[] _menu_key_values = null;
    public byte[] menu_key_values
    {
      get { return _menu_key_values; }
      set { _menu_key_values = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_SendTable : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_SendTable() {}
    

    private bool _is_end = default(bool);
    public bool is_end
    {
      get { return _is_end; }
      set { _is_end = value; }
    }

    private string _net_table_name = "";
    public string net_table_name
    {
      get { return _net_table_name; }
      set { _net_table_name = value; }
    }

    private bool _needs_decoder = default(bool);
    public bool needs_decoder
    {
      get { return _needs_decoder; }
      set { _needs_decoder = value; }
    }
    private readonly global::System.Collections.Generic.List<CSVCMsg_SendTable.sendprop_t> _props = new global::System.Collections.Generic.List<CSVCMsg_SendTable.sendprop_t>();
    public global::System.Collections.Generic.List<CSVCMsg_SendTable.sendprop_t> props
    {
      get { return _props; }
    }
  
  public partial class sendprop_t : global::ProtoBuf.IExtensible
  {
    public sendprop_t() {}
    

    private int _type = default(int);
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }

    private string _var_name = "";
    public string var_name
    {
      get { return _var_name; }
      set { _var_name = value; }
    }

    private int _flags = default(int);
    public int flags
    {
      get { return _flags; }
      set { _flags = value; }
    }

    private int _priority = default(int);
    public int priority
    {
      get { return _priority; }
      set { _priority = value; }
    }

    private string _dt_name = "";
    public string dt_name
    {
      get { return _dt_name; }
      set { _dt_name = value; }
    }

    private int _num_elements = default(int);
    public int num_elements
    {
      get { return _num_elements; }
      set { _num_elements = value; }
    }

    private float _low_value = default(float);
    public float low_value
    {
      get { return _low_value; }
      set { _low_value = value; }
    }

    private float _high_value = default(float);
    public float high_value
    {
      get { return _high_value; }
      set { _high_value = value; }
    }

    private int _num_bits = default(int);
    public int num_bits
    {
      get { return _num_bits; }
      set { _num_bits = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_GameEventList : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_GameEventList() {}
    
    private readonly global::System.Collections.Generic.List<CSVCMsg_GameEventList.descriptor_t> _descriptors = new global::System.Collections.Generic.List<CSVCMsg_GameEventList.descriptor_t>();
    public global::System.Collections.Generic.List<CSVCMsg_GameEventList.descriptor_t> descriptors
    {
      get { return _descriptors; }
    }
  
  public partial class key_t : global::ProtoBuf.IExtensible
  {
    public key_t() {}
    

    private int _type = default(int);
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }

    private string _name = "";
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class descriptor_t : global::ProtoBuf.IExtensible
  {
    public descriptor_t() {}
    

    private int _eventid = default(int);
    public int eventid
    {
      get { return _eventid; }
      set { _eventid = value; }
    }

    private string _name = "";
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<CSVCMsg_GameEventList.key_t> _keys = new global::System.Collections.Generic.List<CSVCMsg_GameEventList.key_t>();
    public global::System.Collections.Generic.List<CSVCMsg_GameEventList.key_t> keys
    {
      get { return _keys; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_PacketEntities : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_PacketEntities() {}
    

    private int _max_entries = default(int);
    public int max_entries
    {
      get { return _max_entries; }
      set { _max_entries = value; }
    }

    private int _updated_entries = default(int);
    public int updated_entries
    {
      get { return _updated_entries; }
      set { _updated_entries = value; }
    }

    private bool _is_delta = default(bool);
    public bool is_delta
    {
      get { return _is_delta; }
      set { _is_delta = value; }
    }

    private bool _update_baseline = default(bool);
    public bool update_baseline
    {
      get { return _update_baseline; }
      set { _update_baseline = value; }
    }

    private int _baseline = default(int);
    public int baseline
    {
      get { return _baseline; }
      set { _baseline = value; }
    }

    private int _delta_from = default(int);
    public int delta_from
    {
      get { return _delta_from; }
      set { _delta_from = value; }
    }

    private byte[] _entity_data = null;
    public byte[] entity_data
    {
      get { return _entity_data; }
      set { _entity_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_TempEntities : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_TempEntities() {}
    

    private bool _reliable = default(bool);
    public bool reliable
    {
      get { return _reliable; }
      set { _reliable = value; }
    }

    private int _num_entries = default(int);
    public int num_entries
    {
      get { return _num_entries; }
      set { _num_entries = value; }
    }

    private byte[] _entity_data = null;
    public byte[] entity_data
    {
      get { return _entity_data; }
      set { _entity_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_CreateStringTable : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_CreateStringTable() {}
    

    private string _name = "";
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private int _max_entries = default(int);
    public int max_entries
    {
      get { return _max_entries; }
      set { _max_entries = value; }
    }

    private int _num_entries = default(int);
    public int num_entries
    {
      get { return _num_entries; }
      set { _num_entries = value; }
    }

    private bool _user_data_fixed_size = default(bool);
    public bool user_data_fixed_size
    {
      get { return _user_data_fixed_size; }
      set { _user_data_fixed_size = value; }
    }

    private int _user_data_size = default(int);
    public int user_data_size
    {
      get { return _user_data_size; }
      set { _user_data_size = value; }
    }

    private int _user_data_size_bits = default(int);
    public int user_data_size_bits
    {
      get { return _user_data_size_bits; }
      set { _user_data_size_bits = value; }
    }

    private int _flags = default(int);
    public int flags
    {
      get { return _flags; }
      set { _flags = value; }
    }

    private byte[] _string_data = null;
    public byte[] string_data
    {
      get { return _string_data; }
      set { _string_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_UpdateStringTable : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_UpdateStringTable() {}
    

    private int _table_id = default(int);
    public int table_id
    {
      get { return _table_id; }
      set { _table_id = value; }
    }

    private int _num_changed_entries = default(int);
    public int num_changed_entries
    {
      get { return _num_changed_entries; }
      set { _num_changed_entries = value; }
    }

    private byte[] _string_data = null;
    public byte[] string_data
    {
      get { return _string_data; }
      set { _string_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_VoiceData : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_VoiceData() {}
    

    private int _client = default(int);
    public int client
    {
      get { return _client; }
      set { _client = value; }
    }

    private bool _proximity = default(bool);
    public bool proximity
    {
      get { return _proximity; }
      set { _proximity = value; }
    }

    private ulong _xuid = default(ulong);
    public ulong xuid
    {
      get { return _xuid; }
      set { _xuid = value; }
    }

    private int _audible_mask = default(int);
    public int audible_mask
    {
      get { return _audible_mask; }
      set { _audible_mask = value; }
    }

    private byte[] _voice_data = null;
    public byte[] voice_data
    {
      get { return _voice_data; }
      set { _voice_data = value; }
    }

    private VoiceDataFormat_t _format = VoiceDataFormat_t.VOICEDATA_FORMAT_STEAM;
    public VoiceDataFormat_t format
    {
      get { return _format; }
      set { _format = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_PacketReliable : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_PacketReliable() {}
    

    private int _tick = default(int);
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }

    private int _messagessize = default(int);
    public int messagessize
    {
      get { return _messagessize; }
      set { _messagessize = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CSVCMsg_FullFrameSplit : global::ProtoBuf.IExtensible
  {
    public CSVCMsg_FullFrameSplit() {}
    

    private int _tick = default(int);
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }

    private int _section = default(int);
    public int section
    {
      get { return _section; }
      set { _section = value; }
    }

    private int _total = default(int);
    public int total
    {
      get { return _total; }
      set { _total = value; }
    }

    private byte[] _data = null;
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public enum NET_Messages
    {
            
      net_NOP = 0,
            
      net_Disconnect = 1,
            
      net_File = 2,
            
      net_SplitScreenUser = 3,
            
      net_Tick = 4,
            
      net_StringCmd = 5,
            
      net_SetConVar = 6,
            
      net_SignonState = 7
    }
  
    public enum CLC_Messages
    {
            
      clc_ClientInfo = 8,
            
      clc_Move = 9,
            
      clc_VoiceData = 10,
            
      clc_BaselineAck = 11,
            
      clc_ListenEvents = 12,
            
      clc_RespondCvarValue = 13,
            
      clc_FileCRCCheck = 14,
            
      clc_LoadingProgress = 15,
            
      clc_SplitPlayerConnect = 16,
            
      clc_ClientMessage = 17
    }
  
    public enum VoiceDataFormat_t
    {
            
      VOICEDATA_FORMAT_STEAM = 0,
            
      VOICEDATA_FORMAT_ENGINE = 1
    }
  
    public enum SVC_Messages
    {
            
      svc_ServerInfo = 8,
            
      svc_SendTable = 9,
            
      svc_ClassInfo = 10,
            
      svc_SetPause = 11,
            
      svc_CreateStringTable = 12,
            
      svc_UpdateStringTable = 13,
            
      svc_VoiceInit = 14,
            
      svc_VoiceData = 15,
            
      svc_Print = 16,
            
      svc_Sounds = 17,
            
      svc_SetView = 18,
            
      svc_FixAngle = 19,
            
      svc_CrosshairAngle = 20,
            
      svc_BSPDecal = 21,
            
      svc_SplitScreen = 22,
            
      svc_UserMessage = 23,
            
      svc_EntityMessage = 24,
            
      svc_GameEvent = 25,
            
      svc_PacketEntities = 26,
            
      svc_TempEntities = 27,
            
      svc_Prefetch = 28,
            
      svc_Menu = 29,
            
      svc_GameEventList = 30,
            
      svc_GetCvarValue = 31,
            
      svc_PacketReliable = 32,
            
      svc_FullFrameSplit = 33
    }
  
    public enum ESplitScreenMessageType
    {
            
      MSG_SPLITSCREEN_ADDUSER = 0,
            
      MSG_SPLITSCREEN_REMOVEUSER = 1
    }
  
}
#pragma warning restore 1591
