//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: usermessages.proto
// Note: requires additional types generated from: google/protobuf/descriptor.proto
// Note: requires additional types generated from: networkbasetypes.proto
namespace nora.protos
{
  public partial class CUserMsg_AchievementEvent : global::ProtoBuf.IExtensible
  {
    public CUserMsg_AchievementEvent() {}
    

    private uint _achievement = default(uint);
    public uint achievement
    {
      get { return _achievement; }
      set { _achievement = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_CloseCaption : global::ProtoBuf.IExtensible
  {
    public CUserMsg_CloseCaption() {}
    

    private uint _hash = default(uint);
    public uint hash
    {
      get { return _hash; }
      set { _hash = value; }
    }

    private float _duration = default(float);
    public float duration
    {
      get { return _duration; }
      set { _duration = value; }
    }

    private bool _from_player = default(bool);
    public bool from_player
    {
      get { return _from_player; }
      set { _from_player = value; }
    }

    private int _ent_index = default(int);
    public int ent_index
    {
      get { return _ent_index; }
      set { _ent_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_CurrentTimescale : global::ProtoBuf.IExtensible
  {
    public CUserMsg_CurrentTimescale() {}
    

    private float _current = default(float);
    public float current
    {
      get { return _current; }
      set { _current = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_DesiredTimescale : global::ProtoBuf.IExtensible
  {
    public CUserMsg_DesiredTimescale() {}
    

    private float _desired = default(float);
    public float desired
    {
      get { return _desired; }
      set { _desired = value; }
    }

    private float _duration = default(float);
    public float duration
    {
      get { return _duration; }
      set { _duration = value; }
    }

    private uint _interpolator = default(uint);
    public uint interpolator
    {
      get { return _interpolator; }
      set { _interpolator = value; }
    }

    private float _start_blend_time = default(float);
    public float start_blend_time
    {
      get { return _start_blend_time; }
      set { _start_blend_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_Fade : global::ProtoBuf.IExtensible
  {
    public CUserMsg_Fade() {}
    

    private uint _duration = default(uint);
    public uint duration
    {
      get { return _duration; }
      set { _duration = value; }
    }

    private uint _hold_time = default(uint);
    public uint hold_time
    {
      get { return _hold_time; }
      set { _hold_time = value; }
    }

    private uint _flags = default(uint);
    public uint flags
    {
      get { return _flags; }
      set { _flags = value; }
    }

    private uint _color = default(uint);
    public uint color
    {
      get { return _color; }
      set { _color = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_Shake : global::ProtoBuf.IExtensible
  {
    public CUserMsg_Shake() {}
    

    private uint _command = default(uint);
    public uint command
    {
      get { return _command; }
      set { _command = value; }
    }

    private float _amplitude = default(float);
    public float amplitude
    {
      get { return _amplitude; }
      set { _amplitude = value; }
    }

    private float _frequency = default(float);
    public float frequency
    {
      get { return _frequency; }
      set { _frequency = value; }
    }

    private float _duration = default(float);
    public float duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_ShakeDir : global::ProtoBuf.IExtensible
  {
    public CUserMsg_ShakeDir() {}
    

    private CUserMsg_Shake _shake = null;
    public CUserMsg_Shake shake
    {
      get { return _shake; }
      set { _shake = value; }
    }

    private CMsgVector _direction = null;
    public CMsgVector direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_Tilt : global::ProtoBuf.IExtensible
  {
    public CUserMsg_Tilt() {}
    

    private uint _command = default(uint);
    public uint command
    {
      get { return _command; }
      set { _command = value; }
    }

    private bool _ease_in_out = default(bool);
    public bool ease_in_out
    {
      get { return _ease_in_out; }
      set { _ease_in_out = value; }
    }

    private CMsgVector _angle = null;
    public CMsgVector angle
    {
      get { return _angle; }
      set { _angle = value; }
    }

    private float _duration = default(float);
    public float duration
    {
      get { return _duration; }
      set { _duration = value; }
    }

    private float _time = default(float);
    public float time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_SayText : global::ProtoBuf.IExtensible
  {
    public CUserMsg_SayText() {}
    

    private uint _client = default(uint);
    public uint client
    {
      get { return _client; }
      set { _client = value; }
    }

    private string _text = "";
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }

    private bool _chat = default(bool);
    public bool chat
    {
      get { return _chat; }
      set { _chat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_SayText2 : global::ProtoBuf.IExtensible
  {
    public CUserMsg_SayText2() {}
    

    private uint _client = default(uint);
    public uint client
    {
      get { return _client; }
      set { _client = value; }
    }

    private bool _chat = default(bool);
    public bool chat
    {
      get { return _chat; }
      set { _chat = value; }
    }

    private string _format = "";
    public string format
    {
      get { return _format; }
      set { _format = value; }
    }

    private string _prefix = "";
    public string prefix
    {
      get { return _prefix; }
      set { _prefix = value; }
    }

    private string _text = "";
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }

    private string _location = "";
    public string location
    {
      get { return _location; }
      set { _location = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_HudMsg : global::ProtoBuf.IExtensible
  {
    public CUserMsg_HudMsg() {}
    

    private uint _channel = default(uint);
    public uint channel
    {
      get { return _channel; }
      set { _channel = value; }
    }

    private float _x = default(float);
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }

    private float _y = default(float);
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }

    private uint _color1 = default(uint);
    public uint color1
    {
      get { return _color1; }
      set { _color1 = value; }
    }

    private uint _color2 = default(uint);
    public uint color2
    {
      get { return _color2; }
      set { _color2 = value; }
    }

    private uint _effect = default(uint);
    public uint effect
    {
      get { return _effect; }
      set { _effect = value; }
    }

    private float _fade_in_time = default(float);
    public float fade_in_time
    {
      get { return _fade_in_time; }
      set { _fade_in_time = value; }
    }

    private float _fade_out_time = default(float);
    public float fade_out_time
    {
      get { return _fade_out_time; }
      set { _fade_out_time = value; }
    }

    private float _hold_time = default(float);
    public float hold_time
    {
      get { return _hold_time; }
      set { _hold_time = value; }
    }

    private float _fx_time = default(float);
    public float fx_time
    {
      get { return _fx_time; }
      set { _fx_time = value; }
    }

    private string _message = "";
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_HudText : global::ProtoBuf.IExtensible
  {
    public CUserMsg_HudText() {}
    

    private string _message = "";
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_TextMsg : global::ProtoBuf.IExtensible
  {
    public CUserMsg_TextMsg() {}
    

    private uint _dest = default(uint);
    public uint dest
    {
      get { return _dest; }
      set { _dest = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _param = new global::System.Collections.Generic.List<string>();
    public global::System.Collections.Generic.List<string> param
    {
      get { return _param; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_GameTitle : global::ProtoBuf.IExtensible
  {
    public CUserMsg_GameTitle() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_ResetHUD : global::ProtoBuf.IExtensible
  {
    public CUserMsg_ResetHUD() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_SendAudio : global::ProtoBuf.IExtensible
  {
    public CUserMsg_SendAudio() {}
    

    private bool _stop = default(bool);
    public bool stop
    {
      get { return _stop; }
      set { _stop = value; }
    }

    private string _name = "";
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_VoiceMask : global::ProtoBuf.IExtensible
  {
    public CUserMsg_VoiceMask() {}
    
    private readonly global::System.Collections.Generic.List<int> _audible_players_mask = new global::System.Collections.Generic.List<int>();
    public global::System.Collections.Generic.List<int> audible_players_mask
    {
      get { return _audible_players_mask; }
    }
  

    private bool _player_mod_enabled = default(bool);
    public bool player_mod_enabled
    {
      get { return _player_mod_enabled; }
      set { _player_mod_enabled = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_RequestState : global::ProtoBuf.IExtensible
  {
    public CUserMsg_RequestState() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_HintText : global::ProtoBuf.IExtensible
  {
    public CUserMsg_HintText() {}
    

    private string _message = "";
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_KeyHintText : global::ProtoBuf.IExtensible
  {
    public CUserMsg_KeyHintText() {}
    
    private readonly global::System.Collections.Generic.List<string> _messages = new global::System.Collections.Generic.List<string>();
    public global::System.Collections.Generic.List<string> messages
    {
      get { return _messages; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_StatsCrawlMsg : global::ProtoBuf.IExtensible
  {
    public CUserMsg_StatsCrawlMsg() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_StatsSkipState : global::ProtoBuf.IExtensible
  {
    public CUserMsg_StatsSkipState() {}
    

    private int _num_skips = default(int);
    public int num_skips
    {
      get { return _num_skips; }
      set { _num_skips = value; }
    }

    private int _num_players = default(int);
    public int num_players
    {
      get { return _num_players; }
      set { _num_players = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_VoiceSubtitle : global::ProtoBuf.IExtensible
  {
    public CUserMsg_VoiceSubtitle() {}
    

    private int _ent_index = default(int);
    public int ent_index
    {
      get { return _ent_index; }
      set { _ent_index = value; }
    }

    private int _menu = default(int);
    public int menu
    {
      get { return _menu; }
      set { _menu = value; }
    }

    private int _item = default(int);
    public int item
    {
      get { return _item; }
      set { _item = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_VGUIMenu : global::ProtoBuf.IExtensible
  {
    public CUserMsg_VGUIMenu() {}
    

    private string _name = "";
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private bool _show = default(bool);
    public bool show
    {
      get { return _show; }
      set { _show = value; }
    }
    private readonly global::System.Collections.Generic.List<CUserMsg_VGUIMenu.Keys> _keys = new global::System.Collections.Generic.List<CUserMsg_VGUIMenu.Keys>();
    public global::System.Collections.Generic.List<CUserMsg_VGUIMenu.Keys> keys
    {
      get { return _keys; }
    }
  
  public partial class Keys : global::ProtoBuf.IExtensible
  {
    public Keys() {}
    

    private string _name = "";
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _value = "";
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_Geiger : global::ProtoBuf.IExtensible
  {
    public CUserMsg_Geiger() {}
    

    private int _range = default(int);
    public int range
    {
      get { return _range; }
      set { _range = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_Rumble : global::ProtoBuf.IExtensible
  {
    public CUserMsg_Rumble() {}
    

    private int _index = default(int);
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }

    private int _data = default(int);
    public int data
    {
      get { return _data; }
      set { _data = value; }
    }

    private int _flags = default(int);
    public int flags
    {
      get { return _flags; }
      set { _flags = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_Train : global::ProtoBuf.IExtensible
  {
    public CUserMsg_Train() {}
    

    private int _train = default(int);
    public int train
    {
      get { return _train; }
      set { _train = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_SayTextChannel : global::ProtoBuf.IExtensible
  {
    public CUserMsg_SayTextChannel() {}
    

    private int _player = default(int);
    public int player
    {
      get { return _player; }
      set { _player = value; }
    }

    private int _channel = default(int);
    public int channel
    {
      get { return _channel; }
      set { _channel = value; }
    }

    private string _text = "";
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_MessageText : global::ProtoBuf.IExtensible
  {
    public CUserMsg_MessageText() {}
    

    private uint _color = default(uint);
    public uint color
    {
      get { return _color; }
      set { _color = value; }
    }

    private string _text = "";
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  public partial class CUserMsg_CameraTransition : global::ProtoBuf.IExtensible
  {
    public CUserMsg_CameraTransition() {}
    

    private uint _camera_type = default(uint);
    public uint camera_type
    {
      get { return _camera_type; }
      set { _camera_type = value; }
    }

    private float _duration = default(float);
    public float duration
    {
      get { return _duration; }
      set { _duration = value; }
    }

    private CUserMsg_CameraTransition.Transition_DataDriven _params_data_driven = null;
    public CUserMsg_CameraTransition.Transition_DataDriven params_data_driven
    {
      get { return _params_data_driven; }
      set { _params_data_driven = value; }
    }
  public partial class Transition_DataDriven : global::ProtoBuf.IExtensible
  {
    public Transition_DataDriven() {}
    

    private string _filename = "";
    public string filename
    {
      get { return _filename; }
      set { _filename = value; }
    }

    private int _attach_ent_index = default(int);
    public int attach_ent_index
    {
      get { return _attach_ent_index; }
      set { _attach_ent_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public enum EBaseUserMessages
    {
            
      UM_AchievementEvent = 1,
            
      UM_CloseCaption = 2,
            
      UM_CloseCaptionDirect = 3,
            
      UM_CurrentTimescale = 4,
            
      UM_DesiredTimescale = 5,
            
      UM_Fade = 6,
            
      UM_GameTitle = 7,
            
      UM_Geiger = 8,
            
      UM_HintText = 9,
            
      UM_HudMsg = 10,
            
      UM_HudText = 11,
            
      UM_KeyHintText = 12,
            
      UM_MessageText = 13,
            
      UM_RequestState = 14,
            
      UM_ResetHUD = 15,
            
      UM_Rumble = 16,
            
      UM_SayText = 17,
            
      UM_SayText2 = 18,
            
      UM_SayTextChannel = 19,
            
      UM_Shake = 20,
            
      UM_ShakeDir = 21,
            
      UM_StatsCrawlMsg = 22,
            
      UM_StatsSkipState = 23,
            
      UM_TextMsg = 24,
            
      UM_Tilt = 25,
            
      UM_Train = 26,
            
      UM_VGUIMenu = 27,
            
      UM_VoiceMask = 28,
            
      UM_VoiceSubtitle = 29,
            
      UM_SendAudio = 30,
            
      UM_CameraTransition = 31,
            
      UM_MAX_BASE = 63
    }
  
}
#pragma warning restore 1591
